[[categories]]
name = "SDK"
description = "A software development kit. Provides an interface to build software on top of it. "

[[categories]]
name = "Application"
description = "Helps run or work with higher-than-circuit or domain-specifc level of abstraction."

[[categories]]
name = "Tooling"
description = "Helps to develop quantum programs, such as IDEs, debuggers, or other development tooling."

[[categories]]
name = "Compute provider"
description = "Provides access to remote quantum computers (or remote simulators) via Qiskit primitives"
link = "https://quantum.cloud.ibm.com/docs/en/api/qiskit/primitives"

[[categories]]
name = "Circuit simulator"
description = "Simulates a quantum computer on your local classical computer"

[[categories]]
name = "Converter"
description = "Converts Qiskit objects (such as QuantumCircuit) for use in other programs or tools"

[[categories]]
name = "Transpiler plugin"
description = "Implements Qiskit's transpiler plugin interface to compile and optimize quantum circuits"
link = "https://quantum.cloud.ibm.com/docs/en/api/qiskit/transpiler_plugins"

[[categories]]
name = "Unitary synthesis plugin"
description = "Implements Qiskit's unitary synthesis plugin interface to synthesize unitary operations into quantum circuits"
link = "https://quantum.cloud.ibm.com/docs/en/api/qiskit/qiskit.transpiler.passes.synthesis.plugin.UnitarySynthesisPlugin"

[[categories]]
name = "High-level synthesis plugin"
description = "Implements Qiskit's HLS plugin interface to synthesize quantum circuits from more abstract operations"
link = "https://quantum.cloud.ibm.com/docs/en/api/qiskit/qiskit.transpiler.passes.synthesis.plugin.HighLevelSynthesisPlugin"

[[categories]]
name = "Qiskit addon"
description = "Enables algorithm discovery at the utility scale"
link = "https://quantum.cloud.ibm.com/docs/en/guides/addons"

[[categories]]
name = "Game"
description = "Games or playful educational resources"

[[categories]]
name = "Paper artifact"
description = "Code or dataset needed to reproduce a specific paper. Probably, without long-term support."

[[categories]]
name = "Other"
description = "Projects that extend, interface with, or use Qiskit in interesting ways"

[[labels]]
name = "chemistry"
description = "Applies quantum computing to chemistry"

[[labels]]
name = "C"
description = "API callable from C programming language"

[[labels]]
name = "C++"
description = "API callable from C++ programming language"

[[labels]]
name = "Julia"
description = "API callable from Julia programming language"

[[labels]]
name = "Rust"
description = "API callable from Rust programming language"

[[labels]]
name = "OCaml"
description = "API callable from OCaml programming language"


[[labels]]
name = "error correction"
description = "Performs or investigates quantum error correction"

[[labels]]
name = "error mitigation"
description = "Tools for mitigating errors"

[[labels]]
name = "finance"
description = "Applies quantum computing to finance"

[[labels]]
name = "QML"
description = "Applies quantum computing to machine learning"

[[labels]]
name = "optimization"
description = "Applies quantum computing to optimization problems"

[[labels]]
name = "physics"
description = "Applies quantum computing to physics"

[[labels]]
name = "provider"
description = "Implements a Qiskit provider or/and Qiskit primitives"
link = "https://quantum.cloud.ibm.com/docs/en/api/qiskit/providers"

[[labels]]
name = "cloud service"
description = "Requieres an account in a cloud service."

[[labels]]
name = "HPC"
description = "Targets High-Performance Computing use-cases."

[[labels]]
name = "quantum information"
description = "Tools for quantum information experiments"

[[labels]]
name = "research"
description = "Implements ideas from papers and/or cutting-edge research"

[[labels]]
name = "demo"
description = "Implements a demo or a proof of concept."

[[labels]]
name = "circuit manipulation"
description = "Optimizes or modifies Qiskit quantum circuits."

[[labels]]
name = "circuit building"
description = "Builds and outputs Qiskit quantum circuits."

[[labels]]
name = "openqasm"
description = "Interfaces with OpenQASM."

