name = "antinature"
url = "https://github.com/mk0dz/antinature"
description = "A Python framework for studying antimatter systems through computational quantum chemistry approaches."
licence = "MIT license"
contact_info = "mukulpal108@hotmail.com"
affiliations = "Since I have worked independently so no organization is affiliated to the project, Even I am not an official student of any institute, So I dont have any choice but I am desirate to associate it with IBM or Cern, because work is associated to them."
labels = [ "chemistry",]
website = "https://antinature.vercel.app/"
group = "Application"
documentation = "https://antinature.vercel.app/docs/"
uuid = "83868867-87d7-40c1-a0cb-7e68be6b22ad"
badge = "https://qisk.it/e-83868867"

[github]
url = "https://github.com/mk0dz/antinature"
owner = "mk0dz"
repo = "antinature"
stars = 3
homepage = "https://antinature.dirac.fun"
license = "MIT License"
description = "py module for studying antimatter using quantum computing approach"
estimated_contributors = 2
total_dependent_repositories = 1
total_dependent_packages = 0
last_commit = 2025-08-11T18:52:41Z

[pypi.antinature]
package_name = "antinature"
version = "0.1.2"
url = "https://pypi.org/project/antinature/"
requires_qiskit = "==1.4.2"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = false
highest_supported_qiskit_release_date = 2025-03-14T17:39:31Z
highest_supported_qiskit_version = "1.4.2"
last_month_downloads = 33
last_180_days_downloads = 276
