name = "Azure Quantum"
url = "https://github.com/microsoft/azure-quantum-python"
description = "Submit quantum jobs written in Q#, Qiskit, or Cirq to the Azure Quantum service."
licence = "MIT license"
labels = [ "provider", "cloud service",]
created_at = 1715084759.598566
group = "Compute provider"
uuid = "8abf631e-bbf0-4624-b9c7-60073981f5b0"
badge = "[![Qiskit Ecosystem](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fqiskit.github.io%2Fecosystem%2Fb%2F8abf631e)](https://qisk.it/e)"

[github]
url = "https://github.com/microsoft/azure-quantum-python"
owner = "microsoft"
repo = "azure-quantum-python"
stars = 144
homepage = "https://learn.microsoft.com/azure/quantum/"
license = "MIT License"
description = "The azure-quantum python package submits jobs to the Azure Quantum service."
estimated_contributors = 58
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2025-12-01T20:55:07Z
last_activity = 2025-12-04T01:31:09Z

[pypi.azure-quantum]
package_name = "azure-quantum"
version = "3.4.0"
url = "https://pypi.org/project/azure-quantum/"
last_month_downloads = 33401
last_180_days_downloads = 94358
