name = "Qiskit Banana Compiler"
url = "https://github.com/somebody/banana-compiler"
description = "Compile bananas into Qiskit circuits. Supports all modern devices, including Musa Ã— paradisiaca."
contact_info = "_No response_"
labels = [ "Rust, Julia",]
website = "https://_no response_"
group = "SDK"
reference_paper = "https://_no response_"
documentation = "https://_no response_"
uuid = "adb27dd9-ce67-46c3-aecc-e99c16ecbe65"
badge = "[![Qiskit Ecosystem](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fqiskit.github.io%2Fecosystem%2Fb%2Fadb27dd9)](https://qisk.it/e)"

[github]
owner = "somebody"
repo = "banana-compiler"
