name = "Blueqat"
url = "https://github.com/Blueqat/Blueqat"
description = "A quantum computing SDK"
licence = "Apache 2.0"
labels = [ "Converter", "Software development kit",]
created_at = 1678827878.864396
updated_at = 1678827878.864397
tier = "Community"
skip_tests = true
stars = 359
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936778828"
package_commit_hash = "0b51250e219ca303654fc28a318c21366584ccd3"
qiskit_version = "0.45.0"
timestamp = 1692696330.719343

[[tests_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936778828"
qiskit_version = "0.44.1"
timestamp = 1692696330.89132

[[tests_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936778828"
qiskit_version = "0.44.1"
timestamp = 1692696330.891324

[[styles_results]]
passed = false
style_type = "pylint"

[[coverages_results]]
passed = false
coverage_type = ""

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.37.0"
qiskit_version = "0.37.0"
timestamp = 1692696330.891338

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.36.2"
qiskit_version = "0.36.2"
timestamp = 1692696330.891341

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.36.2"
qiskit_version = "0.36.2"
timestamp = 1692696330.891345

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.37.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2617548522"
qiskit_version = "0.37.0"
timestamp = 1692696330.891348

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.37.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2617548522"
qiskit_version = "0.37.0"
timestamp = 1692696330.891352

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.37.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824121347"
qiskit_version = "0.37.1"
timestamp = 1692696330.891355

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.37.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824121347"
qiskit_version = "0.37.1"
timestamp = 1692696330.891359

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3180920109"
package_commit_hash = "53e215c31cf3aea51a623dc22883ac92fe74d0b9"
qiskit_version = "0.39.0"
timestamp = 1692696330.891363

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.38.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225638641"
qiskit_version = "0.38.0"
timestamp = 1692696330.891367

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.38.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225638640"
qiskit_version = "0.38.0"
timestamp = 1692696330.891371

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3319732917"
qiskit_version = "0.39.0"
timestamp = 1692696330.891374

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368224539"
qiskit_version = "0.39.0"
timestamp = 1692696330.891378

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.39.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521952019"
qiskit_version = "0.39.2"
timestamp = 1692696330.891381

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.39.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521951991"
qiskit_version = "0.39.2"
timestamp = 1692696330.891385

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937703336"
package_commit_hash = "af0b2220b75fd5cf3980576b1a31f9c4ceb9f99f"
qiskit_version = "0.40.0"
timestamp = 1692696330.891389

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.39.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937703323"
qiskit_version = "0.39.4"
timestamp = 1692696330.891392

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.39.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937703183"
qiskit_version = "0.39.4"
timestamp = 1692696330.891396

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.39.5"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994627601"
qiskit_version = "0.39.5"
timestamp = 1692696330.891399

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.39.5"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994627633"
qiskit_version = "0.39.5"
timestamp = 1692696330.891403

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052482988"
qiskit_version = "0.40.0"
timestamp = 1692696330.891406

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.41.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231021814"
qiskit_version = "0.41.0"
timestamp = 1692696330.89141

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.41.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231021797"
qiskit_version = "0.41.0"
timestamp = 1692696330.891413

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.43.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231021901"
package_commit_hash = "4e3b283157b43687db4260cee6decf17fbb37608"
qiskit_version = "0.43.0"
timestamp = 1692696330.891417

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.41.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414045386"
qiskit_version = "0.41.1"
timestamp = 1692696330.891421

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.41.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414045462"
qiskit_version = "0.41.1"
timestamp = 1692696330.891424

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936778828"
qiskit_version = "0.44.1"
timestamp = 1692696330.891431

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936778828"
qiskit_version = "0.44.1"
timestamp = 1692696330.891435

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936778828"
package_commit_hash = "0b51250e219ca303654fc28a318c21366584ccd3"
qiskit_version = "0.45.0"
timestamp = 1692696330.719343

[configuration]
dependencies_files = [ "requirements.txt",]
extra_dependencies = [ "qiskit", "Cython", "coverage", "pylint",]
tests_command = [ "pytest",]
styles_check_command = [ "pylint -rn blueqat tests",]
coverages_check_command = [ "coverage3 -m pytest", "coverage3 report --fail-under=80",]

[configuration.language]
name = "python"
versions = [ "3.6",]
