name = "Blueqat"
url = "https://github.com/Blueqat/Blueqat"
description = "A quantum computing SDK"
licence = "Apache 2.0"
labels = [ "Converter", "Software development kit",]
created_at = 1678827878.864396
updated_at = 1678827878.864397
stars = 366
group = "other"
