name = "Blueqat"
url = "https://github.com/Blueqat/Blueqat"
description = "A quantum computing SDK"
licence = "Apache 2.0"
labels = [ "convert",]
created_at = 1678827878.864396
updated_at = 1678827878.864397
tier = "Community"
skip_tests = false
stars = 359
[[tests_results]]
test_type = "development"
passed = false
package = "qiskit-terra"
package_version = "0.43.0"
qiskit_version = "0.43.0"
timestamp = 1678827878.855712
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/42310.34.1"
package_commit_hash = "4e3b283157b43687db4260cee6decf17fbb37608"

[[tests_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.41.1"
qiskit_version = "0.41.1"
timestamp = 1678827878.853724
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414045462"

[[tests_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.41.1"
qiskit_version = "0.41.1"
timestamp = 1678827878.855721
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414045386"

[[styles_results]]
style_type = "pylint"
passed = false

[[coverages_results]]
coverage_type = ""
passed = false

[[historical_test_results]]
test_type = "development"
passed = false
package = "qiskit-terra"
package_version = "0.37.0"
qiskit_version = "0.37.0"
timestamp = 1678827878.864336

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.36.2"
qiskit_version = "0.36.2"
timestamp = 1678827878.864341

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.36.2"
qiskit_version = "0.36.2"
timestamp = 1678827878.864343

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.37.0"
qiskit_version = "0.37.0"
timestamp = 1678827878.864346
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2617548522"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.37.0"
qiskit_version = "0.37.0"
timestamp = 1678827878.864348
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2617548522"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.37.1"
qiskit_version = "0.37.1"
timestamp = 1678827878.86435
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824121347"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.37.1"
qiskit_version = "0.37.1"
timestamp = 1678827878.864353
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824121347"

[[historical_test_results]]
test_type = "development"
passed = false
package = "qiskit-terra"
package_version = "0.39.0"
qiskit_version = "0.39.0"
timestamp = 1678827878.864355
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3180.36.09"
package_commit_hash = "53e215c31cf3aea51a623dc22883ac92fe74d0b9"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.38.0"
qiskit_version = "0.38.0"
timestamp = 1678827878.864357
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225638641"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.38.0"
qiskit_version = "0.38.0"
timestamp = 1678827878.864359
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225638640"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.39.0"
qiskit_version = "0.39.0"
timestamp = 1678827878.864362
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3319732917"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.39.0"
qiskit_version = "0.39.0"
timestamp = 1678827878.864364
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368224539"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.39.2"
qiskit_version = "0.39.2"
timestamp = 1678827878.864366
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521952019"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.39.2"
qiskit_version = "0.39.2"
timestamp = 1678827878.864368
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521951991"

[[historical_test_results]]
test_type = "development"
passed = false
package = "qiskit-terra"
package_version = "0.40.0"
qiskit_version = "0.40.0"
timestamp = 1678827878.86437
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937703336"
package_commit_hash = "af0.39.0b75fd5cf3980576b1a31f9c4ceb9f99f"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.39.4"
qiskit_version = "0.39.4"
timestamp = 1678827878.864373
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937703323"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.39.4"
qiskit_version = "0.39.4"
timestamp = 1678827878.864375
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937703183"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.39.5"
qiskit_version = "0.39.5"
timestamp = 1678827878.864377
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994627601"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.39.5"
qiskit_version = "0.39.5"
timestamp = 1678827878.864379
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994627633"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.40.0"
qiskit_version = "0.40.0"
timestamp = 1678827878.864381
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052482988"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.41.0"
qiskit_version = "0.41.0"
timestamp = 1678827878.864384
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231021814"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.41.0"
qiskit_version = "0.41.0"
timestamp = 1678827878.864386
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231021797"

[[historical_test_results]]
test_type = "development"
passed = false
package = "qiskit-terra"
package_version = "0.43.0"
qiskit_version = "0.43.0"
timestamp = 1678827878.864388
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/42310.34.1"
package_commit_hash = "4e3b283157b43687db4260cee6decf17fbb37608"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.41.1"
qiskit_version = "0.41.1"
timestamp = 1678827878.86439
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414045386"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.41.1"
qiskit_version = "0.41.1"
timestamp = 1678827878.853724
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414045462"

[configuration]
dependencies_files = [ "requirements.txt",]
extra_dependencies = [ "qiskit", "Cython", "coverage", "pylint",]
tests_command = [ "pytest",]
styles_check_command = [ "pylint -rn blueqat tests",]
coverages_check_command = [ "coverage3 -m pytest", "coverage3 report --fail-under=80",]

[configuration.language]
name = "python"
versions = [ "3.6",]
