name = "Bosonic Qiskit"
url = "https://github.com/C2QA/bosonic-qiskit"
description = "NQI C2QA project to simulate hybrid boson-qubit systems within Qiskit."
licence = "BSD 2-Clause Simplified or FreeBSD license"
labels = [ "Physics", "Application package",]
ibm_maintained = false
created_at = 1678827878.841977
updated_at = 1678827878.841978
stars = 53
group = "applications"
uuid = "3d8fe04d-8ac0-4282-9eb6-cb458550945a"
