name = "Bosonic Qiskit"
url = "https://github.com/C2QA/bosonic-qiskit"
description = "NQI C2QA project to simulate hybrid boson-qubit systems within Qiskit."
licence = "BSD 2-Clause \"Simplified\" or \"FreeBSD\" license"
labels = [ "physics",]
created_at = 1678827878.841977
updated_at = 1678827878.841978
group = "Application"
uuid = "3d8fe04d-8ac0-4282-9eb6-cb458550945a"
badge = "[![Qiskit Ecosystem](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fqiskit.github.io%2Fecosystem%2Fb%2F3d8fe04d)](https://qisk.it/e)"

[github]
url = "https://github.com/C2QA/bosonic-qiskit"
owner = "C2QA"
repo = "bosonic-qiskit"
stars = 70
license = "BSD 2-Clause \"Simplified\" License"
description = "Extension of Qiskit to support hybrid boson-qubit simulations for the NQI C2QA effort."
estimated_contributors = 10
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2025-11-24T17:18:47Z
last_activity = 2025-12-03T12:04:51Z

[pypi.bosonic-qiskit]
package_name = "bosonic-qiskit"
version = "14.1.1"
url = "https://pypi.org/project/bosonic-qiskit/"
requires_qiskit = "==2.0.0"
compatible_with_qiskit_v1 = false
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2025-04-01T13:49:28Z
highest_supported_qiskit_version = "2.0.0"
last_month_downloads = 487
last_180_days_downloads = 1560
