name = "bosonic-qiskit"
url = "https://github.com/C2QA/bosonic-qiskit"
description = "NQI C2QA project to simulate hybrid boson-qubit systems within Qiskit."
licence = "BSD 2-Clause Simplified or FreeBSD license"
labels = [ "simulation", "physics",]
created_at = 1678827878.841977
updated_at = 1678827878.841978
styles_results = []
coverages_results = []
tier = "Community"
skip_tests = false
stars = 34
[[tests_results]]
test_type = "development"
passed = true
package = "qiskit"
package_version = "0.24.0"
timestamp = 1678827878.839921
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414047438"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"

[[tests_results]]
test_type = "last passing version"
passed = true
package = "qiskit"
package_version = "0.23.2"
timestamp = 1678827878.841942
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414047359"

[[tests_results]]
test_type = "stable"
passed = true
package = "qiskit"
package_version = "0.23.2"
timestamp = 1678827878.841944
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414047359"

[[tests_results]]
test_type = "standard"
passed = true
package = "qiskit"
package_version = "0.22.0"
timestamp = 1678827878.841947
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414047258"

[[historical_test_results]]
test_type = "stable"
passed = true
package = "qiskit"
package_version = "0.22.0"
timestamp = 1678827878.841952
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368225482"

[[historical_test_results]]
test_type = "stable"
passed = true
package = "qiskit"
package_version = "0.22.2"
timestamp = 1678827878.841954
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521953307"

[[historical_test_results]]
test_type = "development"
passed = true
package = "qiskit"
package_version = "0.23.0"
timestamp = 1678827878.841957
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937704942"
package_commit_hash = "af0b2220b75fd5cf3980576b1a31f9c4ceb9f99f"

[[historical_test_results]]
test_type = "stable"
passed = true
package = "qiskit"
package_version = "0.22.3"
timestamp = 1678827878.841959
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937704855"

[[historical_test_results]]
test_type = "stable"
passed = true
package = "qiskit"
package_version = "0.22.4"
timestamp = 1678827878.841961
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994629269"

[[historical_test_results]]
test_type = "stable"
passed = true
package = "qiskit"
package_version = "0.23.0"
timestamp = 1678827878.841963
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052485085"

[[historical_test_results]]
test_type = "stable"
passed = true
package = "qiskit"
package_version = "0.23.1"
timestamp = 1678827878.841967
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231023417"

[[historical_test_results]]
test_type = "standard"
passed = true
package = "qiskit"
package_version = "0.22.0"
timestamp = 1678827878.84197
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414047258"

[[historical_test_results]]
test_type = "stable"
passed = true
package = "qiskit"
package_version = "0.23.2"
timestamp = 1678827878.841972
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414047359"

[[historical_test_results]]
test_type = "development"
passed = true
package = "qiskit"
package_version = "0.24.0"
timestamp = 1678827878.839921
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414047438"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"

