name = "bosonic-qiskit"
url = "https://github.com/C2QA/bosonic-qiskit"
description = "NQI C2QA project to simulate hybrid boson-qubit systems within Qiskit."
licence = "BSD 2-Clause Simplified or FreeBSD license"
labels = [ "Physics",]
created_at = 1678827878.841977
updated_at = 1678827878.841978
tier = "Community"
styles_results = []
coverages_results = []
skip_tests = false
stars = 39
group = "applications"
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "1.0.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624758109"
package_commit_hash = "fe3bffbc85a4fb57dc62ba04fa7f11bcefb5d75f"
qiskit_version = "1.0.0"
timestamp = 1698140505.700804

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit"
package_version = "0.44.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624758109"
qiskit_version = "0.44.2"
timestamp = 1698141364.594495

[[tests_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624758109"
qiskit_version = "0.44.2"
timestamp = 1698140061.279459

[[tests_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624758109"
qiskit_version = "0.39.0"
timestamp = 1698141361.771747

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368225482"
qiskit_version = "0.39.0"
timestamp = 1692699449.223752

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.39.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521953307"
qiskit_version = "0.39.2"
timestamp = 1692699449.223756

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937704942"
package_commit_hash = "af0b2220b75fd5cf3980576b1a31f9c4ceb9f99f"
qiskit_version = "0.40.0"
timestamp = 1692699449.22376

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.39.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937704855"
qiskit_version = "0.39.4"
timestamp = 1692699449.223763

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.39.5"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994629269"
qiskit_version = "0.39.5"
timestamp = 1692699449.223767

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052485085"
qiskit_version = "0.40.0"
timestamp = 1692699449.223771

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.41.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231023417"
qiskit_version = "0.41.0"
timestamp = 1692699449.223774

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.41.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414047359"
qiskit_version = "0.41.1"
timestamp = 1692699449.223778

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.43.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414047438"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"
qiskit_version = "0.43.0"
timestamp = 1692699449.223782

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6310543088"
qiskit_version = "0.44.1"
timestamp = 1695720270.168092

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6545037181"
package_commit_hash = "62467839e8d4e263465c42118414e6e5eca3c776"
qiskit_version = "0.45.0"
timestamp = 1697535054.910321

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "1.0.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624758109"
package_commit_hash = "fe3bffbc85a4fb57dc62ba04fa7f11bcefb5d75f"
qiskit_version = "1.0.0"
timestamp = 1698140505.700804

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624758109"
qiskit_version = "0.44.2"
timestamp = 1698140061.279459

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624758109"
qiskit_version = "0.39.0"
timestamp = 1698141361.771747

