name = "Bosonic Qiskit"
url = "https://github.com/C2QA/bosonic-qiskit"
description = "NQI C2QA project to simulate hybrid boson-qubit systems within Qiskit."
labels = [ "physics",]
created_at = 1678827878.841977
updated_at = 1678827878.841978
group = "Application"
uuid = "3d8fe04d-8ac0-4282-9eb6-cb458550945a"
badge = "https://qisk.it/e-3d8fe04d"

[github]
url = "https://github.com/C2QA/bosonic-qiskit"
owner = "C2QA"
repo = "bosonic-qiskit"
stars = 71
license = "BSD 2-Clause \"Simplified\" License"
description = "Extension of Qiskit to support hybrid boson-qubit simulations for the NQI C2QA effort."
estimated_contributors = 10
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2026-01-07T19:19:12Z
last_activity = 2026-01-29T00:58:04Z

[pypi.bosonic-qiskit]
package_name = "bosonic-qiskit"
version = "14.1.1"
url = "https://pypi.org/project/bosonic-qiskit/"
requires_qiskit = "==2.0.0"
compatible_with_qiskit_v1 = false
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2025-04-01T13:49:28Z
highest_supported_qiskit_version = "2.0.0"
last_month_downloads = 487
last_180_days_downloads = 1560
