name = "c3"
url = "https://github.com/q-optimize/c3"
description = "The C3 package is intended to close the loop between open-loop control optimization, control pulse calibration, and model-matching based on calibration data."
licence = "Apache 2.0"
contact_info = ""
alternatives = ""
labels = [ "plugin",]
created_at = 1678827878.240528
updated_at = 1678827878.240528
tier = "Community"
skip_tests = false
stars = 57
[[tests_results]]
test_type = "development"
passed = false
package = "qiskit-terra"
package_version = "0.24.0"
terra_version = "0.24.0"
timestamp = 1678827878.229887
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414043772"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"

[[tests_results]]
test_type = "last passing version"
passed = true
package = "qiskit-terra"
package_version = "0.22.2"
terra_version = "0.22.2"
timestamp = 1678827878.231853
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3469022488"

[[tests_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.23.2"
terra_version = "0.23.2"
timestamp = 1678827878.231856
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414043735"

[[tests_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.23.2"
terra_version = "0.23.2"
timestamp = 1678827878.231858
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414043694"

[[styles_results]]
style_type = "pylint"
passed = true

[[coverages_results]]
coverage_type = ""
passed = true

[[historical_test_results]]
test_type = "standard"
passed = true
package = "qiskit-terra"
package_version = "0.20.2"
terra_version = "0.20.2"
timestamp = 1678827878.240462

[[historical_test_results]]
test_type = "development"
passed = true
package = "qiskit-terra"
package_version = "0.21.0"
terra_version = "0.21.0"
timestamp = 1678827878.240467

[[historical_test_results]]
test_type = "stable"
passed = true
package = "qiskit-terra"
package_version = "0.20.2"
terra_version = "0.20.2"
timestamp = 1678827878.240469

[[historical_test_results]]
test_type = "standard"
passed = true
package = "qiskit-terra"
package_version = "0.21.0"
terra_version = "0.21.0"
timestamp = 1678827878.240472
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2617548233"

[[historical_test_results]]
test_type = "stable"
passed = true
package = "qiskit-terra"
package_version = "0.21.0"
terra_version = "0.21.0"
timestamp = 1678827878.240474
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2617548233"

[[historical_test_results]]
test_type = "stable"
passed = true
package = "qiskit-terra"
package_version = "0.21.1"
terra_version = "0.21.1"
timestamp = 1678827878.240477
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824120979"

[[historical_test_results]]
test_type = "standard"
passed = true
package = "qiskit-terra"
package_version = "0.21.1"
terra_version = "0.21.1"
timestamp = 1678827878.240479
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824120979"

[[historical_test_results]]
test_type = "development"
passed = false
package = "qiskit-terra"
package_version = "0.22.0"
terra_version = "0.22.0"
timestamp = 1678827878.240481
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3180918979"
package_commit_hash = "53e215c31cf3aea51a623dc22883ac92fe74d0b9"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.21.2"
terra_version = "0.21.2"
timestamp = 1678827878.240483
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225637724"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.21.2"
terra_version = "0.21.2"
timestamp = 1678827878.240486
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225637748"

[[historical_test_results]]
test_type = "stable"
passed = true
package = "qiskit-terra"
package_version = "0.22.0"
terra_version = "0.22.0"
timestamp = 1678827878.240488
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368223753"

[[historical_test_results]]
test_type = "standard"
passed = true
package = "qiskit-terra"
package_version = "0.22.0"
terra_version = "0.22.0"
timestamp = 1678827878.24049
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368223761"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.22.2"
terra_version = "0.22.2"
timestamp = 1678827878.240492
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521950511"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.22.2"
terra_version = "0.22.2"
timestamp = 1678827878.240495
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521950486"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.22.3"
terra_version = "0.22.3"
timestamp = 1678827878.240497
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937700830"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.22.3"
terra_version = "0.22.3"
timestamp = 1678827878.240499
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937700868"

[[historical_test_results]]
test_type = "development"
passed = false
package = "qiskit-terra"
package_version = "0.23.0"
terra_version = "0.23.0"
timestamp = 1678827878.240501
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937700942"
package_commit_hash = "af0b2220b75fd5cf3980576b1a31f9c4ceb9f99f"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.22.4"
terra_version = "0.22.4"
timestamp = 1678827878.240503
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994625453"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.22.4"
terra_version = "0.22.4"
timestamp = 1678827878.240506
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994625536"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.23.0"
terra_version = "0.23.0"
timestamp = 1678827878.240508
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052481181"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.23.0"
terra_version = "0.23.0"
timestamp = 1678827878.24051
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052481227"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.23.1"
terra_version = "0.23.1"
timestamp = 1678827878.240512
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231020187"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.23.1"
terra_version = "0.23.1"
timestamp = 1678827878.240516
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231020171"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.23.2"
terra_version = "0.23.2"
timestamp = 1678827878.240519
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414043735"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.23.2"
terra_version = "0.23.2"
timestamp = 1678827878.240521
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414043694"

[[historical_test_results]]
test_type = "development"
passed = false
package = "qiskit-terra"
package_version = "0.24.0"
terra_version = "0.24.0"
timestamp = 1678827878.229887
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414043772"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"

[configuration]
dependencies_files = [ "requirements.txt",]
extra_dependencies = [ "qiskit", "coverage", "pylint", "black",]
tests_command = [ "pytest -v -x -m \"not slow\" test/", "pytest -v -x -m \"slow\" test/",]
styles_check_command = [ "black --check c3/",]
coverages_check_command = [ "pytest -x -v --cov=c3 --cov-report=xml test/",]

[configuration.language]
name = "python"
versions = [ "3.7", "3.8", "3.9",]
