name = "c3"
url = "https://github.com/q-optimize/c3"
description = "The C3 package is intended to close the loop between open-loop control optimization, control pulse calibration, and model-matching based on calibration data."
licence = "Apache 2.0"
contact_info = ""
alternatives = ""
labels = [ "Circuit simulator",]
created_at = 1678827878.240528
updated_at = 1678827878.240528
tier = "Community"
skip_tests = false
stars = 58
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936779030"
package_commit_hash = "0b51250e219ca303654fc28a318c21366584ccd3"
qiskit_version = "0.45.0"
timestamp = 1692696024.513507

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit"
package_version = "0.39.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3469022488"
qiskit_version = "0.39.2"
timestamp = 1692696024.685026

[[tests_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936779030"
qiskit_version = "0.44.1"
timestamp = 1692696024.685031

[[tests_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936779030"
qiskit_version = "0.44.1"
timestamp = 1692696024.685034

[[styles_results]]
passed = true
style_type = "pylint"

[[coverages_results]]
passed = true
coverage_type = ""

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.36.2"
qiskit_version = "0.36.2"
timestamp = 1692696024.68505

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.37.0"
qiskit_version = "0.37.0"
timestamp = 1692696024.685054

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.36.2"
qiskit_version = "0.36.2"
timestamp = 1692696024.685058

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.37.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2617548233"
qiskit_version = "0.37.0"
timestamp = 1692696024.685061

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.37.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2617548233"
qiskit_version = "0.37.0"
timestamp = 1692696024.685065

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.37.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824120979"
qiskit_version = "0.37.1"
timestamp = 1692696024.685069

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.37.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824120979"
qiskit_version = "0.37.1"
timestamp = 1692696024.685073

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3180918979"
package_commit_hash = "53e215c31cf3aea51a623dc22883ac92fe74d0b9"
qiskit_version = "0.39.0"
timestamp = 1692696024.685077

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.38.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225637724"
qiskit_version = "0.38.0"
timestamp = 1692696024.685081

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.38.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225637748"
qiskit_version = "0.38.0"
timestamp = 1692696024.685085

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368223753"
qiskit_version = "0.39.0"
timestamp = 1692696024.685088

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368223761"
qiskit_version = "0.39.0"
timestamp = 1692696024.685092

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.39.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521950511"
qiskit_version = "0.39.2"
timestamp = 1692696024.685095

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.39.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521950486"
qiskit_version = "0.39.2"
timestamp = 1692696024.685099

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.39.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937700830"
qiskit_version = "0.39.4"
timestamp = 1692696024.685103

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.39.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937700868"
qiskit_version = "0.39.4"
timestamp = 1692696024.685107

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937700942"
package_commit_hash = "af0b2220b75fd5cf3980576b1a31f9c4ceb9f99f"
qiskit_version = "0.40.0"
timestamp = 1692696024.685111

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.39.5"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994625453"
qiskit_version = "0.39.5"
timestamp = 1692696024.685115

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.39.5"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994625536"
qiskit_version = "0.39.5"
timestamp = 1692696024.685119

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052481181"
qiskit_version = "0.40.0"
timestamp = 1692696024.685122

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052481227"
qiskit_version = "0.40.0"
timestamp = 1692696024.685126

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.41.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231020187"
qiskit_version = "0.41.0"
timestamp = 1692696024.68513

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.41.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231020171"
qiskit_version = "0.41.0"
timestamp = 1692696024.685134

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.41.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414043735"
qiskit_version = "0.41.1"
timestamp = 1692696024.685138

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.41.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414043694"
qiskit_version = "0.41.1"
timestamp = 1692696024.685141

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.43.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414043772"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"
qiskit_version = "0.43.0"
timestamp = 1692696024.685145

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936779030"
qiskit_version = "0.44.1"
timestamp = 1692696024.685152

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936779030"
qiskit_version = "0.44.1"
timestamp = 1692696024.685156

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936779030"
package_commit_hash = "0b51250e219ca303654fc28a318c21366584ccd3"
qiskit_version = "0.45.0"
timestamp = 1692696024.513507

[configuration]
dependencies_files = [ "requirements.txt",]
extra_dependencies = [ "qiskit", "coverage", "pylint", "black",]
tests_command = [ "pytest -v -x -m \"not slow\" test/", "pytest -v -x -m \"slow\" test/",]
styles_check_command = [ "black --check c3/",]
coverages_check_command = [ "pytest -x -v --cov=c3 --cov-report=xml test/",]

[configuration.language]
name = "python"
versions = [ "3.7", "3.8", "3.9",]
