name = "CALA-n Quantum Library"
url = "https://github.com/albayaty/cala_quantum_library"
description = "A set of cost-effective n-bit gates based on Clifford+T gates, quantum layouts, and n neighboring physical qubits (2 <= n <= 5)."
licence = "Apache License 2.0"
contact_info = "albayaty@pdx.edu"
affiliations = "Department of Electrical and Computer Engineering at Portland State University"
labels = [ "circuit manipulation", "research",]
group = "Application"
reference_paper = "https://doi.org/10.48550/arXiv.2408.01025"
uuid = "8868c7af-adce-48ee-9ca9-d066fb569cf4"
badge = "https://qisk.it/e-8868c7af"

[github]
url = "https://github.com/albayaty/cala_quantum_library"
owner = "albayaty"
repo = "cala_quantum_library"
stars = 0
license = "Apache License 2.0"
description = "CALA-n Quantum Library"
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2024-10-20T20:38:05Z
