name = "caml_qiskit"
url = "https://github.com/dakk/caml_qiskit"
description = "OCaml wrapper for Qiskit quantum computing toolkit"
licence = "MIT license"
contact_info = "gessadavide@gmail.com"
labels = [ "Converter",]
ibm_maintained = false
stars = 8
group = "other"
documentation = "https://dakk.github.io/caml_qiskit/"
uuid = "64fd2228-855b-4f30-9a1d-b64904ea80b4"
