name = "Circuit Knitting Toolbox"
url = "https://github.com/Qiskit-Extensions/circuit-knitting-toolbox"
description = "Cut large circuits into smaller, hardware-executable circuits, then use their results to reconstruct the original outcome."
licence = "Apache License 2.0"
contact_info = "blake.johnson@ibm.com"
labels = [ "Algorithms", "Circuit building tool",]
ibm_maintained = false
created_at = 1670427445.884067
updated_at = 1670427445.884068
stars = 67
group = "other"
documentation = "https://qiskit-extensions.github.io/circuit-knitting-toolbox/"
