name = "circuit-knitting-toolbox"
url = "https://github.com/Qiskit-Extensions/circuit-knitting-toolbox"
description = "Circuit Knitting is the process of decomposing a quantum circuit into smaller circuits, executing those smaller circuits on a quantum processor(s), and then knitting their results into a reconstruction of the original circuit's outcome. Circuit knitting includes techniques such as entanglement forging, circuit cutting, and classical embedding. The Circuit Knitting Toolbox (CKT) is a collection of such tools."
licence = "Apache License 2.0"
contact_info = "blake.johnson@ibm.com"
alternatives = "_No response_"
labels = [ "Algorithms", "Circuit",]
created_at = 1670427445.884067
updated_at = 1670427445.884068
tier = "Extensions"
styles_results = []
coverages_results = []
skip_tests = true
historical_test_results = []
stars = 46
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3628096614"
package_commit_hash = "0df0d29fc44fb571e38530d20743a6e70e230865"
qiskit_version = "unknown"
timestamp = 1670427445.882592

[[tests_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3628096615"
qiskit_version = "unknown"
timestamp = 1670427445.884051

[[tests_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3628096587"
qiskit_version = "unknown"
timestamp = 1670427445.884055

