name = "Conditional Measurement Toolbox"
url = "https://github.com/alexg-jpg/conditional-measurements"
description = "A software library (in progress) for implementing conditional projective measurement operations in Qiskit."
contact_info = "alexander.greenwood@mail.utoronto.ca"
labels = []
group = "other"
reference_paper = "https://arxiv.org/abs/2508.09110"
uuid = "dc917437-3b51-4ea8-9bdb-e2eaa2114cd5"
badge = "[![Qiskit Ecosystem](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fqiskit.github.io%2Fecosystem%2Fb%2Fdc917437)](https://qisk.it/e)"

[github]
url = "https://github.com/alexg-jpg/conditional-measurements"
owner = "alexg-jpg"
repo = "conditional-measurements"
stars = 0
license = "MIT License"
description = "A software library for implementing conditional projective measurement operations in Qiskit."
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2025-10-02T19:40:07Z
