name = "Conditional Measurement Toolbox"
url = "https://github.com/alexg-jpg/conditional-measurements"
description = "A software library (in progress) for implementing conditional projective measurement operations in Qiskit."
contact_info = "alexander.greenwood@mail.utoronto.ca"
labels = [ ]
ibm_maintained = false
group = "other"
reference_paper = "https://arxiv.org/abs/2508.09110"
uuid = "dc917437-3b51-4ea8-9bdb-e2eaa2114cd5"
badge = "[![Qiskit Ecosystem](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fqiskit.github.io%2Fecosystem%2Fb%2Fdc917437)](https://qisk.it/e)"

[github]
owner = "alexg-jpg"
repo = "conditional-measurements"
