name = "dense-ev"
url = "https://github.com/atlytle/dense-ev"
description = "Expectation value measurements in Qiskit using optimal dense grouping, an improvement of (3/2)^m over qubit-wise commuting groups."
licence = "Apache License 2.0"
contact_info = "atlytle@gmail.com"
affiliations = "University of Illinois at Urbana-Champaign"
labels = [ "Paper implementation",]
ibm_maintained = false
stars = 9
group = "other"
reference_paper = "https://arxiv.org/abs/2305.11847"
