name = "dsm-swap"
url = "https://github.com/qiskit-community/dsm-swap"
description = "A doubly stochastic matrices-based approach to optimal qubit routing."
licence = "Apache License 2.0"
labels = [ "circuit manipulation", "research",]
created_at = 1678827878.56605
updated_at = 1678827878.566051
group = "Transpiler plugin"
uuid = "beaaab32-58d4-496f-8428-e6d88fa1e989"
badge = "https://qisk.it/e-beaaab32"

[github]
url = "https://github.com/qiskit-community/dsm-swap"
owner = "qiskit-community"
repo = "dsm-swap"
stars = 8
license = "Apache License 2.0"
description = "A doubly stochastic matrices-based approach to optimal qubit routing"
estimated_contributors = 3
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2024-05-29T14:41:07Z
last_activity = 2025-11-15T05:58:18Z
