name = "dsm-swap"
url = "https://github.com/qiskit-community/dsm-swap"
description = "A doubly stochastic matrices-based approach to optimal qubit routing"
licence = "Apache License 2.0"
contact_info = "_No response_"
alternatives = "_No response_"
labels = [ "Paper implementation", "Circuit",]
created_at = 1678827878.56605
updated_at = 1678827878.566051
tier = "Community"
styles_results = []
coverages_results = []
skip_tests = false
stars = 7
group = "transpiler_plugin"
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "1.0.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624757223"
package_commit_hash = "fe3bffbc85a4fb57dc62ba04fa7f11bcefb5d75f"
qiskit_version = "1.0.0"
timestamp = 1698139484.144841

[[tests_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.44.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624757223"
qiskit_version = "0.44.2"
timestamp = 1698138907.008306

[[tests_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = ""
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624757223"
qiskit_version = ""
timestamp = 1698139637.364254

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368225626"
qiskit_version = "0.39.0"
timestamp = 1692612759.255206

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368225632"
qiskit_version = "0.39.0"
timestamp = 1692612759.25521

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.39.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521953428"
qiskit_version = "0.39.2"
timestamp = 1692612759.255214

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.39.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521953451"
qiskit_version = "0.39.2"
timestamp = 1692612759.255218

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.39.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937705002"
qiskit_version = "0.39.4"
timestamp = 1692612759.255222

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.39.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937705033"
qiskit_version = "0.39.4"
timestamp = 1692612759.255226

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937705078"
package_commit_hash = "af0b2220b75fd5cf3980576b1a31f9c4ceb9f99f"
qiskit_version = "0.40.0"
timestamp = 1692612759.25523

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.39.5"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994629546"
qiskit_version = "0.39.5"
timestamp = 1692612759.255234

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052485251"
qiskit_version = "0.40.0"
timestamp = 1692612759.255238

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052485304"
qiskit_version = "0.40.0"
timestamp = 1692612759.255242

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.41.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231023555"
qiskit_version = "0.41.0"
timestamp = 1692612759.255246

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.41.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231023565"
qiskit_version = "0.41.0"
timestamp = 1692612759.25525

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.43.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414047715"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"
qiskit_version = "0.43.0"
timestamp = 1692612759.255254

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.41.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414047517"
qiskit_version = "0.41.1"
timestamp = 1692612759.255258

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.41.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414047648"
qiskit_version = "0.41.1"
timestamp = 1692612759.255262

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6310545674"
qiskit_version = "0.44.1"
timestamp = 1695719676.008375

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6545041435"
package_commit_hash = "62467839e8d4e263465c42118414e6e5eca3c776"
qiskit_version = "0.45.0"
timestamp = 1697535071.427365

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "1.0.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624757223"
package_commit_hash = "fe3bffbc85a4fb57dc62ba04fa7f11bcefb5d75f"
qiskit_version = "1.0.0"
timestamp = 1698139484.144841

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = ""
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624757223"
qiskit_version = ""
timestamp = 1698139637.364254

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.44.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624757223"
qiskit_version = "0.44.2"
timestamp = 1698138907.008306

