name = "dsm-swap"
url = "https://github.com/qiskit-community/dsm-swap"
description = "A doubly stochastic matrices-based approach to optimal qubit routing"
licence = "Apache License 2.0"
contact_info = "_No response_"
alternatives = "_No response_"
labels = [ "plugin", "paper implementation", "circuit",]
created_at = 1678827878.56605
updated_at = 1678827878.566051
styles_results = []
coverages_results = []
tier = "Community"
skip_tests = false
stars = 7
[[tests_results]]
test_type = "development"
passed = false
package = "qiskit"
package_version = "0.24.0"
timestamp = 1678827878.566001
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414047715"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"

[[tests_results]]
test_type = "stable"
passed = false
package = "qiskit"
package_version = "0.23.2"
timestamp = 1678827878.56399
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414047648"

[[tests_results]]
test_type = "standard"
passed = false
package = "qiskit"
package_version = "0.23.2"
timestamp = 1678827878.566009
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414047517"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit"
package_version = "0.22.0"
timestamp = 1678827878.566015
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368225626"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit"
package_version = "0.22.0"
timestamp = 1678827878.566017
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368225632"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit"
package_version = "0.22.2"
timestamp = 1678827878.56602
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521953428"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit"
package_version = "0.22.2"
timestamp = 1678827878.566022
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521953451"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit"
package_version = "0.22.3"
timestamp = 1678827878.566024
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937705002"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit"
package_version = "0.22.3"
timestamp = 1678827878.566027
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937705033"

[[historical_test_results]]
test_type = "development"
passed = false
package = "qiskit"
package_version = "0.23.0"
timestamp = 1678827878.566029
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937705078"
package_commit_hash = "af0b2220b75fd5cf3980576b1a31f9c4ceb9f99f"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit"
package_version = "0.22.4"
timestamp = 1678827878.566031
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994629546"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit"
package_version = "0.23.0"
timestamp = 1678827878.566033
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052485251"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit"
package_version = "0.23.0"
timestamp = 1678827878.566036
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052485304"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit"
package_version = "0.23.1"
timestamp = 1678827878.566038
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231023555"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit"
package_version = "0.23.1"
timestamp = 1678827878.56604
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231023565"

[[historical_test_results]]
test_type = "development"
passed = false
package = "qiskit"
package_version = "0.24.0"
timestamp = 1678827878.566042
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414047715"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit"
package_version = "0.23.2"
timestamp = 1678827878.566044
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414047517"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit"
package_version = "0.23.2"
timestamp = 1678827878.56399
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414047648"

