name = "dsm-swap"
url = "https://github.com/qiskit-community/dsm-swap"
description = "A doubly stochastic matrices-based approach to optimal qubit routing"
licence = "Apache License 2.0"
contact_info = "_No response_"
alternatives = "_No response_"
labels = [ "plugin", "paper implementation", "circuit",]
created_at = 1678827878.56605
updated_at = 1678827878.566051
styles_results = []
coverages_results = []
tier = "Community"
skip_tests = false
stars = 7
[[tests_results]]
test_type = "development"
passed = false
package = "qiskit-terra"
package_version = "0.43.0"
qiskit_version = "0.43.0"
timestamp = 1678827878.566001
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414047715"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"

[[tests_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.41.1"
qiskit_version = "0.41.1"
timestamp = 1678827878.56399
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414047648"

[[tests_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.41.1"
qiskit_version = "0.41.1"
timestamp = 1678827878.566009
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414047517"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.39.0"
qiskit_version = "0.39.0"
timestamp = 1678827878.566015
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368225626"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.39.0"
qiskit_version = "0.39.0"
timestamp = 1678827878.566017
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368225632"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.39.2"
qiskit_version = "0.39.2"
timestamp = 1678827878.56602
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521953428"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.39.2"
qiskit_version = "0.39.2"
timestamp = 1678827878.566022
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521953451"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.39.4"
qiskit_version = "0.39.4"
timestamp = 1678827878.566024
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937705002"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.39.4"
qiskit_version = "0.39.4"
timestamp = 1678827878.566027
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937705033"

[[historical_test_results]]
test_type = "development"
passed = false
package = "qiskit-terra"
package_version = "0.40.0"
qiskit_version = "0.40.0"
timestamp = 1678827878.566029
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937705078"
package_commit_hash = "af0.39.0b75fd5cf3980576b1a31f9c4ceb9f99f"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.39.5"
qiskit_version = "0.39.5"
timestamp = 1678827878.566031
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994629546"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.40.0"
qiskit_version = "0.40.0"
timestamp = 1678827878.566033
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052485251"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.40.0"
qiskit_version = "0.40.0"
timestamp = 1678827878.566036
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052485304"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.41.0"
qiskit_version = "0.41.0"
timestamp = 1678827878.566038
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231023555"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.41.0"
qiskit_version = "0.41.0"
timestamp = 1678827878.56604
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231023565"

[[historical_test_results]]
test_type = "development"
passed = false
package = "qiskit-terra"
package_version = "0.43.0"
qiskit_version = "0.43.0"
timestamp = 1678827878.566042
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414047715"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.41.1"
qiskit_version = "0.41.1"
timestamp = 1678827878.566044
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414047517"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.41.1"
qiskit_version = "0.41.1"
timestamp = 1678827878.56399
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414047648"

