name = "dynacir"
url = "https://github.com/derek-wang-ibm/dynacir"
description = "Dynacir is a transpilation plugin for Qiskit that optimizes dynamic quantum circuits."
licence = "Apache License 2.0"
affiliations = "IBM Quantum"
labels = [ "circuit manipulation",]
group = "Transpiler plugin"
uuid = "ee3eb036-bc4d-4342-a36d-af262eed95e4"
badge = "https://qisk.it/e-ee3eb036"

[github]
url = "https://github.com/derek-wang-ibm/dynacir"
owner = "derek-wang-ibm"
repo = "dynacir"
stars = 0
license = "Apache License 2.0"
description = "Qiskti transpiler plugin for dynamic circuits."
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2024-03-21T16:41:46Z
last_activity = 2025-11-19T17:28:13Z

[pypi.dynacir]
package_name = "dynacir"
version = "0.1.4"
url = "https://pypi.org/project/dynacir/"
last_month_downloads = 31
last_180_days_downloads = 169
