name = "Electronic Structure Orbital Optimization"
url = "https://github.com/JoelHBierman/electronic-structure-orbital-optimization"
description = "Apply orbital optimization to quantum algorithms that solve electronic structure Hamiltonians. This collection of methods optimize the underlying basis set through orbital rotations, finding more accurate energies with fewer qubits."
licence = "Apache License 2.0"
contact_info = "joel.bierman@duke.edu"
alternatives = "_No response_"
affiliations = "Duke University"
labels = [ "Algorithms", "Chemistry",]
tier = "Community"
tests_results = []
styles_results = []
coverages_results = []
skip_tests = false
historical_test_results = []
group = "applications"
