name = "fast-pauli"
url = "https://github.com/qognitive/fast-pauli"
description = "Conduct efficient multiplication of tensor products of Pauli matrices against a batch of vectors and other mathematical operations."
licence = "BSD 2-Clause \"Simplified\" or \"FreeBSD\" license"
contact_info = "dev@qognitive.io"
affiliations = "Qognitive Inc"
labels = []
website = "https://qognitive.io"
group = "Application"
reference_paper = "https://arxiv.org/abs/2301.00560"
documentation = "https://qognitive-fast-pauli.readthedocs-hosted.com/en/latest/"
uuid = "b4d78374-40eb-4118-bb22-45e97b2dc0c5"
badge = "https://qisk.it/e-b4d78374"

[github]
url = "https://github.com/qognitive/fast-pauli"
owner = "qognitive"
repo = "fast-pauli"
stars = 15
homepage = "https://qognitive-fast-pauli.readthedocs-hosted.com/en/latest/"
license = "BSD 2-Clause \"Simplified\" License"
description = "Python/C++ library for optimized operations on Pauli matrices and Pauli strings"
estimated_contributors = 4
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2025-04-09T21:51:22Z
last_activity = 2025-10-31T17:43:20Z

[pypi.fast-pauli]
package_name = "fast-pauli"
version = "0.0.35"
url = "https://pypi.org/project/fast-pauli/"
requires_qiskit = ">=0"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2025-10-22T14:47:06Z
highest_supported_qiskit_version = "2.2.2"
last_month_downloads = 789
last_180_days_downloads = 19867
