name = "ffsim"
url = "https://github.com/qiskit-community/ffsim"
description = "ffsim is a software library for simulating fermionic quantum circuits that conserve particle number and the Z component of spin."
licence = "Apache License 2.0"
affiliations = "IBM"
labels = [ "Chemistry", "Circuit simulator", "Application package",]
ibm_maintained = false
website = "https://qiskit-community.github.io/ffsim/"
stars = 26
group = "applications"
uuid = "8bbab14b-6cbb-4e09-8040-d5afd359deec"
