name = "ffsim"
url = "https://github.com/qiskit-community/ffsim"
description = "ffsim is a software library for simulating fermionic quantum circuits that conserve particle number and the Z component of spin."
licence = "Apache License 2.0"
affiliations = "IBM"
labels = [ "chemistry",]
website = "https://qiskit-community.github.io/ffsim/"
group = "Circuit simulator"
uuid = "8bbab14b-6cbb-4e09-8040-d5afd359deec"
badge = "https://qisk.it/e-8bbab14b"

[github]
url = "https://github.com/qiskit-community/ffsim"
owner = "qiskit-community"
repo = "ffsim"
stars = 64
homepage = "https://qiskit-community.github.io/ffsim/"
license = "Apache License 2.0"
description = "Faster simulations of fermionic quantum circuits."
estimated_contributors = 11
total_dependent_repositories = 11
total_dependent_packages = 3
last_commit = 2025-12-31T20:17:12Z
last_activity = 2026-01-01T01:03:25Z

[pypi.ffsim]
package_name = "ffsim"
version = "0.0.61"
url = "https://pypi.org/project/ffsim/"
requires_qiskit = ">=1.3"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2025-10-22T14:47:06Z
highest_supported_qiskit_version = "2.2.2"
last_month_downloads = 8727
last_180_days_downloads = 46708
