name = "GALA-n Quantum Library"
url = "https://github.com/albayaty/gala_quantum_library"
description = "A set of cost-effective n-bit gates based on the layouts and neighboring qubits for IBM quantum computers (n >= 3 qubits)."
licence = "Apache License 2.0"
contact_info = "albayaty@pdx.edu"
affiliations = "Department of Electrical and Computer Engineering at Portland State University"
labels = [ "circuit building", "research",]
group = "Application"
reference_paper = "https://doi.org/10.48550/arXiv.2311.06760"
uuid = "36e10568-9c53-4b9b-b658-8907e5e2edb9"
badge = "https://qisk.it/e-36e10568"

[github]
url = "https://github.com/albayaty/gala_quantum_library"
owner = "albayaty"
repo = "gala_quantum_library"
stars = 1
license = "Apache License 2.0"
description = "GALA-n Quantum Library"
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2024-10-20T20:35:33Z
