name = "Grover controlled-diffuser (CUs)"
url = "https://github.com/albayaty/grover_controlled_diffuser"
description = "The CUs is a new quantum diffusion operator for Groverâ€™s algorithm to search for all solutions for Boolean oracles."
licence = "Apache License 2.0"
contact_info = "albayaty@pdx.edu"
affiliations = "Department of Electrical and Computer Engineering at Portland State University"
labels = [ "circuit manipulation", "research",]
group = "Application"
reference_paper = "https://doi.org/10.21203/rs.3.rs-2997276/v1"
uuid = "40b3b309-0dfa-482a-89a6-cbaffd18b7ba"
badge = "https://qisk.it/e-40b3b309"

[github]
url = "https://github.com/albayaty/grover_controlled_diffuser"
owner = "albayaty"
repo = "grover_controlled_diffuser"
stars = 0
license = "Apache License 2.0"
description = "Grover controlled-diffuser (CUs) for Grover's algorithm"
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2024-10-20T20:34:29Z
