name = "Hamiltonian simulation template"
url = "https://github.com/qiskit-community/qiskit-function-templates/tree/main/physics/hamiltonian_simulation"
description = "A Qiskit Function template for Hamiltonian simulation with AQC-Tensor Qiskit addon"
licence = "Apache License 2.0"
labels = [ "Applications", "Physics",]
ibm_maintained = true
stars = 18
group = "applications"
reference_paper = "https://dl.acm.org/doi/10.1145/3731251"
uuid = "569f773e-34d9-4573-bbaf-1ca0268e7004"
badge = "[![Qiskit Ecosystem](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fqiskit.github.io%2Fecosystem%2Fb%2F569f773e)](https://qisk.it/e)"

[github]
url = "https://github.com/qiskit-community/qiskit-function-templates"
owner = "qiskit-community"
repo = "qiskit-function-templates"
tree = "main/physics/hamiltonian_simulation"
stars = 18
last_commit = 2025-11-04T10:29:43Z
