name = "Hamiltonian simulation template"
url = "https://github.com/qiskit-community/qiskit-function-templates/tree/main/physics/hamiltonian_simulation"
description = "A Qiskit Function template for Hamiltonian simulation with AQC-Tensor Qiskit addon"
licence = "Apache License 2.0"
labels = [ "physics",]
ibm_maintained = true
group = "Application"
reference_paper = "https://dl.acm.org/doi/10.1145/3731251"
uuid = "569f773e-34d9-4573-bbaf-1ca0268e7004"
badge = "https://qisk.it/e-569f773e"

[github]
url = "https://github.com/qiskit-community/qiskit-function-templates"
owner = "qiskit-community"
repo = "qiskit-function-templates"
tree = "main/physics/hamiltonian_simulation"
stars = 20
license = "Apache License 2.0"
estimated_contributors = 13
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2025-11-19T09:14:23Z
last_activity = 2026-02-02T11:55:22Z
