name = "HLQuantum"
url = "https://github.com/AlinDanielFerenczi/HLQuantum"
description = "A human oriented high-level Python package designed to simplify working with quantum algorithms and developing complex systems."
labels = [ "circuit manipulation, circuit building, research",]
group = "High-level synthesis plugin"
packages = [ "https://pypi.org/manage/project/hlquantum",]
uuid = "50bd99f2-dbd5-4759-b19d-6f5ecdf9e0da"

[github]
url = "https://github.com/AlinDanielFerenczi/HLQuantum"
owner = "AlinDanielFerenczi"
repo = "HLQuantum"
stars = 7
license = "Apache License 2.0"
description = "A high-level Python package designed to simplify working with quantum algorithms and implement it with real world use cases."
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2026-02-25T02:30:05Z
last_activity = 2026-02-26T14:24:55Z
