name = "kaleidoscope"
url = "https://github.com/QuSTaR/kaleidoscope"
description = "Kaleidoscope"
licence = "Apache 2.0"
contact_info = ""
alternatives = ""
labels = [ "Visualization",]
created_at = 1678827878.7097
updated_at = 1678827878.709701
tier = "Community"
skip_tests = false
stars = 21
[[tests_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6467186213"
package_commit_hash = "cecb7889372342e3c2ca713d5c767ad793688842"
qiskit_version = "0.45.0"
timestamp = 1696930140.78656

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit"
package_version = "0.44.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6467186213"
qiskit_version = "0.44.2"
timestamp = 1696930223.158664

[[tests_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6467186213"
qiskit_version = "0.44.2"
timestamp = 1696929738.006416

[[tests_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = ""
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6467186213"
qiskit_version = ""
timestamp = 1696930222.06364

[[styles_results]]
passed = false
style_type = "pylint"

[[coverages_results]]
passed = false
coverage_type = ""

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.36.2"
qiskit_version = "0.36.2"
timestamp = 1692696374.581313

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.36.2"
qiskit_version = "0.36.2"
timestamp = 1692696374.581316

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.37.0"
qiskit_version = "0.37.0"
timestamp = 1692696374.581319

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.37.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2617548324"
qiskit_version = "0.37.0"
timestamp = 1692696374.581321

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.37.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2617548324"
qiskit_version = "0.37.0"
timestamp = 1692696374.581325

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.37.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824121157"
qiskit_version = "0.37.1"
timestamp = 1692696374.581328

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.37.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824121157"
qiskit_version = "0.37.1"
timestamp = 1692696374.581331

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3180919383"
package_commit_hash = "53e215c31cf3aea51a623dc22883ac92fe74d0b9"
qiskit_version = "0.39.0"
timestamp = 1692696374.581334

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.38.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225637966"
qiskit_version = "0.38.0"
timestamp = 1692696374.581337

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.38.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225638009"
qiskit_version = "0.38.0"
timestamp = 1692696374.58134

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368223971"
qiskit_version = "0.39.0"
timestamp = 1692696374.581343

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368223985"
qiskit_version = "0.39.0"
timestamp = 1692696374.581346

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.39.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521951084"
qiskit_version = "0.39.2"
timestamp = 1692696374.581349

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.39.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521951050"
qiskit_version = "0.39.2"
timestamp = 1692696374.581352

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.39.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937701441"
qiskit_version = "0.39.4"
timestamp = 1692696374.581355

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937701574"
package_commit_hash = "af0b2220b75fd5cf3980576b1a31f9c4ceb9f99f"
qiskit_version = "0.40.0"
timestamp = 1692696374.581358

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.39.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937701523"
qiskit_version = "0.39.4"
timestamp = 1692696374.581361

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.39.5"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994626207"
qiskit_version = "0.39.5"
timestamp = 1692696374.581365

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.39.5"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994626228"
qiskit_version = "0.39.5"
timestamp = 1692696374.581368

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052481624"
qiskit_version = "0.40.0"
timestamp = 1692696374.58137

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052481674"
qiskit_version = "0.40.0"
timestamp = 1692696374.581373

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.41.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231020677"
qiskit_version = "0.41.0"
timestamp = 1692696374.581377

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.41.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231020708"
qiskit_version = "0.41.0"
timestamp = 1692696374.581381

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.41.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414044343"
qiskit_version = "0.41.1"
timestamp = 1692696374.581384

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.41.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414044250"
qiskit_version = "0.41.1"
timestamp = 1692696374.581387

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.43.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414044381"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"
qiskit_version = "0.43.0"
timestamp = 1692696374.58139

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6310547585"
qiskit_version = "0.44.1"
timestamp = 1695720203.690312

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6467186213"
qiskit_version = "0.44.2"
timestamp = 1696929738.006416

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = ""
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6467186213"
qiskit_version = ""
timestamp = 1696930222.06364

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6467186213"
package_commit_hash = "cecb7889372342e3c2ca713d5c767ad793688842"
qiskit_version = "0.45.0"
timestamp = 1696930140.78656

[configuration]
dependencies_files = [ "requirements.txt", "requirements-dev.txt",]
extra_dependencies = [ "coverage", "pylint",]
debian_dependencies = []
tests_command = [ "pytest -p no:warnings --pyargs kaleidoscope/test/no_qiskit",]
styles_check_command = [ "pylint -rn kaleidoscope",]
coverages_check_command = [ "coverage3 -m pytest -p no:warnings --pyargs kaleidoscope/test/no_qiskit", "coverage3 report --fail-under=80",]

[configuration.language]
name = "python"
versions = [ "3.6",]
