name = "kaleidoscope"
url = "https://github.com/QuSTaR/kaleidoscope"
description = "Kaleidoscope"
licence = "Apache 2.0"
contact_info = ""
alternatives = ""
labels = [ "plugin",]
created_at = 1678827878.7097
updated_at = 1678827878.709701
tier = "Community"
skip_tests = false
stars = 20
[[tests_results]]
test_type = "development"
passed = true
package = "qiskit-terra"
package_version = "0.24.0"
terra_version = "0.24.0"
timestamp = 1678827878.698999
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414044381"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"

[[tests_results]]
test_type = "last passing version"
passed = true
package = "qiskit-terra"
package_version = "0.22.3"
terra_version = "0.22.3"
timestamp = 1678827878.700973
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3683924960"

[[tests_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.23.2"
terra_version = "0.23.2"
timestamp = 1678827878.700976
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414044343"

[[tests_results]]
test_type = "standard"
passed = true
package = "qiskit-terra"
package_version = "0.23.2"
terra_version = "0.23.2"
timestamp = 1678827878.700979
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414044250"

[[styles_results]]
style_type = "pylint"
passed = false

[[coverages_results]]
coverage_type = ""
passed = false

[[historical_test_results]]
test_type = "standard"
passed = true
package = "qiskit-terra"
package_version = "0.20.2"
terra_version = "0.20.2"
timestamp = 1678827878.709635

[[historical_test_results]]
test_type = "stable"
passed = true
package = "qiskit-terra"
package_version = "0.20.2"
terra_version = "0.20.2"
timestamp = 1678827878.709641

[[historical_test_results]]
test_type = "development"
passed = true
package = "qiskit-terra"
package_version = "0.21.0"
terra_version = "0.21.0"
timestamp = 1678827878.709643

[[historical_test_results]]
test_type = "standard"
passed = true
package = "qiskit-terra"
package_version = "0.21.0"
terra_version = "0.21.0"
timestamp = 1678827878.709645
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2617548324"

[[historical_test_results]]
test_type = "stable"
passed = true
package = "qiskit-terra"
package_version = "0.21.0"
terra_version = "0.21.0"
timestamp = 1678827878.709647
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2617548324"

[[historical_test_results]]
test_type = "standard"
passed = true
package = "qiskit-terra"
package_version = "0.21.1"
terra_version = "0.21.1"
timestamp = 1678827878.70965
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824121157"

[[historical_test_results]]
test_type = "stable"
passed = true
package = "qiskit-terra"
package_version = "0.21.1"
terra_version = "0.21.1"
timestamp = 1678827878.709652
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824121157"

[[historical_test_results]]
test_type = "development"
passed = true
package = "qiskit-terra"
package_version = "0.22.0"
terra_version = "0.22.0"
timestamp = 1678827878.709654
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3180919383"
package_commit_hash = "53e215c31cf3aea51a623dc22883ac92fe74d0b9"

[[historical_test_results]]
test_type = "standard"
passed = true
package = "qiskit-terra"
package_version = "0.21.2"
terra_version = "0.21.2"
timestamp = 1678827878.709656
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225637966"

[[historical_test_results]]
test_type = "stable"
passed = true
package = "qiskit-terra"
package_version = "0.21.2"
terra_version = "0.21.2"
timestamp = 1678827878.709659
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225638009"

[[historical_test_results]]
test_type = "standard"
passed = true
package = "qiskit-terra"
package_version = "0.22.0"
terra_version = "0.22.0"
timestamp = 1678827878.709661
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368223971"

[[historical_test_results]]
test_type = "stable"
passed = true
package = "qiskit-terra"
package_version = "0.22.0"
terra_version = "0.22.0"
timestamp = 1678827878.709663
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368223985"

[[historical_test_results]]
test_type = "stable"
passed = true
package = "qiskit-terra"
package_version = "0.22.2"
terra_version = "0.22.2"
timestamp = 1678827878.709665
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521951084"

[[historical_test_results]]
test_type = "standard"
passed = true
package = "qiskit-terra"
package_version = "0.22.2"
terra_version = "0.22.2"
timestamp = 1678827878.709668
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521951050"

[[historical_test_results]]
test_type = "standard"
passed = true
package = "qiskit-terra"
package_version = "0.22.3"
terra_version = "0.22.3"
timestamp = 1678827878.70967
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937701441"

[[historical_test_results]]
test_type = "development"
passed = true
package = "qiskit-terra"
package_version = "0.23.0"
terra_version = "0.23.0"
timestamp = 1678827878.709672
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937701574"
package_commit_hash = "af0b2220b75fd5cf3980576b1a31f9c4ceb9f99f"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.22.3"
terra_version = "0.22.3"
timestamp = 1678827878.709674
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937701523"

[[historical_test_results]]
test_type = "standard"
passed = true
package = "qiskit-terra"
package_version = "0.22.4"
terra_version = "0.22.4"
timestamp = 1678827878.709677
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994626207"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.22.4"
terra_version = "0.22.4"
timestamp = 1678827878.709679
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994626228"

[[historical_test_results]]
test_type = "standard"
passed = true
package = "qiskit-terra"
package_version = "0.23.0"
terra_version = "0.23.0"
timestamp = 1678827878.709681
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052481624"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.23.0"
terra_version = "0.23.0"
timestamp = 1678827878.709683
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052481674"

[[historical_test_results]]
test_type = "standard"
passed = true
package = "qiskit-terra"
package_version = "0.23.1"
terra_version = "0.23.1"
timestamp = 1678827878.709688
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231020677"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.23.1"
terra_version = "0.23.1"
timestamp = 1678827878.70969
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231020708"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.23.2"
terra_version = "0.23.2"
timestamp = 1678827878.709692
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414044343"

[[historical_test_results]]
test_type = "standard"
passed = true
package = "qiskit-terra"
package_version = "0.23.2"
terra_version = "0.23.2"
timestamp = 1678827878.709695
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414044250"

[[historical_test_results]]
test_type = "development"
passed = true
package = "qiskit-terra"
package_version = "0.24.0"
terra_version = "0.24.0"
timestamp = 1678827878.698999
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414044381"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"

[configuration]
dependencies_files = [ "requirements.txt", "requirements-dev.txt",]
extra_dependencies = [ "coverage", "pylint",]
tests_command = [ "pytest -p no:warnings --pyargs kaleidoscope/test/no_qiskit",]
styles_check_command = [ "pylint -rn kaleidoscope",]
coverages_check_command = [ "coverage3 -m pytest -p no:warnings --pyargs kaleidoscope/test/no_qiskit", "coverage3 report --fail-under=80",]

[configuration.language]
name = "python"
versions = [ "3.6",]
