name = "(Large-scale) Quantum Network Coding"
url = "https://github.com/NagyTamas0122/Large-scale_QuantumNetworkCoding"
description = "Simulate (Large-scale) Quantum Network Coding in Quantum Repeater Network environment."
contact_info = "mikrobi.0122@gmail.com"
labels = [ "quantum information",]
group = "Application"
reference_paper = "https://ieeexplore.ieee.org/document/8019800"
packages = []
uuid = "67bfc31d-8b98-4c10-8ac2-fba3c59e2732"
badge = "https://qisk.it/e-67bfc31d"

[github]
url = "https://github.com/NagyTamas0122/Large-scale_QuantumNetworkCoding"
owner = "NagyTamas0122"
repo = "Large-scale_QuantumNetworkCoding"
stars = 0
license = "Apache License 2.0"
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2025-12-09T18:55:12Z
last_activity = 2025-12-09T18:55:13Z
