name = "(Large-scale) Quantum Network Coding"
url = "https://github.com/NagyTamas0122/Large-scale_QuantumNetworkCoding"
description = "Simulate (Large-scale) Quantum Network Coding in Quantum Repeater Network environment."
contact_info = "mikrobi.0122@gmail.com"
labels = [ "quantum information",]
group = "Application"
reference_paper = "https://ieeexplore.ieee.org/document/8019800"
packages = []
uuid = "67bfc31d-8b98-4c10-8ac2-fba3c59e2732"

[github]
owner = "NagyTamas0122"
repo = "Large-scale_QuantumNetworkCoding"
