name = "mirror-gates"
url = "https://github.com/Pitt-JonesLab/mirror-gates"
description = "MIRAGE is a transpilation plugin for quantum circuits that minimizes the use of SWAP gates while optimizing native basis gate decomposition through mirror gates. Specifically designed for iSWAP-based quantum systems, MIRAGE improves circuit depth, making quantum algorithms more practical and efficient."
licence = "MIT license"
contact_info = "evmckinney9@gmail.com"
alternatives = "_No response_"
affiliations = "University of Pittsburgh"
labels = [ "Paper implementation",]
tier = "Community"
website = "https://arxiv.org/abs/2308.03874"
styles_results = []
coverages_results = []
skip_tests = false
stars = 3
group = "transpiler_plugin"
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = ""
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7098434721"
package_commit_hash = "b1fc8e9bddacf63e8bf0e535f9e0c18233746ee2"
qiskit_version = ""
timestamp = 1701767432.208908

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit"
package_version = "0.45.1"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7098434721"
qiskit_version = "0.45.1"
timestamp = 1701767540.179953

[[tests_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.45.1"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7098434721"
qiskit_version = "0.45.1"
timestamp = 1701767245.54787

[[tests_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.43.3"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7098434721"
qiskit_version = "0.43.3"
timestamp = 1701767538.206442

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6310543442"
qiskit_version = "0.44.1"
timestamp = 1695719974.491691

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6310543442"
qiskit_version = "0.44.1"
timestamp = 1695719534.001157

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6545038402"
package_commit_hash = "62467839e8d4e263465c42118414e6e5eca3c776"
qiskit_version = "0.45.0"
timestamp = 1697534336.658552

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.44.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624756541"
qiskit_version = "0.44.2"
timestamp = 1698139199.340997

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624756541"
qiskit_version = "0.44.2"
timestamp = 1698138764.001804

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "1.0.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624756541"
package_commit_hash = "fe3bffbc85a4fb57dc62ba04fa7f11bcefb5d75f"
qiskit_version = "1.0.0"
timestamp = 1698139161.164437

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = ""
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7098434721"
package_commit_hash = "b1fc8e9bddacf63e8bf0e535f9e0c18233746ee2"
qiskit_version = ""
timestamp = 1701767432.208908

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.45.1"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7098434721"
qiskit_version = "0.45.1"
timestamp = 1701767245.54787

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.43.3"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7098434721"
qiskit_version = "0.43.3"
timestamp = 1701767538.206442

