name = "mirror-gates"
url = "https://github.com/Pitt-JonesLab/mirror-gates"
description = "MIRAGE is a transpilation plugin for quantum circuits that minimizes the use of SWAP gates while optimizing native basis gate decomposition through mirror gates. Specifically designed for iSWAP-based quantum systems, MIRAGE improves circuit depth, making quantum algorithms more practical and efficient."
licence = "MIT license"
contact_info = "evmckinney9@gmail.com"
alternatives = "_No response_"
affiliations = "University of Pittsburgh"
labels = [ "Transpiler plugin", "Paper implementation",]
tier = "Community"
website = "https://arxiv.org/abs/2308.03874"
styles_results = []
coverages_results = []
skip_tests = false
stars = 2
[[tests_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6233532208"
package_commit_hash = "2d3632fee633413bb1883e411d1a26f76fc54e92"
qiskit_version = "0.45.0"
timestamp = 1695115029.143158

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6233532208"
qiskit_version = "0.44.1"
timestamp = 1695115068.252887

[[tests_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6233532208"
qiskit_version = "0.44.1"
timestamp = 1695114720.635349

[[tests_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6233532208"
qiskit_version = "0.44.1"
timestamp = 1695115067.13354

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6233532208"
qiskit_version = "0.44.1"
timestamp = 1695114720.635349

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6233532208"
package_commit_hash = "2d3632fee633413bb1883e411d1a26f76fc54e92"
qiskit_version = "0.45.0"
timestamp = 1695115029.143158

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6233532208"
qiskit_version = "0.44.1"
timestamp = 1695115067.13354

