name = "mitiq"
url = "https://github.com/unitaryfund/mitiq"
description = "Mitiq is a Python toolkit for implementing error mitigation techniques on quantum computers"
licence = "Apache 2.0"
labels = [ "Error mitigation",]
created_at = 1678827878.932437
updated_at = 1678827878.932437
tier = "Community"
skip_tests = false
stars = 276
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5924783684"
package_commit_hash = "7bc2bfd4f8dcc436aec5f85641e3ec07be15eb01"
qiskit_version = "0.45.0"
timestamp = 1692617550.562734

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5924783684"
qiskit_version = "0.44.1"
timestamp = 1692617550.562743

[[tests_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5924783684"
qiskit_version = "0.44.1"
timestamp = 1692617550.562747

[[tests_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5924783684"
qiskit_version = "0.44.1"
timestamp = 1692617550.433898

[[styles_results]]
passed = false
style_type = "pylint"

[[coverages_results]]
passed = false
coverage_type = ""

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit-terra"
package_version = "0.37.0"
qiskit_version = "0.37.0"
timestamp = 1692617550.562765

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit-terra"
package_version = "0.36.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2617548449"
qiskit_version = "0.36.2"
timestamp = 1692617550.562769

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit-terra"
package_version = "0.36.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2617548449"
qiskit_version = "0.36.2"
timestamp = 1692617550.562772

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit-terra"
package_version = "0.37.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824121261"
qiskit_version = "0.37.1"
timestamp = 1692617550.562775

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.37.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824121261"
qiskit_version = "0.37.1"
timestamp = 1692617550.562779

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit-terra"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3180919750"
package_commit_hash = "53e215c31cf3aea51a623dc22883ac92fe74d0b9"
qiskit_version = "0.39.0"
timestamp = 1692617550.562782

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit-terra"
package_version = "0.38.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225638345"
qiskit_version = "0.38.0"
timestamp = 1692617550.562786

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit-terra"
package_version = "0.38.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225638304"
qiskit_version = "0.38.0"
timestamp = 1692617550.562789

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit-terra"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368224255"
qiskit_version = "0.39.0"
timestamp = 1692617550.562792

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit-terra"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368224230"
qiskit_version = "0.39.0"
timestamp = 1692617550.562795

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit-terra"
package_version = "0.39.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521951515"
qiskit_version = "0.39.2"
timestamp = 1692617550.562798

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit-terra"
package_version = "0.39.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521951564"
qiskit_version = "0.39.2"
timestamp = 1692617550.562801

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "unknown"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3739076129"
qiskit_version = "unknown"
timestamp = 1692617550.562804

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "unknown"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3739076183"
qiskit_version = "unknown"
timestamp = 1692617550.562807

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit-terra"
package_version = "unknown"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3739076243"
package_commit_hash = "07e0a2fc79bada7c1fbf0594f4ad33934f70b7e2"
qiskit_version = "unknown"
timestamp = 1692617550.562811

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit-terra"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937702596"
package_commit_hash = "af0b2220b75fd5cf3980576b1a31f9c4ceb9f99f"
qiskit_version = "0.40.0"
timestamp = 1692617550.562814

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.39.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937702443"
qiskit_version = "0.39.4"
timestamp = 1692617550.562818

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit-terra"
package_version = "0.39.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937702348"
qiskit_version = "0.39.4"
timestamp = 1692617550.562821

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.39.5"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994626991"
qiskit_version = "0.39.5"
timestamp = 1692617550.562824

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit-terra"
package_version = "0.39.5"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994626957"
qiskit_version = "0.39.5"
timestamp = 1692617550.562827

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052482306"
qiskit_version = "0.40.0"
timestamp = 1692617550.56283

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit-terra"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052482198"
qiskit_version = "0.40.0"
timestamp = 1692617550.562833

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.41.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231021293"
qiskit_version = "0.41.0"
timestamp = 1692617550.562836

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit-terra"
package_version = "0.41.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231021201"
qiskit_version = "0.41.0"
timestamp = 1692617550.562839

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit-terra"
package_version = "0.41.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414044770"
qiskit_version = "0.41.1"
timestamp = 1692617550.562842

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit-terra"
package_version = "0.43.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414044858"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"
qiskit_version = "0.43.0"
timestamp = 1692617550.562845

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.41.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414044812"
qiskit_version = "0.41.1"
timestamp = 1692617550.562848

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5924783684"
qiskit_version = "0.44.1"
timestamp = 1692617550.562851

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5924783684"
package_commit_hash = "7bc2bfd4f8dcc436aec5f85641e3ec07be15eb01"
qiskit_version = "0.45.0"
timestamp = 1692617550.562855

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5924783684"
qiskit_version = "0.44.1"
timestamp = 1692617550.433898

[configuration]
dependencies_files = [ "requirements.txt", "dev_requirements.txt",]
extra_dependencies = [ "coverage", "pylint", "qiskit",]
tests_command = [ "pytest -n auto -v --cov=mitiq --cov-report=term --cov-report=xml --ignore=mitiq/interface/mitiq_pyquil",]
styles_check_command = [ "pylint -rn mitiq",]
coverages_check_command = [ "pytest -n auto -v --cov=mitiq --cov-report=term --cov-report=xml",]

[configuration.language]
name = "python"
versions = [ "3.6",]
