name = "Mitiq"
url = "https://github.com/unitaryfund/mitiq"
description = "Mitiq is a Python toolkit for implementing error mitigation techniques on quantum computers."
licence = "Apache 2.0"
labels = [ "Error mitigation",]
ibm_maintained = false
created_at = 1678827878.932437
updated_at = 1678827878.932437
stars = 401
group = "other"
uuid = "a4ba9712-0aae-4660-b2df-4e6e81abb6c4"
badge = "[![Qiskit Ecosystem](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fqiskit.github.io%2Fecosystem%2Fb%2Fa4ba9712)](https://qisk.it/e)"

[github]
owner = "unitaryfund"
repo = "mitiq"
stars = 401
