name = "MQT DDSIM"
url = "https://github.com/cda-tum/mqt-ddsim"
description = "A classical quantum circuit simulator based on decision diagrams developed as part of the Munich Quantum Toolkit (MQT)."
licence = "MIT license"
contact_info = "quantum.cda@xcit.tum.de"
affiliations = "Technical University of Munich (TUM), Germany"
labels = [ "Circuit simulator", "Paper implementation",]
ibm_maintained = false
website = "https://mqt.readthedocs.io"
stars = 146
group = "other"
reference_paper = "https://arxiv.org/abs/2405.17543"
documentation = "https://mqt.readthedocs.io/projects/ddsim"
uuid = "b852a97c-eef8-46aa-a635-9c56a66e6ee0"
