name = "MQT Bench"
url = "https://github.com/cda-tum/mqt-bench"
description = "A circuit benchmark suite offering the same algorithms across abstraction levels to evaluate quantum software tools and hardware."
licence = "MIT license"
contact_info = "quantum.cda@xcit.tum.de"
affiliations = "Technical University of Munich (TUM), Germany"
labels = [ "circuit manipulation", "research",]
website = "https://www.cda.cit.tum.de/mqtbench/"
group = "Application"
reference_paper = "https://quantum-journal.org/papers/q-2023-07-20-1062/"
documentation = "https://mqt.readthedocs.io/projects/bench/en/latest/"
uuid = "06f1e81e-e82a-4fc2-88b5-60b532248af1"
badge = "https://qisk.it/e-06f1e81e"

[github]
url = "https://github.com/munich-quantum-toolkit/bench"
owner = "munich-quantum-toolkit"
repo = "bench"
stars = 105
homepage = "https://mqt-bench.app/"
license = "MIT License"
description = "MQT Bench - An MQT Tool for Benchmarking Quantum Software Tools"
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2025-12-08T00:50:34Z
last_activity = 2025-12-08T01:11:29Z

[pypi."mqt.bench"]
package_name = "mqt-bench"
version = "2.1.0"
url = "https://pypi.org/project/mqt.bench/"
requires_qiskit = ">=1.3.2"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2025-10-22T14:47:06Z
highest_supported_qiskit_version = "2.2.2"
last_month_downloads = 7153
last_180_days_downloads = 20932
