name = "MQT Core"
url = "https://github.com/cda-tum/mqt-core"
description = "MQT Core forms the backbone of the software tools developed as part of the Munich Quantum Toolkit (MQT) and connects it to Qiskit."
licence = "MIT license"
contact_info = "quantum.cda@xcit.tum.de"
affiliations = "Technical University of Munich (TUM), Germany"
labels = [ "circuit manipulation",]
website = "https://mqt.readthedocs.io"
group = "Converter"
reference_paper = "https://arxiv.org/abs/2405.17543"
documentation = "https://mqt.readthedocs.io/projects/core"
uuid = "2309e6fb-3077-4c8e-af3f-bddf4d6cb458"
badge = "https://qisk.it/e-2309e6fb"

[github]
url = "https://github.com/munich-quantum-toolkit/core"
owner = "munich-quantum-toolkit"
repo = "core"
stars = 103
homepage = "https://mqt.readthedocs.io/projects/core"
license = "MIT License"
description = "MQT Core - The Backbone of the Munich Quantum Toolkit"
total_dependent_repositories = 42
total_dependent_packages = 0
last_commit = 2025-12-08T23:20:44Z
last_activity = 2025-12-08T23:22:44Z

[pypi."mqt.core"]
package_name = "mqt-core"
version = "3.3.3"
url = "https://pypi.org/project/mqt-core/"
requires_qiskit = ">=1.0.0"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2025-10-22T14:47:06Z
highest_supported_qiskit_version = "2.2.2"
last_month_downloads = 44853
last_180_days_downloads = 189761
