name = "MQT QAO"
url = "https://github.com/cda-tum/mqt-qao"
description = "Translate optimization problems into quantum-compliant formats and solve them with major quantum solvers."
licence = "MIT license"
contact_info = "quantum.cda@xcit.tum.de"
affiliations = "Technical University of Munich (TUM), Germany Politecnico di Torino, Italy"
labels = [ "Algorithms", "Applications", "Circuit building tool", "Paper implementation", "Optimization",]
ibm_maintained = false
stars = 27
group = "applications"
reference_paper = "https://arxiv.org/abs/2406.12840"
documentation = "https://mqt.readthedocs.io/projects/qao/en/latest/"
uuid = "6d4c69e4-1e47-486c-b00f-8a60ae5e01d4"
badge = "[![Qiskit Ecosystem](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fqiskit.github.io%2Fecosystem%2Fb%2F6d4c69e4)](https://qisk.it/e)"

[github]
url = "https://github.com/cda-tum/mqt-qao"
owner = "cda-tum"
repo = "mqt-qao"
stars = 27
last_commit = 2025-11-10T17:36:09Z

[pypi."mqt.qao"]
package_name = "mqt-qao"
version = "0.3.0"
url = "https://pypi.org/project/mqt.qao/"
requires_qiskit = ">=1.0"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2025-10-22T14:47:06Z
highest_supported_qiskit_version = "2.2.2"
