name = "MQT QCEC"
url = "https://github.com/cda-tum/mqt-qcec"
description = "A tool for quantum circuit equivalence checking developed as part of the Munich Quantum Toolkit (MQT)."
licence = "MIT license"
contact_info = "quantum.cda@xcit.tum.de"
affiliations = "Technical University of Munich (TUM), Germany"
labels = [ "research", "quantum information",]
website = "https://mqt.readthedocs.io"
group = "Other"
reference_paper = "https://arxiv.org/abs/2405.17543"
documentation = "https://mqt.readthedocs.io/projects/qcec"
uuid = "79415931-2d24-4959-ab15-29dfaeb139b4"
badge = "[![Qiskit Ecosystem](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fqiskit.github.io%2Fecosystem%2Fb%2F79415931)](https://qisk.it/e)"

[github]
url = "https://github.com/munich-quantum-toolkit/qcec"
owner = "munich-quantum-toolkit"
repo = "qcec"
stars = 106
homepage = "https://mqt.readthedocs.io/projects/qcec"
license = "MIT License"
description = "MQT QCEC - A tool for Quantum Circuit Equivalence Checking"
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2025-12-01T11:51:36Z
last_activity = 2025-12-01T11:51:37Z

[pypi."mqt.qcec"]
package_name = "mqt-qcec"
version = "3.3.0"
url = "https://pypi.org/project/mqt.qcec/"
requires_qiskit = ">=1.0.0"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2025-10-22T14:47:06Z
highest_supported_qiskit_version = "2.2.2"
last_month_downloads = 7574
last_180_days_downloads = 45862
