name = "MQT DDSIM"
url = "https://github.com/cda-tum/mqt-ddsim"
description = "A classical quantum circuit simulator based on decision diagrams developed as part of the Munich Quantum Toolkit (MQT)."
licence = "MIT license"
contact_info = "quantum.cda@xcit.tum.de"
affiliations = "Technical University of Munich (TUM), Germany"
labels = [ "research",]
website = "https://mqt.readthedocs.io"
group = "Circuit simulator"
reference_paper = "https://arxiv.org/abs/2405.17543"
documentation = "https://mqt.readthedocs.io/projects/ddsim"
uuid = "b852a97c-eef8-46aa-a635-9c56a66e6ee0"
badge = "https://qisk.it/e-b852a97c"

[github]
url = "https://github.com/munich-quantum-toolkit/ddsim"
owner = "munich-quantum-toolkit"
repo = "ddsim"
stars = 156
homepage = "https://mqt.readthedocs.io/projects/ddsim"
license = "MIT License"
description = "MQT DDSIM - A quantum circuit simulator based on decision diagrams written in C++"
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2025-12-08T00:57:19Z
last_activity = 2025-12-08T00:57:20Z

[pypi."mqt.ddsim"]
package_name = "mqt-ddsim"
version = "2.1.0"
url = "https://pypi.org/project/mqt.ddsim/"
requires_qiskit = ">=1.1"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2025-10-22T14:47:06Z
highest_supported_qiskit_version = "2.2.2"
last_month_downloads = 4846
last_180_days_downloads = 35211
