name = "MQT ProblemSolver"
url = "https://github.com/cda-tum/MQTProblemSolver"
description = "A framework for users with little to no quantum computing knowledge to solve common problems. Part of the Munich Quantum Toolkit (MQT)."
licence = "MIT license"
contact_info = "quantum.cda@xcit.tum.de"
affiliations = "Technical University of Munich (TUM), Germany"
labels = [ "research",]
group = "Application"
reference_paper = "https://arxiv.org/pdf/2210.14928"
uuid = "4262945e-f1af-441a-ad38-c803a5c6df0b"
badge = "https://qisk.it/e-4262945e"

[github]
url = "https://github.com/munich-quantum-toolkit/problemsolver"
owner = "munich-quantum-toolkit"
repo = "problemsolver"
stars = 53
homepage = "https://munich-quantum-toolkit.github.io/problemsolver/"
license = "MIT License"
description = "MQT ProblemSolver - A MQT Tool for Solving Problems Using Quantum Computing"
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2026-01-12T14:13:20Z
last_activity = 2026-01-12T14:13:19Z

[pypi."mqt.problemsolver"]
package_name = "mqt-problemsolver"
version = "0.4"
url = "https://pypi.org/project/mqt.problemsolver/"
requires_qiskit = "<0.42.0,>=0.36.0"
compatible_with_qiskit_v1 = false
compatible_with_qiskit_v2 = false
highest_supported_qiskit_release_date = 2023-02-24T09:50:56Z
highest_supported_qiskit_version = "0.41.1"
last_month_downloads = 15
last_180_days_downloads = 168
