name = "MQT QECC"
url = "https://github.com/cda-tum/mqt-qecc"
description = "A collection of tools for decoding and synthesizing fault-tolerant quantum circuits."
licence = "MIT license"
contact_info = "quantum.cda@xcit.tum.de"
affiliations = "Technical University of Munich (TUM), Germany"
labels = [ "error correction",]
website = "https://mqt.readthedocs.io"
group = "Other"
documentation = "https://mqt.readthedocs.io/projects/qecc/en/latest/"
uuid = "791d4814-0ced-4f5a-94c5-908ceb4b5a90"
badge = "https://qisk.it/e-791d4814"

[github]
url = "https://github.com/munich-quantum-toolkit/qecc"
owner = "munich-quantum-toolkit"
repo = "qecc"
stars = 185
homepage = "https://mqt.readthedocs.io/projects/qecc"
license = "MIT License"
description = "MQT QECC - Tools for Quantum Error Correcting Codes"
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2025-12-31T13:50:11Z
last_activity = 2025-12-31T13:50:08Z

[pypi."mqt.qcec"]
package_name = "mqt-qcec"
version = "3.3.0"
url = "https://pypi.org/project/mqt.qcec/"
requires_qiskit = ">=1.0.0"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2025-10-22T14:47:06Z
highest_supported_qiskit_version = "2.2.2"
last_month_downloads = 7574
last_180_days_downloads = 45862
