name = "MQT QMAP"
url = "https://github.com/cda-tum/mqt-qmap"
description = "A tool for quantum circuit compilation for various qubit technologies developed as part of the Munich Quantum Toolkit (MQT)."
licence = "MIT license"
contact_info = "quantum.cda@xcit.tum.de"
affiliations = "Technical University of Munich (TUM), Germany"
labels = [ "research", "circuit manipulation",]
website = "https://mqt.readthedocs.io"
group = "Transpiler plugin"
reference_paper = "https://arxiv.org/abs/2405.17543"
documentation = "https://mqt.readthedocs.io/projects/qmap"
uuid = "d16209fb-443e-47ad-8090-9396a0cc592d"
badge = "https://qisk.it/e-d16209fb"

[github]
url = "https://github.com/munich-quantum-toolkit/qmap"
owner = "munich-quantum-toolkit"
repo = "qmap"
stars = 131
homepage = "https://mqt.readthedocs.io/projects/qmap"
license = "MIT License"
description = "MQT QMAP - A tool for Quantum Circuit Mapping written in C++"
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2026-01-19T01:38:55Z
last_activity = 2026-01-20T13:55:12Z

[pypi."mqt.qmap"]
package_name = "mqt-qmap"
version = "3.4.0"
url = "https://pypi.org/project/mqt.qmap/"
requires_qiskit = ">=1.0.0"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2025-10-22T14:47:06Z
highest_supported_qiskit_version = "2.2.2"
last_month_downloads = 3223
last_180_days_downloads = 23510
