name = "mthree"
url = "https://github.com/Qiskit-Partners/mthree"
description = "Matrix-free Measurement Mitigation (M3)"
licence = "Apache 2.0"
contact_info = ""
alternatives = ""
labels = [ "Error mitigation",]
group = "other"
created_at = 1678827878.805163
updated_at = 1678827878.805164
tier = "Extensions"
styles_results = []
coverages_results = []
skip_tests = false
stars = 26
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624760423"
package_commit_hash = "fe3bffbc85a4fb57dc62ba04fa7f11bcefb5d75f"
qiskit_version = "unknown"
timestamp = 1698139754.783217

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit"
package_version = "0.41.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231024987"
qiskit_version = "0.41.0"
timestamp = 1692696278.114188

[[tests_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624760423"
qiskit_version = "unknown"
timestamp = 1698139682.371153

[[tests_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624760423"
qiskit_version = "unknown"
timestamp = 1698139826.291417

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.37.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824121650"
qiskit_version = "0.37.1"
timestamp = 1692696278.114202

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.37.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824121650"
qiskit_version = "0.37.1"
timestamp = 1692696278.114206

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.38.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3180921293"
qiskit_version = "0.38.0"
timestamp = 1692696278.114209

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3180921367"
package_commit_hash = "53e215c31cf3aea51a623dc22883ac92fe74d0b9"
qiskit_version = "0.39.0"
timestamp = 1692696278.114212

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.38.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225639689"
qiskit_version = "0.38.0"
timestamp = 1692696278.114216

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368226321"
qiskit_version = "0.39.0"
timestamp = 1692696278.114219

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368226347"
qiskit_version = "0.39.0"
timestamp = 1692696278.114222

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.39.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3469025244"
qiskit_version = "0.39.2"
timestamp = 1692696278.114226

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.39.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521954458"
qiskit_version = "0.39.2"
timestamp = 1692696278.114229

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.39.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937706305"
qiskit_version = "0.39.4"
timestamp = 1692696278.114232

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937706326"
package_commit_hash = "af0b2220b75fd5cf3980576b1a31f9c4ceb9f99f"
qiskit_version = "0.40.0"
timestamp = 1692696278.114236

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.39.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937706246"
qiskit_version = "0.39.4"
timestamp = 1692696278.114239

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.39.5"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994631633"
qiskit_version = "0.39.5"
timestamp = 1692696278.114242

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.39.5"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994631645"
qiskit_version = "0.39.5"
timestamp = 1692696278.114245

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052486650"
qiskit_version = "0.40.0"
timestamp = 1692696278.114249

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052486607"
qiskit_version = "0.40.0"
timestamp = 1692696278.114252

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.41.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231024987"
qiskit_version = "0.41.0"
timestamp = 1692696278.114255

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.41.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231024915"
qiskit_version = "0.41.0"
timestamp = 1692696278.114258

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.41.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414049585"
qiskit_version = "0.41.1"
timestamp = 1692696278.114262

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.41.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414049662"
qiskit_version = "0.41.1"
timestamp = 1692696278.114265

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.43.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414049677"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"
qiskit_version = "0.43.0"
timestamp = 1692696278.114268

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624760423"
qiskit_version = "unknown"
timestamp = 1698139826.291417

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624760423"
package_commit_hash = "fe3bffbc85a4fb57dc62ba04fa7f11bcefb5d75f"
qiskit_version = "unknown"
timestamp = 1698139754.783217

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624760423"
qiskit_version = "unknown"
timestamp = 1698139682.371153

[configuration]
dependencies_files = [ "requirements.txt", "requirements-dev.txt",]
extra_dependencies = []
debian_dependencies = []
tests_command = [ "pytest -p no:warnings --pyargs mthree/test",]
styles_check_command = [ "pylint -rn mthree",]
coverages_check_command = []

[configuration.language]
name = "python"
versions = [ "3.7",]
