name = "mthree"
url = "https://github.com/Qiskit-Partners/mthree"
description = "Matrix-free Measurement Mitigation (M3). Reduce the effects of readout errors from noisy quantum hardware."
licence = "Apache 2.0"
contact_info = ""
alternatives = ""
labels = [ "IBM maintained", "Error mitigation",]
created_at = 1678827878.805163
updated_at = 1678827878.805164
stars = 32
group = "other"
