name = "qOMM"
url = "https://github.com/renlililoli/OMM"
description = "Implementation of the quantum orbital minimization method to calculate the ground state and first few excited states of a Hamiltonian."
licence = "MIT license"
contact_info = "renlililoli@163.com"
labels = []
ibm_maintained = false
stars = 1
group = "other"
reference_paper = "https://arxiv.org/abs/2201.07963"
uuid = "b1285a61-8b2d-4f0a-8afd-678d6e57e0a9"
