name = "OpenQASM"
url = "https://github.com/openqasm/openqasm"
description = "An imperative programming language for near-term quantum computing. Describe quantum programs by using the measurement-based quantum circuit model with support for classical feedforward flow control based on measurement outcomes."
licence = "Apache 2.0"
contact_info = "_No response_"
alternatives = "_No response_"
affiliations = "OpenQASM specification contributors"
labels = [ "OpenQASM",]
created_at = 1660223774.444544
updated_at = 1660223774.44455
website = "https://openqasm.com/"
stars = 1143
group = "other"
