name = "OpenQASM"
url = "https://github.com/openqasm/openqasm"
website = "https://openqasm.com/"
description = "OpenQASM is an imperative programming language designed for near-term quantum computing algorithms and applications. Quantum programs are described using the measurement-based quantum circuit model with support for classical feed-forward flow control based on measurement outcomes."
licence = "Apache 2.0"
contact_info = "_No response_"
alternatives = "_No response_"
affiliations = "OpenQASM specification contributors"
labels = [ "openqasm",]
created_at = 1660223774.444544
updated_at = 1660223774.44455
tests_results = []
styles_results = []
coverages_results = []
tier = "Main"
skip_tests = true
historical_test_results = []
stars = 1024
