name = "Pennylane-Qiskit"
url = "https://github.com/PennyLaneAI/pennylane-qiskit"
description = "The PennyLane-Qiskit plugin integrates the Qiskit quantum computing framework with PennyLane's quantum machine learning capabilities."
licence = "Apache 2.0"
labels = []
created_at = 1678827878.782751
updated_at = 1678827878.782752
group = "Converter"
uuid = "cfbecefc-6cf7-49a6-99c5-049dae76fdcc"
badge = "https://qisk.it/e-cfbecefc"

[github]
url = "https://github.com/PennyLaneAI/pennylane-qiskit"
owner = "PennyLaneAI"
repo = "pennylane-qiskit"
stars = 221
homepage = "https://docs.pennylane.ai/projects/qiskit"
license = "Apache License 2.0"
description = "The PennyLane-Qiskit plugin integrates the Qiskit quantum computing framework and IBM Q with PennyLane."
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2025-12-10T22:37:49Z
last_activity = 2025-12-10T22:37:49Z

[pypi.pennylane-qiskit]
package_name = "pennylane-qiskit"
version = "0.43.0"
url = "https://pypi.org/project/PennyLane-qiskit/"
requires_qiskit = "<2.2,>=2.0"
compatible_with_qiskit_v1 = false
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2025-08-19T15:29:40Z
highest_supported_qiskit_version = "2.1.2"
last_month_downloads = 21426
last_180_days_downloads = 111736
