name = "Pennylane-Qiskit"
url = "https://github.com/PennyLaneAI/pennylane-qiskit"
description = "The PennyLane-Qiskit plugin integrates the Qiskit quantum computing framework with PennyLane's quantum machine learning capabilities."
licence = "Apache 2.0"
labels = [ "Converter",]
created_at = 1678827878.782751
updated_at = 1678827878.782752
tier = "Community"
skip_tests = false
stars = 136
group = "other"
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624756813"
package_commit_hash = "fe3bffbc85a4fb57dc62ba04fa7f11bcefb5d75f"
qiskit_version = "unknown"
timestamp = 1698138740.260072

[[tests_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624756813"
qiskit_version = "unknown"
timestamp = 1698138729.221521

[[tests_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624756813"
qiskit_version = "unknown"
timestamp = 1698138750.98411

[[styles_results]]
passed = false
style_type = "pylint"

[[coverages_results]]
passed = false
coverage_type = ""

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.37.0"
qiskit_version = "0.37.0"
timestamp = 1692695490.79955

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2617548463"
package_commit_hash = "c60d3b8e735d54c1180fe788876f3c4dacbc3cba"
qiskit_version = "0.39.0"
timestamp = 1692695490.799553

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.34.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2617548463"
qiskit_version = "0.34.1"
timestamp = 1692695490.799556

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.34.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2617548463"
qiskit_version = "0.34.1"
timestamp = 1692695490.799559

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "-"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3039653656"
qiskit_version = "-"
timestamp = 1692695490.799562

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "-"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3039653687"
package_commit_hash = "055fe0f9c9ca3b3b994f68ba2c7647763a29f63b"
qiskit_version = "-"
timestamp = 1692695490.799565

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "-"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3039653655"
qiskit_version = "-"
timestamp = 1692695490.799568

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624756813"
qiskit_version = "unknown"
timestamp = 1698138750.98411

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624756813"
package_commit_hash = "fe3bffbc85a4fb57dc62ba04fa7f11bcefb5d75f"
qiskit_version = "unknown"
timestamp = 1698138740.260072

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624756813"
qiskit_version = "unknown"
timestamp = 1698138729.221521

[configuration]
dependencies_files = [ "requirements.txt",]
extra_dependencies = [ "coverage", "pylint", "qiskit",]
debian_dependencies = []
tests_command = [ "pytest tests --tb=short",]
styles_check_command = [ "pylint -rn pennylane_qiskit tests",]
coverages_check_command = [ "python3 -m pytest tests --tb=short --cov=pennylane_qiskit --cov-report term-missing --cov-report=html:coverage_html_report",]

[configuration.language]
name = "python"
versions = [ "3.6",]
