name = "piQture"
url = "https://github.com/SaashaJoshi/piQture"
description = "Develop, execute, and train Quantum Machine Learning models tailored for image processing tasks. Seamlessly integrated with Qiskit."
licence = "Apache License 2.0"
contact_info = "saashajoshi08@gmail.com"
affiliations = "University of Victoria"
labels = [ "Algorithms", "Applications", "Machine learning",]
ibm_maintained = false
stars = 57
group = "applications"
reference_paper = "https://hdl.handle.net/1828/16627"
uuid = "da29aca4-ba28-4d62-942b-f4c5371e7b6e"
badge = "[![Qiskit Ecosystem](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fqiskit.github.io%2Fecosystem%2Fb%2Fda29aca4)](https://qisk.it/e)"

[github]
owner = "SaashaJoshi"
repo = "piQture"
stars = 57

[pypi.piqture]
project = "piqture"
requires_qiskit = ">=2.0.0"
