name = "piQture"
url = "https://github.com/SaashaJoshi/piQture"
description = "Develop, execute, and train Quantum Machine Learning models tailored for image processing tasks. Seamlessly integrated with Qiskit."
licence = "Apache License 2.0"
contact_info = "saashajoshi08@gmail.com"
affiliations = "University of Victoria"
labels = [ "Algorithms", "Applications", "Machine learning",]
ibm_maintained = false
stars = 58
group = "applications"
reference_paper = "https://hdl.handle.net/1828/16627"
uuid = "da29aca4-ba28-4d62-942b-f4c5371e7b6e"
badge = "[![Qiskit Ecosystem](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fqiskit.github.io%2Fecosystem%2Fb%2Fda29aca4)](https://qisk.it/e)"

[github]
url = "https://github.com/SaashaJoshi/piQture"
owner = "SaashaJoshi"
repo = "piQture"
stars = 58
last_commit = 2025-07-25T20:40:18Z

[pypi.piqture]
package_name = "piqture"
version = "0.2.0"
url = "https://pypi.org/project/piQture/"
requires_qiskit = ">=2.0.0"
compatible_with_qiskit_v1 = false
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2025-10-22T14:47:06Z
highest_supported_qiskit_version = "2.2.2"
