name = "POVM Toolbox"
url = "https://github.com/qiskit-community/povm-toolbox"
description = "A toolbox for the implementation of positive operator-valued measures (POVMs)."
licence = "Apache License 2.0"
contact_info = "oss@zurich.ibm.com"
alternatives = "_No response_"
affiliations = "_No response_"
labels = [ "Quantum information", "Algorithms", "Circuit building tool",]
ibm_maintained = false
stars = 38
group = "other"
documentation = "https://qiskit-community.github.io/povm-toolbox/"
uuid = "1fb3d426-e458-4c7a-be9e-e31a758bb872"
