name = "POVM Toolbox"
url = "https://github.com/qiskit-community/povm-toolbox"
description = "A toolbox for the implementation of positive operator-valued measures (POVMs)."
licence = "Apache License 2.0"
contact_info = "oss@zurich.ibm.com"
labels = [ "circuit building",]
group = "Other"
documentation = "https://qiskit-community.github.io/povm-toolbox/"
uuid = "1fb3d426-e458-4c7a-be9e-e31a758bb872"
badge = "https://qisk.it/e-1fb3d426"

[github]
url = "https://github.com/qiskit-community/povm-toolbox"
owner = "qiskit-community"
repo = "povm-toolbox"
stars = 39
homepage = "https://qiskit-community.github.io/povm-toolbox/"
license = "Apache License 2.0"
description = "A toolbox for the implementation of positive operator-valued measures (POVMs)."
estimated_contributors = 6
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2026-01-12T09:09:51Z
last_activity = 2026-01-12T09:09:51Z

[pypi.povm-toolbox]
package_name = "povm-toolbox"
version = "0.2.0"
url = "https://pypi.org/project/povm-toolbox/"
requires_qiskit = "<3,>=1.4"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2025-10-22T14:47:06Z
highest_supported_qiskit_version = "2.2.2"
last_month_downloads = 158
last_180_days_downloads = 2725
