name = "POVM Toolbox"
url = "https://github.com/qiskit-community/povm-toolbox"
description = "A toolbox for the implementation of positive operator-valued measures (POVMs)."
licence = "Apache License 2.0"
contact_info = "oss@zurich.ibm.com"
alternatives = "_No response_"
affiliations = "_No response_"
labels = [ "Quantum information",]
stars = 5
group = "other"
documentation = "https://qiskit-community.github.io/povm-toolbox/"
