name = "Quantum Random Access Optimization"
url = "https://github.com/qiskit-community/prototype-qrao"
description = "Solve larger combinatorial optimization problems with quantum random access codes. Save resources by encoding many binary variables on a single qubit before solving with standard variational algorithms."
licence = "Apache 2.0"
contact_info = ""
alternatives = ""
labels = [ "Optimization", "Prototype",]
created_at = 1678827878.909912
updated_at = 1678827878.909913
stars = 27
group = "applications"
