name = "Entanglement forging"
url = "https://github.com/qiskit-community/prototype-entanglement-forging"
description = "This module allows a user to simulate chemical and physical systems using a Variational Quantum Eigensolver (VQE) enhanced by Entanglement Forging. Entanglement Forging doubles the size of the system that can be exactly simulated on a fixed set of quantum bits."
licence = "Apache 2.0"
contact_info = ""
alternatives = ""
labels = [ "Prototype", "Chemistry",]
created_at = 1678827878.886831
updated_at = 1678827878.886832
tier = "Extensions"
styles_results = []
coverages_results = []
skip_tests = false
stars = 30
group = "applications"
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "1.0.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624760554"
package_commit_hash = "fe3bffbc85a4fb57dc62ba04fa7f11bcefb5d75f"
qiskit_version = "1.0.0"
timestamp = 1698140143.977066

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit"
package_version = "0.38.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3039654673"
qiskit_version = "0.38.0"
timestamp = 1692696549.367459

[[tests_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.44.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624760554"
qiskit_version = "0.44.2"
timestamp = 1698139722.304594

[[tests_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.35.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624760554"
qiskit_version = "0.35.0"
timestamp = 1698140218.816217

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.37.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824121527"
qiskit_version = "0.37.1"
timestamp = 1692696549.367475

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.37.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824121527"
qiskit_version = "0.37.1"
timestamp = 1692696549.367479

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.38.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3039654669"
qiskit_version = "0.38.0"
timestamp = 1692696549.367483

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3180921013"
package_commit_hash = "53e215c31cf3aea51a623dc22883ac92fe74d0b9"
qiskit_version = "0.39.0"
timestamp = 1692696549.367488

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.38.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225639436"
qiskit_version = "0.38.0"
timestamp = 1692696549.367492

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368225903"
qiskit_version = "0.39.0"
timestamp = 1692696549.367496

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.39.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521954071"
qiskit_version = "0.39.2"
timestamp = 1692696549.367499

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937705810"
package_commit_hash = "af0b2220b75fd5cf3980576b1a31f9c4ceb9f99f"
qiskit_version = "0.40.0"
timestamp = 1692696549.367503

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.39.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937705775"
qiskit_version = "0.39.4"
timestamp = 1692696549.367508

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.39.5"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994630976"
qiskit_version = "0.39.5"
timestamp = 1692696549.367512

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052486140"
qiskit_version = "0.40.0"
timestamp = 1692696549.367515

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.41.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231024378"
qiskit_version = "0.41.0"
timestamp = 1692696549.367519

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.41.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414048905"
qiskit_version = "0.41.1"
timestamp = 1692696549.367523

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.36.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414048792"
qiskit_version = "0.36.0"
timestamp = 1692696549.367526

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.43.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414048974"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"
qiskit_version = "0.43.0"
timestamp = 1692696549.36753

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6310548071"
qiskit_version = "0.44.1"
timestamp = 1695720317.004089

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6545042596"
package_commit_hash = "62467839e8d4e263465c42118414e6e5eca3c776"
qiskit_version = "0.45.0"
timestamp = 1697535273.464765

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "1.0.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624760554"
package_commit_hash = "fe3bffbc85a4fb57dc62ba04fa7f11bcefb5d75f"
qiskit_version = "1.0.0"
timestamp = 1698140143.977066

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.35.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624760554"
qiskit_version = "0.35.0"
timestamp = 1698140218.816217

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.44.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624760554"
qiskit_version = "0.44.2"
timestamp = 1698139722.304594

[configuration]
dependencies_files = []
extra_dependencies = [ "qiskit>=0.35.0", "qiskit_nature>=0.3.2", "pyscf>=2.0.1", "h5py>=3.6.0", "pytest", "black==22.3.0",]
debian_dependencies = []
tests_command = [ "python -m pytest tests",]
styles_check_command = [ "python -m black --check entanglement_forging tests",]
coverages_check_command = []

[configuration.language]
name = "python"
versions = [ "3.7",]
