name = "Quantum Kernel Training"
url = "https://github.com/qiskit-community/prototype-quantum-kernel-training"
description = "Train and use quantum kernels for machine learning. For researchers and practitioners looking to explore and apply these algorithms."
licence = "Apache 2.0"
contact_info = ""
labels = [ "Machine learning", "Applications",]
created_at = 1645480343.964777
updated_at = 1645480343.964777
group = "applications"
uuid = "6daa87ef-87ea-4dc9-aeed-3b9e8d202fd9"
badge = "[![Qiskit Ecosystem](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fqiskit.github.io%2Fecosystem%2Fb%2F6daa87ef)](https://qisk.it/e)"

[github]
url = "https://github.com/qiskit-community/prototype-quantum-kernel-training"
owner = "qiskit-community"
repo = "prototype-quantum-kernel-training"
stars = 45
homepage = "https://arxiv.org/abs/2105.03406"
license = "Apache License 2.0"
description = "Toolkit for training quantum kernels in machine learning applications"
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2024-03-31T17:02:36Z
