name = "Quantum Random Access Optimization"
url = "https://github.com/qiskit-community/prototype-qrao"
description = "The Quantum Random Access Optimization (QRAO) module is designed to enable users to leverage a new quantum method for combinatorial optimization problems."
licence = "Apache 2.0"
contact_info = ""
alternatives = ""
labels = [ "Optimization", "Prototype",]
created_at = 1678827878.909912
updated_at = 1678827878.909913
tier = "Community"
styles_results = []
coverages_results = []
skip_tests = false
stars = 27
[[tests_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936782681"
package_commit_hash = "0b51250e219ca303654fc28a318c21366584ccd3"
qiskit_version = "0.45.0"
timestamp = 1692696456.131841

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936782681"
qiskit_version = "0.44.1"
timestamp = 1692696456.271797

[[tests_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936782681"
qiskit_version = "0.44.1"
timestamp = 1692696456.271801

[[tests_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = ""
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936782681"
qiskit_version = ""
timestamp = 1692696456.271803

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.37.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824121584"
qiskit_version = "0.37.1"
timestamp = 1692696456.271809

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.37.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824121584"
qiskit_version = "0.37.1"
timestamp = 1692696456.271812

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3180921127"
package_commit_hash = "53e215c31cf3aea51a623dc22883ac92fe74d0b9"
qiskit_version = "0.39.0"
timestamp = 1692696456.271816

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.38.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225639520"
qiskit_version = "0.38.0"
timestamp = 1692696456.271819

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.38.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225639517"
qiskit_version = "0.38.0"
timestamp = 1692696456.271822

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368226033"
qiskit_version = "0.39.0"
timestamp = 1692696456.271825

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368225981"
qiskit_version = "0.39.0"
timestamp = 1692696456.271828

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.39.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521954179"
qiskit_version = "0.39.2"
timestamp = 1692696456.271832

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.39.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521954205"
qiskit_version = "0.39.2"
timestamp = 1692696456.271834

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.39.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937705929"
qiskit_version = "0.39.4"
timestamp = 1692696456.271837

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.39.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937705953"
qiskit_version = "0.39.4"
timestamp = 1692696456.27184

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937705973"
package_commit_hash = "af0b2220b75fd5cf3980576b1a31f9c4ceb9f99f"
qiskit_version = "0.40.0"
timestamp = 1692696456.271843

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.39.5"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994631129"
qiskit_version = "0.39.5"
timestamp = 1692696456.271846

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.39.5"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994631163"
qiskit_version = "0.39.5"
timestamp = 1692696456.271849

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052486294"
qiskit_version = "0.40.0"
timestamp = 1692696456.271851

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052486355"
qiskit_version = "0.40.0"
timestamp = 1692696456.271854

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.41.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231024475"
qiskit_version = "0.41.0"
timestamp = 1692696456.271857

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.41.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231024540"
qiskit_version = "0.41.0"
timestamp = 1692696456.27186

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.41.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414049043"
qiskit_version = "0.41.1"
timestamp = 1692696456.271863

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.41.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414049127"
qiskit_version = "0.41.1"
timestamp = 1692696456.271866

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.43.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414049192"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"
qiskit_version = "0.43.0"
timestamp = 1692696456.271869

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936782681"
qiskit_version = "0.44.1"
timestamp = 1692696456.271874

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = ""
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936782681"
qiskit_version = ""
timestamp = 1692696456.271877

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936782681"
package_commit_hash = "0b51250e219ca303654fc28a318c21366584ccd3"
qiskit_version = "0.45.0"
timestamp = 1692696456.131841

[configuration]
dependencies_files = [ "requirements.txt", "requirements-dev.txt",]
extra_dependencies = []
tests_command = [ "pip check", "python -m pytest",]
styles_check_command = [ "black .",]
coverages_check_command = []

[configuration.language]
name = "python"
versions = [ "3.7",]
