name = "purplecaffeine"
url = "https://github.com/IceKhan13/purplecaffeine"
description = "Project is aimed to create simple general interface to track quantum experiments, store and search them in an easy way."
licence = "Apache License 2.0"
contact_info = "_No response_"
alternatives = "_No response_"
affiliations = "QAMP"
labels = [ "Productivity", "Jupyter notebook",]
created_at = 1688661859.080258
updated_at = 1688661859.080264
tier = "Community"
website = "https://icekhan13.github.io/purplecaffeine/index.html"
styles_results = []
coverages_results = []
skip_tests = false
stars = 6
group = "other"
[[tests_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "1.0.0"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/6861457415"
package_commit_hash = "af6fbd0725de411fbc8f0ff70d550d77ebf715dc"
qiskit_version = "1.0.0"
timestamp = 1699953989.808253

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/6861457415"
qiskit_version = "0.45.0"
timestamp = 1699954114.750774

[[tests_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/6861457415"
qiskit_version = "0.45.0"
timestamp = 1699953322.990756

[[tests_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/6861457415"
qiskit_version = "0.45.0"
timestamp = 1699954109.904226

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6310543781"
qiskit_version = "0.44.1"
timestamp = 1695719671.169195

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6310543781"
qiskit_version = "0.44.1"
timestamp = 1695720141.771474

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6545035463"
package_commit_hash = "62467839e8d4e263465c42118414e6e5eca3c776"
qiskit_version = "0.45.0"
timestamp = 1697534512.954835

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.44.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624755024"
qiskit_version = "0.44.2"
timestamp = 1698139707.001367

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624755024"
qiskit_version = "0.44.2"
timestamp = 1698138965.979135

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "1.0.0"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/6861457415"
package_commit_hash = "af6fbd0725de411fbc8f0ff70d550d77ebf715dc"
qiskit_version = "1.0.0"
timestamp = 1699953989.808253

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/6861457415"
qiskit_version = "0.45.0"
timestamp = 1699954109.904226

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/6861457415"
qiskit_version = "0.45.0"
timestamp = 1699953322.990756

