name = "purplecaffeine"
url = "https://github.com/IceKhan13/purplecaffeine"
description = "Project is aimed to create simple general interface to track quantum experiments, store and search them in an easy way."
licence = "Apache License 2.0"
contact_info = "_No response_"
alternatives = "_No response_"
affiliations = "QAMP"
labels = [ "Productivity", "Jupyter notebook",]
created_at = 1688661859.080258
updated_at = 1688661859.080264
tier = "Community"
website = "https://icekhan13.github.io/purplecaffeine/index.html"
styles_results = []
coverages_results = []
skip_tests = false
stars = 6
[[tests_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6233532405"
package_commit_hash = "2d3632fee633413bb1883e411d1a26f76fc54e92"
qiskit_version = "0.45.0"
timestamp = 1695115227.940852

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6233532405"
qiskit_version = "0.44.1"
timestamp = 1695115324.304852

[[tests_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6233532405"
qiskit_version = "0.44.1"
timestamp = 1695114863.784412

[[tests_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6233532405"
qiskit_version = "0.44.1"
timestamp = 1695115321.070793

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6233532405"
qiskit_version = "0.44.1"
timestamp = 1695115321.070793

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6233532405"
package_commit_hash = "2d3632fee633413bb1883e411d1a26f76fc54e92"
qiskit_version = "0.45.0"
timestamp = 1695115227.940852

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6233532405"
qiskit_version = "0.44.1"
timestamp = 1695114863.784412

