name = "pyRiemann-qiskit"
url = "https://github.com/pyRiemann/pyRiemann-qiskit"
description = "Supervised machine learning based on quantum computing and Riemannian geometry. Focuses on classification of time series data."
licence = "BSD 3-Clause \"New\" or \"Revised\" license"
contact_info = "gcattan@hotmail.fr"
affiliations = "pyRiemann (https://github.com/pyRiemann)"
labels = [ "Machine learning", "Application package",]
ibm_maintained = false
stars = 21
group = "applications"
documentation = "https://pyriemann-qiskit.readthedocs.io/"
