name = "pyRiemann-qiskit"
url = "https://github.com/pyRiemann/pyRiemann-qiskit"
description = "Supervised machine learning based on quantum computing and Riemannian geometry. Focuses on classification of time series data."
licence = "BSD 3-Clause \"New\" or \"Revised\" license"
contact_info = "gcattan@hotmail.fr"
affiliations = "pyRiemann (https://github.com/pyRiemann)"
labels = [ "QML",]
group = "Application"
documentation = "https://pyriemann-qiskit.readthedocs.io/"
uuid = "fb1907a7-9af8-4c23-be0c-48841a36f2df"
badge = "https://qisk.it/e-fb1907a7"

[github]
url = "https://github.com/pyRiemann/pyRiemann-qiskit"
owner = "pyRiemann"
repo = "pyRiemann-qiskit"
stars = 31
homepage = "https://pyriemann-qiskit.readthedocs.io/"
license = "BSD 3-Clause \"New\" or \"Revised\" License"
description = "A library for machine learning and quantum programming based on pyRiemann and Qiskit projects"
estimated_contributors = 12
total_dependent_repositories = 3
total_dependent_packages = 0
last_commit = 2026-01-02T18:08:26Z
last_activity = 2026-01-28T16:33:20Z

[pypi.pyriemann-qiskit]
package_name = "pyriemann-qiskit"
version = "0.4.2"
url = "https://pypi.org/project/pyriemann-qiskit/"
requires_qiskit = "==1.*"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = false
highest_supported_qiskit_release_date = 2025-10-13T14:23:38Z
highest_supported_qiskit_version = "1.4.5"
last_month_downloads = 54
last_180_days_downloads = 325
