name = "pyRiemann-qiskit"
url = "https://github.com/pyRiemann/pyRiemann-qiskit"
description = "A library for supervised machine learning based on quantum computing and Riemannian geometry. The project is built on top of the Qiskit and pyRiemann projects and focuses on the classification of time series data."
licence = "BSD 3-Clause \"New\" or \"Revised\" license"
contact_info = "gcattan@hotmail.fr"
alternatives = "_No response_"
affiliations = "pyRiemann (https://github.com/pyRiemann)"
labels = [ "Machine learning",]
stars = 19
group = "applications"
