name = "python-open-controls"
url = "https://github.com/qctrl/python-open-controls"
description = "Q-CTRL Open Controls is an open-source Python package that makes it easy to create and deploy established error-robust quantum control protocols from the open literature"
licence = "Apache 2.0"
labels = [ "Hardware",]
created_at = 1678827878.68594
updated_at = 1678827878.68594
tier = "Community"
skip_tests = true
stars = 89
[[tests_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936781825"
package_commit_hash = "0b51250e219ca303654fc28a318c21366584ccd3"
qiskit_version = "0.45.0"
timestamp = 1692696056.391948

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936781825"
qiskit_version = "0.44.1"
timestamp = 1692696056.576225

[[tests_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936781825"
qiskit_version = "0.44.1"
timestamp = 1692696056.57623

[[tests_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936781825"
qiskit_version = "0.44.1"
timestamp = 1692696056.576234

[[styles_results]]
passed = false
style_type = "pylint"

[[coverages_results]]
passed = false
coverage_type = ""

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.37.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2617548538"
qiskit_version = "0.37.0"
timestamp = 1692696056.576248

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.37.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2617548538"
qiskit_version = "0.37.0"
timestamp = 1692696056.576252

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.37.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824121404"
qiskit_version = "0.37.1"
timestamp = 1692696056.576255

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.37.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824121404"
qiskit_version = "0.37.1"
timestamp = 1692696056.57626

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3134449307"
package_commit_hash = "672e95d089ba0e834915796f2b1d59527f3b4ef2"
qiskit_version = "0.39.0"
timestamp = 1692696056.576264

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.38.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225638751"
qiskit_version = "0.38.0"
timestamp = 1692696056.576267

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.38.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225638746"
qiskit_version = "0.38.0"
timestamp = 1692696056.576271

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368224632"
qiskit_version = "0.39.0"
timestamp = 1692696056.576274

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368224622"
qiskit_version = "0.39.0"
timestamp = 1692696056.576278

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.39.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521952236"
qiskit_version = "0.39.2"
timestamp = 1692696056.576282

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.39.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521952183"
qiskit_version = "0.39.2"
timestamp = 1692696056.576285

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937703617"
package_commit_hash = "af0b2220b75fd5cf3980576b1a31f9c4ceb9f99f"
qiskit_version = "0.40.0"
timestamp = 1692696056.576289

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.39.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937703451"
qiskit_version = "0.39.4"
timestamp = 1692696056.576293

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.39.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937703538"
qiskit_version = "0.39.4"
timestamp = 1692696056.576296

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.39.5"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994627765"
qiskit_version = "0.39.5"
timestamp = 1692696056.5763

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.39.5"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994627780"
qiskit_version = "0.39.5"
timestamp = 1692696056.576304

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052483343"
qiskit_version = "0.40.0"
timestamp = 1692696056.576307

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052483261"
qiskit_version = "0.40.0"
timestamp = 1692696056.576311

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.41.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231021941"
qiskit_version = "0.41.0"
timestamp = 1692696056.576315

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.41.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231022030"
qiskit_version = "0.41.0"
timestamp = 1692696056.576319

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.43.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414045764"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"
qiskit_version = "0.43.0"
timestamp = 1692696056.576323

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.41.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414045663"
qiskit_version = "0.41.1"
timestamp = 1692696056.576326

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.41.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414045697"
qiskit_version = "0.41.1"
timestamp = 1692696056.57633

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936781825"
qiskit_version = "0.44.1"
timestamp = 1692696056.576337

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936781825"
qiskit_version = "0.44.1"
timestamp = 1692696056.576341

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936781825"
package_commit_hash = "0b51250e219ca303654fc28a318c21366584ccd3"
qiskit_version = "0.45.0"
timestamp = 1692696056.391948

[configuration]
dependencies_files = []
extra_dependencies = [ "qiskit", "coverage", "numpy==1.*,>=1.20.0", "toml==0.*,>=0.10.0", "black==20.*,>=20.8.0.b1", "isort==5.*,>=5.7.0", "mypy==0.*,>=0.800.0", "nbval==0.*,>=0.9.5", "pre-commit==2.*,>=2.9.3", "pylint==2.*,>=2.6.0", "pylint-runner==0.*,>=0.5.4", "pytest==5.*,>=5.0.0", "qctrl-visualizer==2.*,>=2.12.2",]
tests_command = [ "pytest",]
styles_check_command = [ "pylint -rn qctrlopencontrols tests",]
coverages_check_command = [ "coverage3 -m pytest", "coverage3 report --fail-under=80",]

[configuration.language]
name = "python"
versions = [ "3.6",]
