name = "pytket-qiskit"
url = "https://github.com/CQCL/pytket-qiskit"
description = "Convert between Pytket (a Python interface for CQC tket) and Qiskit, and run Pytket circuits on IBM backends and simulators"
licence = "Apache 2.0"
labels = [ "Converter",]
ibm_maintained = false
created_at = 1661869851.523229
updated_at = 1661869851.523229
stars = 21
group = "other"
uuid = "7c80aef4-96b8-4273-8d36-7d75ca209bcd"
badge = "[![Qiskit Ecosystem](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fqiskit.github.io%2Fecosystem%2Fb%2F7c80aef4)](https://qisk.it/e)"

[github]
owner = "CQCL"
repo = "pytket-qiskit"
stars = 21

[pypi.pytket-qiskit]
project = "pytket-qiskit"
requires_qiskit = ">=2.2.0"
