name = "pytket-qiskit"
url = "https://github.com/CQCL/pytket-qiskit"
description = "an extension to Pytket (a python module for interfacing with CQC tket) that allows Pytket circuits to be run on IBM backends and simulators, as well as conversion to and from Qiskit representations."
licence = "Apache 2.0"
labels = [ "Converter",]
created_at = 1661869851.523229
updated_at = 1661869851.523229
tier = "Community"
skip_tests = false
stars = 7
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6390975723"
package_commit_hash = "19854d193aa479527e401476146e484e9a86a566"
qiskit_version = "0.45.0"
timestamp = 1696324686.765308

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6390975723"
qiskit_version = "0.44.1"
timestamp = 1696324745.820871

[[tests_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6390975723"
qiskit_version = "0.44.1"
timestamp = 1696324350.307194

[[tests_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6390975723"
qiskit_version = "0.44.1"
timestamp = 1696324743.591809

[[styles_results]]
passed = false
style_type = "pylint"

[[coverages_results]]
passed = false
coverage_type = ""

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "-"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2955002169"
qiskit_version = "-"
timestamp = 1661869851.52322

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "-"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2955002169"
package_commit_hash = "bab9d4568334d572dd14ffef3b35567bb81fbc2c"
qiskit_version = "-"
timestamp = 1661869851.523222

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "-"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2955002169"
qiskit_version = "-"
timestamp = 1661869851.522323

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6390975723"
package_commit_hash = "19854d193aa479527e401476146e484e9a86a566"
qiskit_version = "0.45.0"
timestamp = 1696324686.765308

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6390975723"
qiskit_version = "0.44.1"
timestamp = 1696324350.307194

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6390975723"
qiskit_version = "0.44.1"
timestamp = 1696324743.591809

