name = "pytket-qiskit"
url = "https://github.com/CQCL/pytket-qiskit"
description = "Convert between Pytket (a Python interface for CQC tket) and Qiskit, and run Pytket circuits on IBM backends and simulators"
licence = "Apache 2.0"
labels = []
created_at = 1661869851.523229
updated_at = 1661869851.523229
group = "Converter"
uuid = "7c80aef4-96b8-4273-8d36-7d75ca209bcd"
badge = "https://qisk.it/e-7c80aef4"

[github]
url = "https://github.com/Quantinuum/pytket-qiskit"
owner = "Quantinuum"
repo = "pytket-qiskit"
stars = 21
license = "Apache License 2.0"
description = "pytket-qiskit, extensions for pytket quantum SDK "
estimated_contributors = 20
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2025-12-22T18:29:16Z
last_activity = 2025-12-22T18:29:17Z

[pypi.pytket-qiskit]
package_name = "pytket-qiskit"
version = "0.73.0"
url = "https://pypi.org/project/pytket-qiskit/"
requires_qiskit = ">=2.2.0"
compatible_with_qiskit_v1 = false
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2025-10-22T14:47:06Z
highest_supported_qiskit_version = "2.2.2"
last_month_downloads = 58286
last_180_days_downloads = 251663
