name = "pytorch-quantum"
url = "https://github.com/mit-han-lab/pytorch-quantum"
description = "A PyTorch-centric hybrid classical-quantum dynamic neural networks framework."
licence = "Apache 2.0"
labels = [ "Machine learning",]
created_at = 1678827878.611621
updated_at = 1678827878.611622
stars = 1131
group = "applications"
