name = "pytorch-quantum"
url = "https://github.com/mit-han-lab/pytorch-quantum"
description = "A PyTorch-centric hybrid classical-quantum dynamic neural networks framework."
licence = "Apache 2.0"
labels = [ "machine learning",]
created_at = 1678827878.611621
updated_at = 1678827878.611622
tier = "Community"
skip_tests = false
stars = 764
[[tests_results]]
test_type = "development"
passed = false
package = "qiskit-terra"
package_version = "0.24.0"
terra_version = "0.24.0"
timestamp = 1678827878.602838
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414046155"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"

[[tests_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.23.2"
terra_version = "0.23.2"
timestamp = 1678827878.602844
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414046140"

[[tests_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.21.2"
terra_version = "0.21.2"
timestamp = 1678827878.60056
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414046089"

[[styles_results]]
style_type = "pylint"
passed = false

[[coverages_results]]
coverage_type = ""
passed = false

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.20.2"
terra_version = "0.20.2"
timestamp = 1678827878.611555

[[historical_test_results]]
test_type = "development"
passed = false
package = "qiskit-terra"
package_version = "0.21.0"
terra_version = "0.21.0"
timestamp = 1678827878.611561

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.20.2"
terra_version = "0.20.2"
timestamp = 1678827878.611563

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.21.0"
terra_version = "0.21.0"
timestamp = 1678827878.611566
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2617548602"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.21.0"
terra_version = "0.21.0"
timestamp = 1678827878.611568
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2617548602"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.21.1"
terra_version = "0.21.1"
timestamp = 1678827878.61157
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824121448"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.21.1"
terra_version = "0.21.1"
timestamp = 1678827878.611572
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824121448"

[[historical_test_results]]
test_type = "development"
passed = false
package = "qiskit-terra"
package_version = "0.22.0"
terra_version = "0.22.0"
timestamp = 1678827878.611577
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3180920482"
package_commit_hash = "53e215c31cf3aea51a623dc22883ac92fe74d0b9"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.21.2"
terra_version = "0.21.2"
timestamp = 1678827878.611579
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225638971"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.18.3"
terra_version = "0.18.3"
timestamp = 1678827878.611581
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3319733310"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.22.0"
terra_version = "0.22.0"
timestamp = 1678827878.611584
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368224766"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.22.0"
terra_version = "0.22.0"
timestamp = 1678827878.611586
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368224775"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.22.2"
terra_version = "0.22.2"
timestamp = 1678827878.611588
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521952548"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.22.2"
terra_version = "0.22.2"
timestamp = 1678827878.61159
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521952575"

[[historical_test_results]]
test_type = "development"
passed = false
package = "qiskit-terra"
package_version = "0.23.0"
terra_version = "0.23.0"
timestamp = 1678827878.611593
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937704035"
package_commit_hash = "af0b2220b75fd5cf3980576b1a31f9c4ceb9f99f"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.22.3"
terra_version = "0.22.3"
timestamp = 1678827878.611595
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937703995"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.22.3"
terra_version = "0.22.3"
timestamp = 1678827878.611597
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937703922"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.22.4"
terra_version = "0.22.4"
timestamp = 1678827878.611599
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994628138"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.22.4"
terra_version = "0.22.4"
timestamp = 1678827878.611601
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994628139"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.23.0"
terra_version = "0.23.0"
timestamp = 1678827878.611604
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052483696"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.23.0"
terra_version = "0.23.0"
timestamp = 1678827878.611606
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052483765"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.23.1"
terra_version = "0.23.1"
timestamp = 1678827878.611608
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231022339"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.23.1"
terra_version = "0.23.1"
timestamp = 1678827878.61161
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231022382"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.23.2"
terra_version = "0.23.2"
timestamp = 1678827878.611612
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414046140"

[[historical_test_results]]
test_type = "development"
passed = false
package = "qiskit-terra"
package_version = "0.24.0"
terra_version = "0.24.0"
timestamp = 1678827878.611615
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414046155"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.21.2"
terra_version = "0.21.2"
timestamp = 1678827878.60056
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414046089"

[configuration]
dependencies_files = [ "requirements.txt",]
extra_dependencies = [ "qiskit", "coverage", "pylint",]
tests_command = [ "pytest",]
styles_check_command = [ "pylint -rn torchquantum test",]
coverages_check_command = [ "coverage3 -m pytest", "coverage3 report --fail-under=80",]

[configuration.language]
name = "python"
versions = [ "3.6",]
