name = "q-kernel-ops"
url = "https://github.com/Travis-S-IBM/q-kernel-ops"
description = "Code base on the paper Kernel Matrix Completion for Offline Quantum-Enhanced Machine Learning [2112.08449](https://arxiv.org/abs/2112.08449)."
licence = "Apache 2.0"
contact_info = "### Email"
alternatives = "### Alternatives"
labels = [ "Advocate mentorship project", "Machine learning",]
created_at = 1678827878.663275
updated_at = 1678827878.663276
styles_results = []
coverages_results = []
tier = "Community"
skip_tests = false
stars = 3
[[tests_results]]
test_type = "development"
passed = false
package = "qiskit-terra"
package_version = "unknown"
terra_version = "unknown"
timestamp = 1678827878.663244
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231022887"
package_commit_hash = "4e3b283157b43687db4260cee6decf17fbb37608"

[[tests_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "unknown"
terra_version = "unknown"
timestamp = 1678827878.663249
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414046565"

[[tests_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "unknown"
terra_version = "unknown"
timestamp = 1678827878.661149
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414046492"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "-"
terra_version = "-"
timestamp = 1678827878.663257
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3039654390"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "-"
terra_version = "-"
timestamp = 1678827878.66326
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3039654418"

[[historical_test_results]]
test_type = "development"
passed = false
package = "qiskit-terra"
package_version = "-"
terra_version = "-"
timestamp = 1678827878.663262
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3039654437"
package_commit_hash = "055fe0f9c9ca3b3b994f68ba2c7647763a29f63b"

[[historical_test_results]]
test_type = "development"
passed = false
package = "qiskit-terra"
package_version = "unknown"
terra_version = "unknown"
timestamp = 1678827878.663267
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231022887"
package_commit_hash = "4e3b283157b43687db4260cee6decf17fbb37608"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "unknown"
terra_version = "unknown"
timestamp = 1678827878.663269
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414046565"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "unknown"
terra_version = "unknown"
timestamp = 1678827878.661149
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414046492"

