name = "q-kernel-ops"
url = "https://github.com/Travis-S-IBM/q-kernel-ops"
description = "Code base on the paper Kernel Matrix Completion for Offline Quantum-Enhanced Machine Learning [2112.08449](https://arxiv.org/abs/2112.08449)."
licence = "Apache 2.0"
contact_info = "### Email"
alternatives = "### Alternatives"
labels = [ "Advocate mentorship project", "Machine learning",]
created_at = 1678827878.663275
updated_at = 1678827878.663276
tier = "Community"
styles_results = []
coverages_results = []
skip_tests = false
stars = 3
group = "other"
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = ""
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7016431201"
package_commit_hash = "e91947e1b55f6e661c683fba72ab66c5f92d3aec"
qiskit_version = ""
timestamp = 1701162620.658721

[[tests_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7016431201"
qiskit_version = "0.45.0"
timestamp = 1701162276.103855

[[tests_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7016431201"
qiskit_version = "0.45.0"
timestamp = 1701162656.452775

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "-"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3039654390"
qiskit_version = "-"
timestamp = 1692695539.680839

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "-"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3039654418"
qiskit_version = "-"
timestamp = 1692695539.680842

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "-"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3039654437"
package_commit_hash = "055fe0f9c9ca3b3b994f68ba2c7647763a29f63b"
qiskit_version = "-"
timestamp = 1692695539.680846

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6310545107"
qiskit_version = "unknown"
timestamp = 1695719491.346655

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6310545107"
package_commit_hash = "6e80e89e18da2691a86d4e2050db2e5479043b16"
qiskit_version = "unknown"
timestamp = 1695719489.109084

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6310545107"
qiskit_version = "unknown"
timestamp = 1695719486.283348

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6545042171"
package_commit_hash = "62467839e8d4e263465c42118414e6e5eca3c776"
qiskit_version = "0.45.0"
timestamp = 1697535055.034608

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.44.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624759887"
qiskit_version = "0.44.2"
timestamp = 1698139503.322323

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "1.0.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624759887"
package_commit_hash = "fe3bffbc85a4fb57dc62ba04fa7f11bcefb5d75f"
qiskit_version = "1.0.0"
timestamp = 1698139905.157739

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.44.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624759887"
qiskit_version = "0.44.2"
timestamp = 1698139949.288386

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7016431201"
qiskit_version = "0.45.0"
timestamp = 1701162276.103855

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = ""
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7016431201"
package_commit_hash = "e91947e1b55f6e661c683fba72ab66c5f92d3aec"
qiskit_version = ""
timestamp = 1701162620.658721

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7016431201"
qiskit_version = "0.45.0"
timestamp = 1701162656.452775

