name = "Qamomile"
url = "https://github.com/Jij-Inc/Qamomile"
description = "Model constrained optimization problems using an algebraic modeler and convert them for quantum optimization algorithms."
licence = "Apache License 2.0"
contact_info = "h.matsuyama@j-ij.com"
affiliations = "Jij Inc."
labels = [ "optimization",]
group = "SDK"
documentation = "https://jij-inc.github.io/Qamomile/"
uuid = "50cd2126-dc2c-45f8-b3e7-fb1d132f7d02"
badge = "[![Qiskit Ecosystem](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fqiskit.github.io%2Fecosystem%2Fb%2F50cd2126)](https://qisk.it/e)"

[github]
url = "https://github.com/Jij-Inc/Qamomile"
owner = "Jij-Inc"
repo = "Qamomile"
stars = 13
license = "Apache License 2.0"
estimated_contributors = 15
total_dependent_repositories = 2
total_dependent_packages = 1
last_commit = 2025-12-04T08:38:59Z
last_activity = 2025-12-04T08:38:59Z

[pypi.qamomile]
package_name = "qamomile"
version = "0.8.0"
url = "https://pypi.org/project/qamomile/"
requires_qiskit = "<3.0.0,>=2.1.0"
compatible_with_qiskit_v1 = false
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2025-10-22T14:47:06Z
highest_supported_qiskit_version = "2.2.2"
last_month_downloads = 543
last_180_days_downloads = 2742
