name = "Qamomile"
url = "https://github.com/Jij-Inc/Qamomile"
description = "Model constrained optimization problems using an algebraic modeler and convert them for quantum optimization algorithms."
licence = "Apache License 2.0"
contact_info = "h.matsuyama@j-ij.com"
affiliations = "Jij Inc."
labels = [ "Algorithms", "Applications", "Optimization", "Software development kit",]
ibm_maintained = false
stars = 12
group = "applications"
documentation = "https://jij-inc.github.io/Qamomile/"
uuid = "50cd2126-dc2c-45f8-b3e7-fb1d132f7d02"
badge = "[![Qiskit Ecosystem](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fqiskit.github.io%2Fecosystem%2Fb%2F50cd2126)](https://qisk.it/e)"

[github]
owner = "Jij-Inc"
repo = "Qamomile"
stars = 12
