name = "QASM-Runner-Qiskit-Platform"
url = "https://github.com/TownsendBrown/QASM-Runner-Qiskit-Platform"
description = "Python-based CLI tool for executing OpenQASM 2.0 circuits on both real IBM Quantum hardware and local simulators. Includes support for multi-files, configurable shot count, backend selection, JSON output, and circuit diagram generation."
contact_info = "stiofancondon@outlook.com"
labels = [ "optimization",]
ibm_maintained = false
website = "https://github.com/TownsendBrown/QASM-Runner-Qiskit-Platform"
group = "applications"
reference_paper = "https://_no response_"
documentation = "https://github.com/TownsendBrown/QASM-Runner-Qiskit-Platform/blob/main/README.md"
uuid = "5b05d5a3-26c6-4487-91cc-3ca3aeaf0d6b"
badge = "[![Qiskit Ecosystem](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fqiskit.github.io%2Fecosystem%2Fb%2F5b05d5a3)](https://qisk.it/e)"

[github]
owner = "TownsendBrown"
repo = "QASM-Runner-Qiskit-Platform"
