name = "QASM Runner for IBM platforms"
url = "https://github.com/TownsendBrown/QASM-Runner-Qiskit-Platform"
description = "A command-line tool for executing OpenQASM 2.0 files on IBM Quantum hardware and simulators."
contact_info = "stiofancondon@outlook.com"
labels = [ "other",]
ibm_maintained = false
group = "applications"
uuid = "5b05d5a3-26c6-4487-91cc-3ca3aeaf0d6b"
badge = "[![Qiskit Ecosystem](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fqiskit.github.io%2Fecosystem%2Fb%2F5b05d5a3)](https://qisk.it/e)"

[github]
owner = "TownsendBrown"
repo = "QASM-Runner-Qiskit-Platform"
