name = "qBraid"
url = "https://github.com/qBraid/qBraid"
description = "The qBraid-SDK is a Python toolkit for cross-framework abstraction, transpilation, and execution of quantum programs."
licence = "GNU General Public License (GPL)"
contact_info = "ryanhill@qbraid.com"
alternatives = "There are some alternatives to individual modules within the qBraid-SDK e.g. to execute a Qiskit circuit on an AWS device, you could use the qiskit-braket-provider. However, there aren't any other existing projects that support the same matrix of quantum program types and backends through a single, unified interface."
affiliations = "qBraid Co."
labels = [ "Circuit building tool", "Converter", "Software development kit",]
ibm_maintained = false
created_at = 1690263743.561744
updated_at = 1690263743.56175
website = "https://qbraid.com"
stars = 73
group = "other"
uuid = "c5b19e1a-cdde-4f31-b9d2-62c7709da809"
