name = "qBraid"
url = "https://github.com/qBraid/qBraid"
description = "The qBraid-SDK is a Python toolkit for cross-framework abstraction, transpilation, and execution of quantum programs."
licence = "GNU General Public License (GPL)"
contact_info = "ryanhill@qbraid.com"
affiliations = "qBraid Co."
labels = [ "Circuit building tool", "Converter", "Software development kit",]
ibm_maintained = false
created_at = 1690263743.561744
updated_at = 1690263743.56175
website = "https://qbraid.com"
stars = 102
group = "other"
uuid = "c5b19e1a-cdde-4f31-b9d2-62c7709da809"
badge = "[![Qiskit Ecosystem](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fqiskit.github.io%2Fecosystem%2Fb%2Fc5b19e1a)](https://qisk.it/e)"

[github]
url = "https://github.com/qBraid/qBraid"
owner = "qBraid"
repo = "qBraid"
stars = 102
last_commit = 2025-11-06T15:55:05Z

[pypi.qbraid]
package_name = "qbraid"
version = "0.10.0"
url = "https://pypi.org/project/qbraid/"
requires_qiskit = "<3.0,>=1.0"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2025-10-22T14:47:06Z
highest_supported_qiskit_version = "2.2.2"
