name = "qBraid"
url = "https://github.com/qBraid/qBraid"
description = "The qBraid-SDK is a Python toolkit for cross-framework abstraction, transpilation, and execution of quantum programs."
licence = "GNU General Public License (GPL)"
contact_info = "ryanhill@qbraid.com"
alternatives = "There are some alternatives to individual modules within the qBraid-SDK e.g. to execute a Qiskit circuit on an AWS device, you could use the qiskit-braket-provider. However, there aren't any other existing projects that support the same matrix of quantum program types and backends through a single, unified interface."
affiliations = "qBraid Co."
labels = [ "Circuit", "OpenQASM", "Converter", "Software development kit",]
created_at = 1690263743.561744
updated_at = 1690263743.56175
tier = "Community"
website = "https://qbraid.com"
styles_results = []
coverages_results = []
skip_tests = false
stars = 37
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936779503"
package_commit_hash = "0b51250e219ca303654fc28a318c21366584ccd3"
qiskit_version = "0.45.0"
timestamp = 1692696381.802871

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5924783548"
qiskit_version = "0.44.1"
timestamp = 1692696381.802882

[[tests_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936779503"
qiskit_version = "0.44.1"
timestamp = 1692696381.802886

[[tests_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936779503"
qiskit_version = "0.44.1"
timestamp = 1692696381.631434

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936779503"
package_commit_hash = "0b51250e219ca303654fc28a318c21366584ccd3"
qiskit_version = "0.45.0"
timestamp = 1692696381.8029

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936779503"
qiskit_version = "0.44.1"
timestamp = 1692696381.802904

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936779503"
qiskit_version = "0.44.1"
timestamp = 1692696381.631434

