name = "Qclib"
url = "https://github.com/qclib/qclib"
description = "A quantum computing library implemented using Qiskit. The focus of Qclib is on preparing quantum states, but it is not limited to that."
licence = "Apache License 2.0"
labels = [ "Algorithms", "Circuit building tool", "Optimization", "Paper implementation",]
group = "other"
uuid = "727120b2-7559-453e-beb3-0ab33fb60a4a"
badge = "[![Qiskit Ecosystem](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fqiskit.github.io%2Fecosystem%2Fb%2F727120b2)](https://qisk.it/e)"

[github]
url = "https://github.com/qclib/qclib"
owner = "qclib"
repo = "qclib"
stars = 44
license = "Apache License 2.0"
description = "Qclib is a quantum computing library implemented using qiskit. The focus of qclib is on preparing quantum states, but it is not lim..."
total_dependent_repositories = 14
total_dependent_packages = 1
last_commit = 2025-08-07T13:50:05Z

[pypi.qclib]
package_name = "qclib"
version = "0.1.15"
url = "https://pypi.org/project/qclib/"
requires_qiskit = ">=1.0.0"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2025-10-22T14:47:06Z
highest_supported_qiskit_version = "2.2.2"
last_month_downloads = 596
last_180_days_downloads = 3252
