name = "Qclib"
url = "https://github.com/qclib/qclib"
description = "A quantum computing library implemented using Qiskit. The focus of Qclib is on preparing quantum states, but it is not limited to that."
licence = "Apache License 2.0"
labels = [ "Algorithms", "Circuit building tool", "Optimization", "Paper implementation",]
ibm_maintained = false
stars = 44
group = "other"
uuid = "727120b2-7559-453e-beb3-0ab33fb60a4a"
badge = "[![Qiskit Ecosystem](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fqiskit.github.io%2Fecosystem%2Fb%2F727120b2)](https://qisk.it/e)"

[github]
owner = "qclib"
repo = "qclib"
stars = 44
last_commit = "2025-08-07T13:50:05+00:00"

[pypi.qclib]
package_name = "qclib"
version = "0.1.15"
requires_qiskit = ">=1.0.0"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
