name = "qdao"
url = "https://github.com/Zhaoyilunnn/qdao"
description = "A lightweight framework to enable configurable memory consumption when simulating large quantum circuits."
licence = "Apache License 2.0"
contact_info = "zyilun8@gmail.com"
affiliations = "Institute of Computing Technology, Chinese Academy of Sciences."
labels = [ "Circuit simulator",]
ibm_maintained = false
stars = 13
group = "other"
uuid = "c39a1176-0a10-41c5-9961-f6f4f5da0c6c"
