name = "qdao"
url = "https://github.com/Zhaoyilunnn/qdao"
description = "A lightweight framework to enable configurable memory consumption when simulating large quantum circuits."
licence = "Apache License 2.0"
contact_info = "zyilun8@gmail.com"
affiliations = "Institute of Computing Technology, Chinese Academy of Sciences."
labels = []
group = "Circuit simulator"
uuid = "c39a1176-0a10-41c5-9961-f6f4f5da0c6c"
badge = "https://qisk.it/e-c39a1176"

[github]
url = "https://github.com/Zhaoyilunnn/qdao"
owner = "Zhaoyilunnn"
repo = "qdao"
stars = 15
license = "Apache License 2.0"
description = "Full State Quantum Circuit Simulation Beyond Memory Limit"
estimated_contributors = 6
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2024-08-05T01:26:18Z
