name = "QELM"
url = "https://github.com/R-D-BioTech-Alaska/Qelm"
description = "A quantum-powered NLP project using Qiskit to create ultra-compact, efficient LLMs, running instantly on small devices without data centers."
licence = "MIT license"
contact_info = "contact@rdbiotechalaska.com"
affiliations = "R&D BioTech Alaska"
labels = [ "Machine learning",]
ibm_maintained = false
group = "applications"
uuid = "8b3685bb-451f-4d3d-abac-61a5ce48708f"
