name = "QELM"
url = "https://github.com/R-D-BioTech-Alaska/Qelm"
description = "A quantum-powered NLP project. Creates ultra-compact, efficient LLMs that run instantly on small devices without data centers."
licence = "MIT license"
contact_info = "contact@rdbiotechalaska.com"
affiliations = "R&D BioTech Alaska"
labels = [ "QML", "circuit building", "research",]
group = "Application"
reference_paper = "https://doi.org/10.13140/RG.2.2.11844.90243"
documentation = "https://github.com/R-D-BioTech-Alaska/Qelm/tree/main/Documentation"
uuid = "8b3685bb-451f-4d3d-abac-61a5ce48708f"
badge = "[![Qiskit Ecosystem](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fqiskit.github.io%2Fecosystem%2Fb%2F8b3685bb)](https://qisk.it/e)"

[github]
url = "https://github.com/R-D-BioTech-Alaska/Qelm"
owner = "R-D-BioTech-Alaska"
repo = "Qelm"
stars = 25
homepage = "https://www.Qelm.org"
license = "Other"
description = "Qelm - Quantum Enhanced Language Model"
estimated_contributors = 3
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2025-12-04T02:55:49Z
last_activity = 2025-12-04T02:55:50Z

[pypi.qelm]
package_name = "qelm"
version = "0.1.4"
url = "https://pypi.org/project/qelm/"
requires_qiskit = ">=1.0"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2025-10-22T14:47:06Z
highest_supported_qiskit_version = "2.2.2"
last_month_downloads = 21
last_180_days_downloads = 11970
