name = "qiskit-machine-learning"
url = "https://github.com/qiskit-community/qiskit-machine-learning"
description = "The Machine Learning package contains sample datasets and quantum ML algorithms."
licence = "Apache 2.0"
labels = [ "Algorithms", "Machine learning",]
created_at = 1636403010.012954
updated_at = 1636403010.012956
tier = "Community"
website = "https://qiskit.org/ecosystem/machine-learning"
tests_results = []
styles_results = []
coverages_results = []
skip_tests = true
historical_test_results = []
stars = 501
