name = "qiskit-qubit-reuse"
url = "https://github.com/qiskit-community/qiskit-qubit-reuse"
description = "A Qiskit transpiler stage plugin that reuses qubits through mid-circuit measurement and reset."
licence = "Apache License 2.0"
affiliations = "IBM"
labels = [ "Paper implementation", "Transpiler plugin",]
group = "transpiler_plugin"
uuid = "c9369922-7e0d-4b77-b00a-329472b57a34"
badge = "[![Qiskit Ecosystem](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fqiskit.github.io%2Fecosystem%2Fb%2Fc9369922)](https://qisk.it/e)"

[github]
url = "https://github.com/qiskit-community/qiskit-qubit-reuse"
owner = "qiskit-community"
repo = "qiskit-qubit-reuse"
stars = 26
license = "Apache License 2.0"
description = "A Qiskit transpiler stage plugin to enable qubit reuse via mid-circuit measurement and reset."
last_commit = 2025-07-03T17:08:32Z

[pypi.qiskit-qubit-reuse]
package_name = "qiskit-qubit-reuse"
version = "0.0.2"
url = "https://pypi.org/project/qiskit-qubit-reuse/"
requires_qiskit = ">=0.43.0"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2025-10-22T14:47:06Z
highest_supported_qiskit_version = "2.2.2"
