name = "Qiskit Machine Learning"
url = "https://github.com/qiskit-community/qiskit-machine-learning"
description = "Use flexible building blocks, such as quantum kernels and neural networks, to create quantum machine learning algorithms."
licence = "Apache 2.0"
labels = [ "Algorithms", "Machine learning", "Applications",]
created_at = 1636403010.012954
updated_at = 1636403010.012956
group = "applications"
documentation = "https://qiskit-community.github.io/qiskit-machine-learning/"
uuid = "18986ebc-e138-4998-8c52-16359961af0a"
badge = "[![Qiskit Ecosystem](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fqiskit.github.io%2Fecosystem%2Fb%2F18986ebc)](https://qisk.it/e)"

[github]
url = "https://github.com/qiskit-community/qiskit-machine-learning"
owner = "qiskit-community"
repo = "qiskit-machine-learning"
stars = 883
homepage = "https://qiskit-community.github.io/qiskit-machine-learning/"
license = "Apache License 2.0"
description = "Quantum Machine Learning"
total_dependent_repositories = 517
total_dependent_packages = 21
last_commit = 2025-11-10T17:37:14Z

[pypi.qiskit-machine-learning]
package_name = "qiskit-machine-learning"
version = "0.8.4"
url = "https://pypi.org/project/qiskit-machine-learning/"
requires_qiskit = "<2.0,>=1.0"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = false
highest_supported_qiskit_release_date = 2025-10-13T14:23:38Z
highest_supported_qiskit_version = "1.4.5"
