name = "qiskit-addon-mpf"
url = "https://github.com/Qiskit/qiskit-addon-mpf"
description = "Reduce the Trotter error of Hamiltonian dynamics with multi-product formulas (MPF)."
licence = "Apache License 2.0"
contact_info = "oss@zurich.ibm.com"
labels = [ "circuit building", "physics",]
ibm_maintained = true
created_at = 1758737407.8760931
group = "Qiskit addon"
documentation = "https://qiskit.github.io/qiskit-addon-mpf/"
uuid = "99eb5c40-00ee-439c-971e-e3e2a523c83a"
badge = "https://qisk.it/e-99eb5c40"

[github]
url = "https://github.com/Qiskit/qiskit-addon-mpf"
owner = "Qiskit"
repo = "qiskit-addon-mpf"
stars = 33
homepage = "https://qiskit.github.io/qiskit-addon-mpf/"
license = "Apache License 2.0"
description = "Reducing the Trotter error of Hamiltonian dynamics with multi-product formulas"
estimated_contributors = 13
total_dependent_repositories = 6
total_dependent_packages = 0
last_commit = 2026-01-01T02:07:23Z
last_activity = 2026-01-01T02:11:51Z

[pypi.qiskit-addon-mpf]
package_name = "qiskit-addon-mpf"
version = "0.3.0"
url = "https://pypi.org/project/qiskit-addon-mpf/"
requires_qiskit = "<3,>=1.2"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2025-10-22T14:47:06Z
highest_supported_qiskit_version = "2.2.2"
last_month_downloads = 774
last_180_days_downloads = 5423
