name = "Qiskit4Java"
url = "https://github.com/gnietof/QREST"
description = "Java client for submitting OpenQASM 3 programs to IBM Quantum backends."
contact_info = "genaro@es.ibm.com"
labels = ["Java", "openqasm"]
group = "SDK"
packages = []
uuid = "62adafb3-291b-470c-95e1-40f4d7ad8a97"

[github]
url = "https://github.com/gnietof/QREST"
owner = "gnietof"
repo = "QREST"
stars = 0
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2026-01-16T01:49:36Z
last_activity = 2026-01-16T01:49:37Z
