name = "Qiskit IonQ Provider"
url = "https://github.com/qiskit-community/qiskit-ionq"
description = "This project contains a provider that allows access to IonQ ion trap quantum systems."
licence = "Apache 2.0"
contact_info = ""
labels = [ "cloud service",]
created_at = 1670427446.011674
updated_at = 1670427446.011675
group = "Compute provider"
uuid = "9dec814e-feb8-49c2-818a-f6a2503d38c5"
badge = "https://qisk.it/e-9dec814e"

[github]
url = "https://github.com/qiskit-community/qiskit-ionq"
owner = "qiskit-community"
repo = "qiskit-ionq"
stars = 54
homepage = "https://qiskit-community.github.io/qiskit-ionq/"
license = "Apache License 2.0"
description = "Qiskit provider for IonQ backends"
estimated_contributors = 16
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2025-12-08T17:59:08Z
last_activity = 2026-01-15T02:07:07Z

[pypi.qiskit-ionq]
package_name = "qiskit-ionq"
version = "1.0.2"
url = "https://pypi.org/project/qiskit-ionq/"
requires_qiskit = ">=2.0.0"
compatible_with_qiskit_v1 = false
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2025-10-22T14:47:06Z
highest_supported_qiskit_version = "2.2.2"
last_month_downloads = 49706
last_180_days_downloads = 238344
