name = "Qiskit QEC"
url = "https://github.com/qiskit-community/qiskit-qec"
description = "For quantum error correction developers, experimentalists, and theorists."
licence = "Apache 2.0"
labels = [ "error correction",]
created_at = 1662992390.122591
updated_at = 1662992390.122597
group = "Other"
uuid = "f00eb2fa-f4f1-4e97-8e59-3013e424e0f5"
badge = "https://qisk.it/e-f00eb2fa"

[github]
url = "https://github.com/qiskit-community/qiskit-qec"
owner = "qiskit-community"
repo = "qiskit-qec"
stars = 111
homepage = "https://qiskit-community.github.io/qiskit-qec/"
license = "Apache License 2.0"
description = "Qiskit quantum error correction framework"
estimated_contributors = 20
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2025-01-27T10:23:37Z
last_activity = 2026-02-01T01:12:42Z
