name = "qiskit-qec"
url = "https://github.com/qiskit-community/qiskit-qec"
description = "Framework for Quantum Error Correction is an open-source framework for developers, experimentalist and theorists of Quantum Error Correction (QEC)."
licence = "Apache 2.0"
contact_info = "_No response_"
alternatives = "_No response_"
affiliations = "_No response_"
labels = [ "algorithms", "QEC", "circuit",]
created_at = 1662992390.122591
updated_at = 1662992390.122597
tier = "Extensions"
tests_results = []
styles_results = []
coverages_results = []
skip_tests = true
historical_test_results = []
