name = "Qiskit QEC"
url = "https://github.com/qiskit-community/qiskit-qec"
description = "For quantum error correction developers, experimentalists, and theorists."
licence = "Apache 2.0"
labels = [ "Algorithms", "Circuit building tool", "Error correction",]
created_at = 1662992390.122591
updated_at = 1662992390.122597
group = "other"
uuid = "f00eb2fa-f4f1-4e97-8e59-3013e424e0f5"
badge = "[![Qiskit Ecosystem](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fqiskit.github.io%2Fecosystem%2Fb%2Ff00eb2fa)](https://qisk.it/e)"

[github]
url = "https://github.com/qiskit-community/qiskit-qec"
owner = "qiskit-community"
repo = "qiskit-qec"
stars = 108
homepage = "https://qiskit-community.github.io/qiskit-qec/"
license = "Apache License 2.0"
description = "Qiskit quantum error correction framework"
last_commit = 2025-01-27T10:23:37Z
