name = "Qiskit Experiments"
url = "https://github.com/qiskit-community/qiskit-experiments"
description = "Run characterizing, calibrating, and benchmarking experiments."
licence = "Apache 2.0"
labels = [ "Algorithms",]
ibm_maintained = true
created_at = 1661785302.25299
updated_at = 1661785302.25299
group = "other"
documentation = "https://qiskit-community.github.io/qiskit-experiments/"
uuid = "6e94a8b7-65a7-4fee-b71e-25191203fa49"
badge = "[![Qiskit Ecosystem](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fqiskit.github.io%2Fecosystem%2Fb%2F6e94a8b7)](https://qisk.it/e)"

[github]
url = "https://github.com/qiskit-community/qiskit-experiments"
owner = "qiskit-community"
repo = "qiskit-experiments"
stars = 184
homepage = "https://qiskit-community.github.io/qiskit-experiments/"
license = "Apache License 2.0"
description = "Qiskit Experiments"
last_commit = 2025-11-05T18:38:39Z

[pypi.qiskit-experiments]
package_name = "qiskit-experiments"
version = "0.13.0"
url = "https://pypi.org/project/qiskit-experiments/"
requires_qiskit = ">=1.3"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2025-10-22T14:47:06Z
highest_supported_qiskit_version = "2.2.2"
