name = "Qiskit Scaleway"
url = "https://github.com/scaleway/qiskit-scaleway"
description = "A Python package to run quantum circuits on Scaleway infrastructure, providing access to simulators on powerful hardware (CPU and GPU)."
licence = "Apache License 2.0"
contact_info = "lmerbouche@scaleway.com"
labels = [ "Circuit simulator", "Compute provider",]
ibm_maintained = false
website = "https://www.scaleway.com"
stars = 4
group = "provider"
documentation = "https://pypi.org/project/qiskit-scaleway/"
uuid = "a942dc5d-c715-4b23-a9d6-4f2c3ee1d70b"
