name = "qiskit-nature"
url = "https://github.com/qiskit-community/qiskit-nature"
description = "Qiskit Nature allows researchers and developers in different areas of natural sciences (including physics, chemistry, material science and biology) to model and solve domain-specific problems using quantum simulations"
licence = "Apache 2.0"
labels = [ "Algorithms", "Physics", "Chemistry",]
created_at = 1636403009.16708
updated_at = 1636403009.167082
tier = "Community"
website = "https://qiskit.org/ecosystem/nature"
tests_results = []
styles_results = []
coverages_results = []
skip_tests = true
historical_test_results = []
stars = 246
