name = "Qiskit Dynamics"
url = "https://github.com/Qiskit-Extensions/qiskit-dynamics"
description = "Build, transform, and solve time-dependent quantum systems."
licence = "Apache 2.0"
labels = [ "Physics", "Application package",]
ibm_maintained = true
created_at = 1628883441.121108
updated_at = 1628883441.121111
stars = 97
group = "applications"
documentation = "https://qiskit.org/ecosystem/dynamics/"
uuid = "4bf110b1-5e54-4540-8338-d7d0fb7801d0"
