name = "Qiskit Finance"
url = "https://github.com/qiskit-community/qiskit-finance"
description = "Includes uncertainty components for stock/securities problems, Ising translators for portfolio optimizations, and data providers."
licence = "Apache 2.0"
labels = [ "Algorithms", "Finance", "Application package",]
ibm_maintained = false
created_at = 1636403009.368607
updated_at = 1636403009.368609
stars = 249
group = "applications"
documentation = "https://qiskit-community.github.io/qiskit-finance/"
uuid = "8ebeec26-5043-4423-9cdc-bfa92bd4ad63"
