name = "Qiskit Scaleway"
url = "https://github.com/scaleway/qiskit-scaleway"
description = "A Python package to run quantum circuits on Scaleway infrastructure, providing access to simulators on powerful hardware (CPU and GPU)."
licence = "Apache License 2.0"
contact_info = "lmerbouche@scaleway.com"
labels = [ "Circuit simulator", "Compute provider", "Cloud service",]
ibm_maintained = false
website = "https://www.scaleway.com"
stars = 6
group = "provider"
documentation = "https://pypi.org/project/qiskit-scaleway/"
uuid = "a942dc5d-c715-4b23-a9d6-4f2c3ee1d70b"
badge = "[![Qiskit Ecosystem](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fqiskit.github.io%2Fecosystem%2Fb%2Fa942dc5d)](https://qisk.it/e)"

[github]
owner = "scaleway"
repo = "qiskit-scaleway"
stars = 6
last_commit = "2025-10-27T13:18:13+00:00"

[pypi.qiskit-scaleway]
package_name = "qiskit-scaleway"
version = "0.3.0"
requires_qiskit = "~=2.1"
compatible_with_qiskit_v1 = false
compatible_with_qiskit_v2 = true
release_date_of_the_last_qiskit_version_supported = 2025-10-22T14:47:06.921570Z
last_qiskit_version_supported = "2.2.2"
