name = "qiskit-metal"
url = "https://github.com/qiskit-community/qiskit-metal"
description = "Qiskit Metal is an open-source framework for engineers and scientists to design superconducting quantum devices with ease."
licence = "Apache 2.0"
labels = [ "Hardware",]
created_at = 1628883441.119202
updated_at = 1628883441.119205
tier = "Community"
tests_results = []
styles_results = []
coverages_results = []
skip_tests = true
historical_test_results = []
stars = 244
