name = "Qiskit Experiments"
url = "https://github.com/Qiskit-Extensions/qiskit-experiments"
description = "Run characterizing, calibrating, and benchmarking experiments."
licence = "Apache 2.0"
labels = [ "Algorithms",]
ibm_maintained = true
created_at = 1661785302.25299
updated_at = 1661785302.25299
stars = 151
group = "other"
documentation = "https://qiskit.org/ecosystem/experiments/"
uuid = "6e94a8b7-65a7-4fee-b71e-25191203fa49"
