name = "Qiskit Timeline Debugger"
url = "https://github.com/TheGupta2012/qiskit-timeline-debugger"
description = "A Jupyter widget to highlight the actions of the qiskit transpiler. Simply replace the transpile function with the debugger to see circuit evolution, property set changes, logs, docs, and more."
licence = "Apache 2.0"
labels = [ "Visualization", "Productivity", "Transpiler plugin",]
created_at = 1674387065.334913
updated_at = 1709296915.670992
stars = 13
group = "other"
