name = "Qiskit Nature PySCF"
url = "https://github.com/qiskit-community/qiskit-nature-pyscf"
description = "A third-party integration plugin of Qiskit Nature and PySCF."
licence = "Apache License 2.0"
labels = [ "Chemistry",]
created_at = 1678827878.723733
updated_at = 1678827878.723734
stars = 17
group = "applications"
documentation = "https://qiskit-community.github.io/qiskit-nature-pyscf/"
