name = "Qiskit Nature"
url = "https://github.com/qiskit-community/qiskit-nature"
description = "Model and solve problems in physics, chemistry, material science, and biology by using quantum simulations."
licence = "Apache 2.0"
labels = [ "Algorithms", "Physics", "Chemistry",]
created_at = 1636403009.16708
updated_at = 1636403009.167082
tier = "Community"
tests_results = []
styles_results = []
coverages_results = []
skip_tests = true
historical_test_results = []
stars = 257
group = "applications"
documentation = "https://qiskit.org/ecosystem/nature"
