name = "Qiskit Experiments"
url = "https://github.com/qiskit-community/qiskit-experiments"
description = "Run characterizing, calibrating, and benchmarking quantum experiments."
licence = "Apache 2.0"
labels = []
ibm_maintained = true
created_at = 1661785302.25299
updated_at = 1661785302.25299
group = "Other"
reference_paper = "https://doi.org/10.21105/joss.05329"
documentation = "https://qiskit-community.github.io/qiskit-experiments/"
uuid = "6e94a8b7-65a7-4fee-b71e-25191203fa49"
badge = "https://qisk.it/e-6e94a8b7"

[github]
url = "https://github.com/qiskit-community/qiskit-experiments"
owner = "qiskit-community"
repo = "qiskit-experiments"
stars = 188
homepage = "https://qiskit-community.github.io/qiskit-experiments/"
license = "Apache License 2.0"
description = "Qiskit Experiments"
total_dependent_repositories = 176
total_dependent_packages = 13
last_commit = 2025-12-15T16:28:50Z
last_activity = 2025-12-19T03:35:36Z

[pypi.qiskit-experiments]
package_name = "qiskit-experiments"
version = "0.13.0"
url = "https://pypi.org/project/qiskit-experiments/"
requires_qiskit = ">=1.3"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2025-10-22T14:47:06Z
highest_supported_qiskit_version = "2.2.2"
last_month_downloads = 76778
last_180_days_downloads = 294485
