name = "qiskit-addon-cutting"
url = "https://github.com/Qiskit/qiskit-addon-cutting"
description = "Cut large circuits into smaller, hardware-executable circuits, then use their results to reconstruct the original outcome."
licence = "Apache License 2.0"
contact_info = "garrison@ibm.com"
labels = [ "circuit manipulation",]
ibm_maintained = true
created_at = 1670427445.884067
updated_at = 1758737407.8760931
group = "Qiskit addon"
documentation = "https://qiskit.github.io/qiskit-addon-cutting/"
uuid = "b8a6cb2a-e38f-46a5-b714-37ddb1e562e4"
badge = "https://qisk.it/e-b8a6cb2a"

[github]
url = "https://github.com/Qiskit/qiskit-addon-cutting"
owner = "Qiskit"
repo = "qiskit-addon-cutting"
stars = 97
homepage = "https://qiskit.github.io/qiskit-addon-cutting/"
license = "Apache License 2.0"
description = "Reduce width and depth of quantum circuits by cutting gates and wires."
estimated_contributors = 26
total_dependent_repositories = 12
total_dependent_packages = 1
last_commit = 2026-02-02T20:02:09Z
last_activity = 2026-02-02T20:02:10Z

[pypi.qiskit-addon-cutting]
package_name = "qiskit-addon-cutting"
version = "0.10.0"
url = "https://pypi.org/project/qiskit-addon-cutting/"
requires_qiskit = "<3,>=1.3.1"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2025-10-22T14:47:06Z
highest_supported_qiskit_version = "2.2.2"
last_month_downloads = 1767
last_180_days_downloads = 8178
