name = "Qiskit Serverless"
url = "https://github.com/Qiskit/qiskit-serverless"
description = "Execute Qiskit programs as long-running jobs and distribute them across many CPUs, GPUs, and QPUs."
licence = "Apache License 2.0"
contact_info = "sanket@ibm.com"
labels = [ "Software development kit",]
ibm_maintained = true
created_at = 1670427445.627174
updated_at = 1670427445.627175
stars = 68
group = "other"
uuid = "d463fcf2-9e98-4d16-af3b-25ec29b650f7"
