name = "Qiskit Scaleway"
url = "https://github.com/scaleway/qiskit-scaleway"
description = "A Python package to run quantum circuits on Scaleway infrastructure, providing access to simulators on powerful hardware (CPU and GPU)."
licence = "Apache License 2.0"
contact_info = "lmerbouche@scaleway.com"
labels = [ "Circuit simulator", "Compute provider", "Cloud service",]
website = "https://www.scaleway.com"
group = "provider"
documentation = "https://pypi.org/project/qiskit-scaleway/"
uuid = "a942dc5d-c715-4b23-a9d6-4f2c3ee1d70b"
badge = "[![Qiskit Ecosystem](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fqiskit.github.io%2Fecosystem%2Fb%2Fa942dc5d)](https://qisk.it/e)"

[github]
url = "https://github.com/scaleway/qiskit-scaleway"
owner = "scaleway"
repo = "qiskit-scaleway"
stars = 6
license = "Apache License 2.0"
description = "Scaleway provider implementation for Qiskit SDK"
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2025-11-06T16:31:09Z

[pypi.qiskit-scaleway]
package_name = "qiskit-scaleway"
version = "0.3.0"
url = "https://pypi.org/project/qiskit-scaleway/"
requires_qiskit = "~=2.1"
compatible_with_qiskit_v1 = false
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2025-10-22T14:47:06Z
highest_supported_qiskit_version = "2.2.2"
