name = "Qiskit Rigetti Provider"
url = "https://github.com/rigetti/qiskit-rigetti"
description = "Rigetti Provider for Qiskit."
licence = "Apache 2.0"
labels = [ "cloud service",]
created_at = 1678827878.136911
updated_at = 1678827878.136912
group = "Compute provider"
uuid = "88a73f80-a247-4bb4-a6aa-f5da3ebd50c4"
badge = "https://qisk.it/e-88a73f80"

[github]
url = "https://github.com/rigetti/qiskit-rigetti"
owner = "rigetti"
repo = "qiskit-rigetti"
stars = 15
license = "Apache License 2.0"
description = "Qiskit provider serving Rigetti hardware & simulator backends."
estimated_contributors = 10
total_dependent_repositories = 5
total_dependent_packages = 0
last_commit = 2025-04-09T21:16:09Z
last_activity = 2025-12-04T13:53:26Z

[pypi.qiskit-rigetti]
package_name = "qiskit-rigetti"
version = "0.4.7"
url = "https://pypi.org/project/qiskit-rigetti/"
requires_qiskit = ">=0.38.0"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2025-10-22T14:47:06Z
highest_supported_qiskit_version = "2.2.2"
