name = "Qiskit C++"
url = "https://github.com/Qiskit/qiskit-cpp"
contact_info = "qiskit@us.ibm.com"
labels = [ "quantum information", "circuit manipulation",]
ibm_maintained = true
group = "SDK"
uuid = "254bd1b0-409a-42fc-a104-2d8eb8a0b22d"
badge = "https://qisk.it/e-254bd1b0"

[github]
url = "https://github.com/Qiskit/qiskit-cpp"
owner = "Qiskit"
repo = "qiskit-cpp"
stars = 29
license = "Apache License 2.0"
description = "Qiskit C++ is an opensource interface to quantum centric supercomputing, compatible interface to Qiskit in C++"
estimated_contributors = 8
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2025-12-09T02:28:17Z
last_activity = 2025-12-16T02:20:56Z
