name = "Qiskit Inspect"
url = "https://github.com/neuralsorcerer/qiskit-inspect"
description = "Debugger, backend prefix tracing, and assertions for Qiskit."
licence = "Apache License 2.0"
contact_info = "soumyadip@soumyadipsarkar.com"
labels = []
ibm_maintained = false
stars = 1
group = "other"
uuid = "1513e7fe-9390-4014-9c2a-f6c600ddf6ca"
badge = "[![Qiskit Ecosystem](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fqiskit.github.io%2Fecosystem%2Fb%2F1513e7fe)](https://qisk.it/e)"

[github]
url = "https://github.com/neuralsorcerer/qiskit-inspect"
owner = "neuralsorcerer"
repo = "qiskit-inspect"
stars = 1
last_commit = 2025-11-02T09:36:53Z
