name = "QiskitBot"
url = "https://github.com/infiniteregrets/QiskitBot"
description = "A discord bot that allows you to execute Quantum Circuits, look up the Qiskit's Documentation, and search questions on the Quantum Computing StackExchange"
licence = "Apache 2.0"
labels = [ "Productivity",]
created_at = 1641938992.363096
updated_at = 1641938992.363099
stars = 24
group = "other"
