name = "qiskit-addon-aqc-tensor"
url = "https://github.com/Qiskit/qiskit-addon-aqc-tensor"
description = "Map to lower depth circuits by compressing initial layers via approximate quantum compilation with tensor networks (AQC-Tensor)."
licence = "Apache License 2.0"
contact_info = "garrison@ibm.com"
labels = [ "Algorithms", "Circuit building tool",]
ibm_maintained = true
created_at = 1758737407.8760931
stars = 25
group = "qiskit_addon"
documentation = "https://qiskit.github.io/qiskit-addon-aqc-tensor/"
uuid = "5ad8eedc-2e26-4ca9-92de-f1a5d3f3b097"
badge = "[![Qiskit Ecosystem](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fqiskit.github.io%2Fecosystem%2Fb%2F5ad8eedc)](https://qisk.it/e)"

[github]
owner = "Qiskit"
repo = "qiskit-addon-aqc-tensor"
stars = 25

[pypi.qiskit-addon-aqc-tensor]
project = "qiskit-addon-aqc-tensor"
requires_qiskit = "<3,>=1.3.0"
