name = "qiskit-qubit-reuse"
url = "https://github.com/qiskit-community/qiskit-qubit-reuse"
description = "A Qiskit transpiler stage plugin that reuses qubits through mid-circuit measurement and reset."
licence = "Apache License 2.0"
affiliations = "IBM"
labels = [ "Paper implementation",]
stars = 12
group = "transpiler_plugin"
