name = "Qiskit Qulacs"
url = "https://github.com/Gopal-Dahale/qiskit-qulacs"
description = "Qiskit-Qulacs allows users to execute Qiskit programs using Qulacs backend."
licence = "Apache License 2.0"
contact_info = "dahalegopal27@gmail.com"
affiliations = "Supported by the Unitary Fund microgrant program: https://unitary.fund/grants/"
labels = [ "Circuit simulator", "Converter", "Compute provider",]
ibm_maintained = false
stars = 10
group = "provider"
documentation = "https://qiskit-qulacs.netlify.app/"
uuid = "ebd47aa6-4dda-4318-a822-dbd1597ed37a"
badge = "[![Qiskit Ecosystem](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fqiskit.github.io%2Fecosystem%2Fb%2Febd47aa6)](https://qisk.it/e)"

[github]
owner = "Gopal-Dahale"
repo = "qiskit-qulacs"
stars = 10
last_commit = "2025-09-08T18:42:37+00:00"

[pypi.qiskit-qulacs]
package_name = "qiskit-qulacs"
version = "0.1.0"
requires_qiskit = ">=1.0.0"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2025-10-22T14:47:06.921570Z
highest_supported_qiskit_version = "2.2.2"
