name = "Qiskit Research"
url = "https://github.com/qiskit-community/qiskit-research"
description = "Run quantum computing research experiments by using Qiskit and IBM Quantum services, demonstrating best practices by example."
licence = "Apache 2.0"
contact_info = "_No response_"
alternatives = "_No response_"
affiliations = "_No response_"
labels = [ "Paper implementation",]
created_at = 1662992208.202283
updated_at = 1662992208.20229
tier = "Extensions"
tests_results = []
styles_results = []
coverages_results = []
skip_tests = true
historical_test_results = []
stars = 58
group = "other"
