name = "Qiskit Nature PySCF DFT Embedding"
url = "https://github.com/mrossinek/qiskit-nature-pyscf-dft-embedding"
description = "This repository contains the latest prototype implementation of the Qiskit Nature + PySCF DFT Embedding. It is based on \"Quantum HF/DFT-embedding algorithms for electronic structure calculations: Scaling up to complex molecular systems\"."
licence = "Apache License 2.0"
contact_info = "oss@zurich.ibm.com"
alternatives = "_No response_"
affiliations = "_No response_"
labels = [ "Algorithms", "Chemistry",]
created_at = 1685540348.208874
updated_at = 1685540348.208879
stars = 5
group = "applications"
reference_paper = "https://pubs.aip.org/aip/jcp/article-abstract/154/11/114105/315377/Quantum-HF-DFT-embedding-algorithms-for-electronic"
