name = "QiskitOpt.jl"
url = "https://github.com/psrenergy/QiskitOpt.jl"
description = "QiskitOpt.jl is a Julia package that exports a JuMP wrapper for qiskit-optimization."
licence = "MIT license"
contact_info = "pedroxavier@psr-inc.com, pedroripper@psr-inc.com, tiago@psr-inc.com, joaquim@psr-inc.com, dbernalneira@usra.edu"
affiliations = "@psrenergy and USRA"
labels = [ "Algorithms", "Julia",]
created_at = 1673642669.650459
updated_at = 1673642669.650464
stars = 9
group = "applications"
