name = "Qiskit Braket provider"
url = "https://github.com/qiskit-community/qiskit-braket-provider"
description = "Execute Qiskit programs on AWS quantum computing hardware devices through Amazon Braket."
licence = "Apache 2.0"
labels = [ "provider", "cloud service",]
created_at = 1715085130.096724
group = "Compute provider"
uuid = "de20c734-6ee9-4ba0-a4f0-3e4d62ec3c2a"
badge = "https://qisk.it/e-de20c734"

[github]
url = "https://github.com/qiskit-community/qiskit-braket-provider"
owner = "qiskit-community"
repo = "qiskit-braket-provider"
stars = 71
homepage = "https://qiskit-community.github.io/qiskit-braket-provider/"
license = "Apache License 2.0"
description = "Qiskit-Braket provider to execute Qiskit programs on devices via Amazon Braket."
estimated_contributors = 41
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2025-12-22T18:47:12Z
last_activity = 2025-12-22T18:47:12Z

[pypi.qiskit-braket-provider]
package_name = "qiskit-braket-provider"
version = "0.8.0"
url = "https://pypi.org/project/qiskit-braket-provider/"
requires_qiskit = ">=0.34.2"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2025-10-22T14:47:06Z
highest_supported_qiskit_version = "2.2.2"
last_month_downloads = 7989
last_180_days_downloads = 40934
