name = "qiskit-superstaq"
url = "https://github.com/Infleqtion/client-superstaq/tree/main/qiskit-superstaq"
description = "This package is used to access SuperstaQ via a Web API through Qiskit. Qiskit programmers can take advantage of the applications, pulse level optimizations, and write-once-target-all features of SuperstaQ with this package."
licence = "Apache 2.0"
contact_info = ""
alternatives = ""
labels = [ "Converter", "Provider",]
created_at = 1678827878.760089
updated_at = 1678827878.76009
tier = "Community"
skip_tests = true
[[tests_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.43.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414044022"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"
qiskit_version = "0.43.0"
timestamp = 1678827878.751285

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit"
package_version = "0.41.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414043952"
qiskit_version = "0.41.1"
timestamp = 1678827878.760098

[[tests_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.41.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414043952"
qiskit_version = "0.41.1"
timestamp = 1678827878.749304

[[tests_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.39.5"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414043929"
qiskit_version = "0.39.5"
timestamp = 1678827878.751296

[[styles_results]]
passed = false
style_type = "pylint"

[[coverages_results]]
passed = true
coverage_type = ""

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.37.0"
qiskit_version = "0.37.0"
timestamp = 1678827878.760048

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.36.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2998938222"
qiskit_version = "0.36.2"
timestamp = 1678827878.760053

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3180919098"
package_commit_hash = "53e215c31cf3aea51a623dc22883ac92fe74d0b9"
qiskit_version = "0.39.0"
timestamp = 1678827878.760056

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.38.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225637871"
qiskit_version = "0.38.0"
timestamp = 1678827878.760058

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368223849"
qiskit_version = "0.39.0"
timestamp = 1678827878.76006

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.39.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521950701"
qiskit_version = "0.39.2"
timestamp = 1678827878.760063

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.36.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3881839693"
qiskit_version = "0.36.2"
timestamp = 1678827878.760065

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.39.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937700989"
qiskit_version = "0.39.4"
timestamp = 1678827878.760067

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.39.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937701047"
qiskit_version = "0.39.4"
timestamp = 1678827878.76007

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937701165"
package_commit_hash = "af0b2220b75fd5cf3980576b1a31f9c4ceb9f99f"
qiskit_version = "0.40.0"
timestamp = 1678827878.760072

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.39.5"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994625755"
qiskit_version = "0.39.5"
timestamp = 1678827878.760074

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052481340"
qiskit_version = "0.40.0"
timestamp = 1678827878.760077

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.41.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231020376"
qiskit_version = "0.41.0"
timestamp = 1678827878.760079

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.39.5"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414043929"
qiskit_version = "0.39.5"
timestamp = 1678827878.760081

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.43.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414044022"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"
qiskit_version = "0.43.0"
timestamp = 1678827878.760083

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.41.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414043952"
qiskit_version = "0.41.1"
timestamp = 1678827878.749304

[configuration]
dependencies_files = [ "requirements.txt", "dev-requirements.txt",]
extra_dependencies = [ "qiskit",]
tests_command = [ "pytest .  --ignore-glob=*_integration_test.py --ignore=examples/",]
styles_check_command = [ "pylint --rcfile=.pylintrc examples qiskit-superstaq",]
coverages_check_command = [ "pytest qiskit_superstaq --cov --cov-report=term-missing --cov-config=.coveragerc --cov-fail-under=100 --ignore-glob=*_integration_test.py --ignore=examples/",]

[configuration.language]
name = "python"
versions = [ "3.6",]
