name = "qiskit-classroom-converter"
url = "https://github.com/KMU-quantum-classroom/qiskit-classroom-converter"
description = "Convert quantum circuits, matrices, and bra-ket strings. This converter includes the following conversion functions: quantum circuit to bra-ket notation, quantum circuit to matrix, matrix to quantum circuit, bra-ket notation to matrix"
licence = "Apache License 2.0"
contact_info = "_No response_"
alternatives = "_No response_"
affiliations = "_No response_"
labels = [ "Converter",]
tier = "Community"
website = "https://github.com/KMU-quantum-classroom"
styles_results = []
coverages_results = []
skip_tests = false
stars = 2
group = "other"
[[tests_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "1.0.0"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/6861460396"
package_commit_hash = "af6fbd0725de411fbc8f0ff70d550d77ebf715dc"
qiskit_version = "1.0.0"
timestamp = 1699954191.153598

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/6861460396"
qiskit_version = "0.45.0"
timestamp = 1699954240.839332

[[tests_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/6861460396"
qiskit_version = "0.45.0"
timestamp = 1699953850.085405

[[tests_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/6861460396"
qiskit_version = "0.45.0"
timestamp = 1699954239.880078

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.44.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936778455"
qiskit_version = "0.44.0"
timestamp = 1692695810.332834

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6310543985"
qiskit_version = "0.44.1"
timestamp = 1695719543.770475

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6467182720"
qiskit_version = "0.44.1"
timestamp = 1696929604.031178

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6545037395"
package_commit_hash = "62467839e8d4e263465c42118414e6e5eca3c776"
qiskit_version = "0.45.0"
timestamp = 1697534461.770505

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624759165"
qiskit_version = "0.44.2"
timestamp = 1698139442.510082

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.44.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624759165"
qiskit_version = "0.44.2"
timestamp = 1698140015.539843

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/6861460396"
qiskit_version = "0.45.0"
timestamp = 1699953850.085405

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "1.0.0"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/6861460396"
package_commit_hash = "af6fbd0725de411fbc8f0ff70d550d77ebf715dc"
qiskit_version = "1.0.0"
timestamp = 1699954191.153598

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/6861460396"
qiskit_version = "0.45.0"
timestamp = 1699954239.880078

