name = "Qiskit Machine Learning"
url = "https://github.com/qiskit-community/qiskit-machine-learning"
description = "Use flexible building blocks, such as quantum kernels and neural networks, to create quantum machine learning algorithms."
licence = "Apache 2.0"
labels = [ "QML",]
created_at = 1636403010.012954
updated_at = 1636403010.012956
group = "Application"
documentation = "https://qiskit-community.github.io/qiskit-machine-learning/"
uuid = "18986ebc-e138-4998-8c52-16359961af0a"
badge = "https://qisk.it/e-18986ebc"

[github]
url = "https://github.com/qiskit-community/qiskit-machine-learning"
owner = "qiskit-community"
repo = "qiskit-machine-learning"
stars = 939
homepage = "https://qiskit-community.github.io/qiskit-machine-learning/"
license = "Apache License 2.0"
description = "An open-source library built on Qiskit for quantum machine learning tasks at scale on quantum hardware and classical simulators"
total_dependent_repositories = 528
total_dependent_packages = 22
last_commit = 2026-01-22T15:48:05Z
last_activity = 2026-01-29T06:37:28Z

[pypi.qiskit-machine-learning]
package_name = "qiskit-machine-learning"
version = "0.8.4"
url = "https://pypi.org/project/qiskit-machine-learning/"
requires_qiskit = "<2.0,>=1.0"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = false
highest_supported_qiskit_release_date = 2025-10-13T14:23:38Z
highest_supported_qiskit_version = "1.4.5"
last_month_downloads = 59409
last_180_days_downloads = 263496
