name = "Qiskit Research"
url = "https://github.com/qiskit-community/qiskit-research"
description = "Run quantum computing research experiments by using Qiskit and IBM Quantum services, demonstrating best practices by example."
licence = "Apache 2.0"
labels = [ "Paper implementation",]
ibm_maintained = false
created_at = 1662992208.202283
updated_at = 1662992208.20229
stars = 66
group = "other"
uuid = "8794efa6-808d-45a6-bee1-39f8eeb45fdf"
