name = "qiskit-dynamics"
url = "https://github.com/Qiskit-Extensions/qiskit-dynamics"
description = "Dynamics is an open-source project for building, transforming, and solving time-dependent quantum systems in Qiskit."
licence = "Apache 2.0"
labels = [ "Physics",]
created_at = 1628883441.121108
updated_at = 1628883441.121111
tier = "Extensions"
website = "https://qiskit.org/ecosystem/dynamics/"
tests_results = []
styles_results = []
coverages_results = []
skip_tests = true
historical_test_results = []
stars = 74
