name = "qiskit-symb"
url = "https://github.com/SimoneGasperini/qiskit-symb"
description = "Symbolic evaluation of statevectors, density matrices, and unitary operators created from parameterized circuits in Qiskit."
licence = "Apache License 2.0"
contact_info = "simone.gasperini4@unibo.it"
labels = [ "Circuit simulator", "Quantum information",]
ibm_maintained = false
created_at = 1680254616.930627
updated_at = 1680254616.930632
stars = 30
group = "other"
uuid = "9350b230-d7ca-4d52-b082-9d71303478b7"
