name = "QiskitOpt.jl"
url = "https://github.com/JuliaQUBO/QiskitOpt.jl"
description = "QiskitOpt.jl is a Julia package that exports a JuMP wrapper for qiskit-optimization."
licence = "MIT license"
contact_info = "pedrox@cos.ufrj.br, pedroripper@psr-inc.com, tiago@psr-inc.com, joaquim@psr-inc.com, dbernalneira@usra.edu"
affiliations = "@psrenergy and USRA"
labels = [ "Algorithms", "Optimization", "Applications",]
created_at = 1673642669.650459
updated_at = 1673642669.650464
group = "applications"
packages = [ "https://juliapackages.com/p/qiskitopt",]
uuid = "fd796b7d-2775-4ece-89f0-778066552014"
badge = "[![Qiskit Ecosystem](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fqiskit.github.io%2Fecosystem%2Fb%2Ffd796b7d)](https://qisk.it/e)"

[github]
url = "https://github.com/JuliaQUBO/QiskitOpt.jl"
owner = "JuliaQUBO"
repo = "QiskitOpt.jl"
stars = 13
license = "MIT License"
description = "JuMP wrapper for IBMQ Optimization Algorithms (ft QUBODrivers.jl)"
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2024-06-19T13:04:10Z
