name = "qiskit-addon-aqc-tensor"
url = "https://github.com/Qiskit/qiskit-addon-opt-mapper"
description = "Mapping combinatorial optimization problems to quantum computers"
licence = "Apache License 2.0"
contact_info = "garrison@ibm.com"
labels = []
ibm_maintained = true
group = "Qiskit addon"
documentation = "https://qiskit.github.io/qiskit-addon-opt-mapper/"
uuid = "ef4e120a-f308-4462-86b6-10e7c7ba17c7"
badge = "[![Qiskit Ecosystem](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fqiskit.github.io%2Fecosystem%2Fb%2Fef4e120a)](https://qisk.it/e)"

[github]
url = "https://github.com/Qiskit/qiskit-addon-opt-mapper"
owner = "Qiskit"
repo = "qiskit-addon-opt-mapper"
stars = 11
homepage = "https://qiskit.github.io/qiskit-addon-opt-mapper/"
license = "Apache License 2.0"
description = "Mapping combinatorial optimization problems to quantum computers"
estimated_contributors = 22
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2025-11-19T11:15:10Z
last_activity = 2025-11-20T08:33:44Z

[pypi.qiskit-addon-opt-mapper]
package_name = "qiskit-addon-opt-mapper"
version = "0.1.0"
url = "https://pypi.org/project/qiskit-addon-opt-mapper/"
requires_qiskit = "<3"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2025-10-22T14:47:06Z
highest_supported_qiskit_version = "2.2.2"
last_month_downloads = 560
last_180_days_downloads = 560
