name = "Qiskit QEC"
url = "https://github.com/qiskit-community/qiskit-qec"
description = "For quantum error correction developers, experimentalists, and theorists."
licence = "Apache 2.0"
contact_info = "_No response_"
alternatives = "_No response_"
affiliations = "_No response_"
labels = [ "Algorithms", "Error correction", "Circuit",]
created_at = 1662992390.122591
updated_at = 1662992390.122597
stars = 66
group = "other"
