name = "qiskit-research"
url = "https://github.com/qiskit-community/qiskit-research"
description = "This project contains modules for running quantum computing research experiments using Qiskit and the IBM Quantum Services, demonstrating by example best practices for running such experiments."
licence = "Apache 2.0"
contact_info = "_No response_"
alternatives = "_No response_"
affiliations = "_No response_"
labels = [ "paper implementation",]
created_at = 1662992208.202283
updated_at = 1662992208.20229
tier = "Extensions"
tests_results = []
styles_results = []
coverages_results = []
skip_tests = true
historical_test_results = []
stars = 56
