name = "qiskit-superstaq"
url = "https://github.com/Infleqtion/client-superstaq/tree/main/qiskit-superstaq"
description = "Access the SuperstaQ web API through Qiskit for applications, pulse-level optimizations, and write-once-target-all features."
licence = "Apache 2.0"
contact_info = ""
alternatives = ""
labels = [ "Converter", "Compute provider",]
ibm_maintained = false
created_at = 1678827878.760089
updated_at = 1678827878.76009
group = "provider"
