name = "qiskit-rs"
url = "https://github.com/Qiskit/Qiskit-rs"
contact_info = ""
labels = [ "Rust",]
ibm_maintained = true
group = "SDK"
uuid = "0f1aa4a6-6012-4f23-afe9-17436f718460"

[github]
url = "https://github.com/Qiskit/qiskit-rs"
owner = "Qiskit"
repo = "qiskit-rs"
stars = 5
license = "Apache License 2.0"
description = "Rust binding for Qiskit"
estimated_contributors = 2
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2025-11-18T20:29:35Z
last_activity = 2025-11-21T18:50:24Z
