name = "Qiskit Nature"
url = "https://github.com/qiskit-community/qiskit-nature"
description = "Model and solve problems in physics, chemistry, material science, and biology by using quantum simulations."
licence = "Apache 2.0"
labels = [ "Algorithms", "Chemistry", "Physics", "Application package",]
ibm_maintained = false
created_at = 1636403009.16708
updated_at = 1636403009.167082
stars = 293
group = "applications"
documentation = "https://qiskit-community.github.io/qiskit-nature/"
uuid = "768ba9e4-0aea-4046-a902-5c81051f001f"
