name = "QiskitOpt.jl"
url = "https://github.com/JuliaQUBO/QiskitOpt.jl"
description = "QiskitOpt.jl is a Julia package that exports a JuMP wrapper for qiskit-optimization."
licence = "MIT license"
contact_info = "pedrox@cos.ufrj.br, pedroripper@psr-inc.com, tiago@psr-inc.com, joaquim@psr-inc.com, dbernalneira@usra.edu"
affiliations = "@psrenergy and USRA"
labels = [ "Algorithms", "Optimization", "Application package",]
ibm_maintained = false
created_at = 1673642669.650459
updated_at = 1673642669.650464
stars = 10
group = "applications"
uuid = "fd796b7d-2775-4ece-89f0-778066552014"
