name = "qiskit-addon-sqd-hpc"
url = "https://github.com/Qiskit/qiskit-addon-sqd-hpc"
description = "A modern C++ software library to enable large-scale SQD calculations on high-performance computing (HPC) systems."
licence = "Apache License 2.0"
contact_info = "garrison@ibm.com"
related_projects = ["qiskit-addon-sqd"]
labels = [ "Algorithms",]
ibm_maintained = true
website = "https://qiskit.github.io/qiskit-addon-sqd-hpc/"
group = "qiskit_addon"
uuid = "f342b5ed-2136-4f7a-bd00-a0a7d2df3493"
