name = "qiskit-nature-pyscf-dft-embedding"
url = "https://github.com/mrossinek/qiskit-nature-pyscf-dft-embedding"
description = "This repository contains the latest prototype implementation of the Qiskit Nature + PySCF DFT Embedding. It is based on the following publication: > Max Rossmannek, Panagiotis Kl. Barkoutsos, Pauline J. Ollitrault, Ivano Tavernelli; > Quantum HF/DFT-embedding algorithms for electronic structure calculations: Scaling up to complex molecular systems. > J. Chem. Phys. 21 March 2021; 154 (11): 114105."
licence = "Apache License 2.0"
contact_info = "oss@zurich.ibm.com"
alternatives = "_No response_"
affiliations = "_No response_"
labels = [ "Algorithms", "Chemistry",]
created_at = 1685540348.208874
updated_at = 1685540348.208879
tier = "Community"
styles_results = []
coverages_results = []
skip_tests = false
stars = 4
group = "applications"
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "1.0.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6782294797"
package_commit_hash = "af643eb09b22fc3833084b3112890b1aebdcbf92"
qiskit_version = "1.0.0"
timestamp = 1699348761.766701

[[tests_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6782294797"
qiskit_version = "0.45.0"
timestamp = 1699348339.889254

[[tests_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6782294797"
qiskit_version = "0.45.0"
timestamp = 1699348799.092081

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936781104"
package_commit_hash = "0b51250e219ca303654fc28a318c21366584ccd3"
qiskit_version = "unknown"
timestamp = 1692695570.725693

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936781104"
qiskit_version = "unknown"
timestamp = 1692695570.725697

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936781104"
qiskit_version = "unknown"
timestamp = 1692695570.546512

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6310543007"
qiskit_version = "0.44.1"
timestamp = 1695719518.259935

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6545036237"
package_commit_hash = "62467839e8d4e263465c42118414e6e5eca3c776"
qiskit_version = "0.45.0"
timestamp = 1697534308.766613

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.44.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624754872"
qiskit_version = "0.44.2"
timestamp = 1698138755.839153

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = ""
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624754872"
qiskit_version = ""
timestamp = 1698139207.103735

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6782294797"
qiskit_version = "0.45.0"
timestamp = 1699348339.889254

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "1.0.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6782294797"
package_commit_hash = "af643eb09b22fc3833084b3112890b1aebdcbf92"
qiskit_version = "1.0.0"
timestamp = 1699348761.766701

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6782294797"
qiskit_version = "0.45.0"
timestamp = 1699348799.092081

