name = "qiskit-classroom"
url = "https://github.com/KMU-quantum-classroom/qiskit-classroom"
description = "Qiskit-classroom is a toolkit that helps implement quantum algorithms by converting and visualizing different expressions used in the Qiskit ecosystem using Qiskit-classroom-converter. The following three transformations are supported : Quantum circuit to Dirac notation, quantum circuit to matrix, matrix to quantum circuit etc."
licence = "Apache License 2.0"
contact_info = "_No response_"
alternatives = "_No response_"
affiliations = "_No response_"
labels = [ "Visualization",]
tier = "Community"
website = "https://github.com/KMU-quantum-classroom"
styles_results = []
coverages_results = []
skip_tests = false
stars = 1
group = "other"
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = ""
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7098436459"
package_commit_hash = "b1fc8e9bddacf63e8bf0e535f9e0c18233746ee2"
qiskit_version = ""
timestamp = 1701767305.895153

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit"
package_version = "0.45.1"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7098436459"
qiskit_version = "0.45.1"
timestamp = 1701767348.989064

[[tests_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.45.1"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7098436459"
qiskit_version = "0.45.1"
timestamp = 1701767077.138847

[[tests_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7098436459"
qiskit_version = "0.44.1"
timestamp = 1701767347.02167

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6310545378"
qiskit_version = "0.44.1"
timestamp = 1695719559.39801

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6545042072"
package_commit_hash = "62467839e8d4e263465c42118414e6e5eca3c776"
qiskit_version = "0.45.0"
timestamp = 1697535040.818637

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624758746"
qiskit_version = "0.44.2"
timestamp = 1698139332.539176

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "1.0.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624758746"
package_commit_hash = "fe3bffbc85a4fb57dc62ba04fa7f11bcefb5d75f"
qiskit_version = "1.0.0"
timestamp = 1698139755.818676

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7098436459"
qiskit_version = "0.44.1"
timestamp = 1701767347.02167

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.45.1"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7098436459"
qiskit_version = "0.45.1"
timestamp = 1701767077.138847

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = ""
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7098436459"
package_commit_hash = "b1fc8e9bddacf63e8bf0e535f9e0c18233746ee2"
qiskit_version = ""
timestamp = 1701767305.895153

