name = "Qiskit Nature PySCF"
url = "https://github.com/qiskit-community/qiskit-nature-pyscf"
description = "Qiskit Nature PySCF is a third-party integration plugin of Qiskit Nature and PySCF."
licence = "Apache License 2.0"
contact_info = "_No response_"
alternatives = "_No response_"
labels = [ "Chemistry",]
created_at = 1678827878.723733
updated_at = 1678827878.723734
tier = "Community"
styles_results = []
coverages_results = []
skip_tests = false
stars = 15
group = "applications"
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = ""
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7098437521"
package_commit_hash = "b1fc8e9bddacf63e8bf0e535f9e0c18233746ee2"
qiskit_version = ""
timestamp = 1701767660.317713

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit"
package_version = "0.45.1"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7098437521"
qiskit_version = "0.45.1"
timestamp = 1701767710.564793

[[tests_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.45.1"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7098437521"
qiskit_version = "0.45.1"
timestamp = 1701767433.923042

[[tests_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.45.1"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7098437521"
qiskit_version = "0.45.1"
timestamp = 1701767707.398002

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937705234"
package_commit_hash = "af0b2220b75fd5cf3980576b1a31f9c4ceb9f99f"
qiskit_version = "0.40.0"
timestamp = 1692696201.987688

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.39.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937705147"
qiskit_version = "0.39.4"
timestamp = 1692696201.987691

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.39.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937705182"
qiskit_version = "0.39.4"
timestamp = 1692696201.987694

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.39.5"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994629837"
qiskit_version = "0.39.5"
timestamp = 1692696201.987697

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.40.0rc1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994629761"
qiskit_version = "0.40.0rc1"
timestamp = 1692696201.9877

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052485540"
qiskit_version = "0.40.0"
timestamp = 1692696201.987704

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052485468"
qiskit_version = "0.40.0"
timestamp = 1692696201.987707

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.41.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231023779"
qiskit_version = "0.41.0"
timestamp = 1692696201.98771

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.41.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231023690"
qiskit_version = "0.41.0"
timestamp = 1692696201.987713

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.41.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414047797"
qiskit_version = "0.41.1"
timestamp = 1692696201.987716

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.41.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414047863"
qiskit_version = "0.41.1"
timestamp = 1692696201.987719

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.43.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414047970"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"
qiskit_version = "0.43.0"
timestamp = 1692696201.987722

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6310546314"
qiskit_version = "0.44.1"
timestamp = 1695720038.087814

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6545040475"
package_commit_hash = "62467839e8d4e263465c42118414e6e5eca3c776"
qiskit_version = "0.45.0"
timestamp = 1697534806.265146

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "1.0.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624757853"
package_commit_hash = "fe3bffbc85a4fb57dc62ba04fa7f11bcefb5d75f"
qiskit_version = "1.0.0"
timestamp = 1698139363.687709

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = ""
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624757853"
qiskit_version = ""
timestamp = 1698139406.111886

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624757853"
qiskit_version = "0.44.2"
timestamp = 1698138896.88371

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.45.1"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7098437521"
qiskit_version = "0.45.1"
timestamp = 1701767707.398002

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = ""
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7098437521"
package_commit_hash = "b1fc8e9bddacf63e8bf0e535f9e0c18233746ee2"
qiskit_version = ""
timestamp = 1701767660.317713

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.45.1"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7098437521"
qiskit_version = "0.45.1"
timestamp = 1701767433.923042

