name = "qiskit-superstaq"
url = "https://github.com/Infleqtion/client-superstaq/tree/main/qiskit-superstaq"
description = "Access the SuperstaQ web API through Qiskit for applications, pulse-level optimizations, and write-once-target-all features."
licence = "Apache 2.0"
contact_info = ""
labels = [ "Converter", "Compute provider", "Cloud service",]
ibm_maintained = false
created_at = 1678827878.760089
updated_at = 1678827878.76009
stars = 105
group = "provider"
uuid = "76ae525f-0734-405b-b4b8-421f74125fa2"
badge = "[![Qiskit Ecosystem](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fqiskit.github.io%2Fecosystem%2Fb%2F76ae525f)](https://qisk.it/e)"

[github]
owner = "Infleqtion"
repo = "client-superstaq"
tree = "main/qiskit-superstaq"
stars = 105
last_commit = "2025-10-27T18:03:57+00:00"

[pypi.qiskit-superstaq]
package_name = "qiskit-superstaq"
version = "0.5.53"
requires_qiskit = ">=1.3.0"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
release_date_of_the_last_qiskit_version_supported = 2025-10-22T14:47:06.921570Z
last_qiskit_version_supported = "2.2.2"
