name = "Qiskit Nature + CP2K Embedding"
url = "https://github.com/mrossinek/qiskit-nature-cp2k"
description = "This project contains the utilities that are required for the communication between Qiskit Nature and CP2K."
licence = "Apache License 2.0"
labels = [ "chemistry",]
group = "Application"
reference_paper = "https://arxiv.org/abs/2404.18737"
uuid = "a08d66f6-0ee7-446c-a121-c9c692bc0ae9"
badge = "[![Qiskit Ecosystem](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fqiskit.github.io%2Fecosystem%2Fb%2Fa08d66f6)](https://qisk.it/e)"

[github]
url = "https://github.com/mrossinek/qiskit-nature-cp2k"
owner = "mrossinek"
repo = "qiskit-nature-cp2k"
stars = 7
license = "Apache License 2.0"
description = "Qiskit Nature + CP2K Embedding"
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2024-08-10T10:50:35Z
last_activity = 2025-12-03T11:17:35Z
