name = "Qiskit Research"
url = "https://github.com/qiskit-community/qiskit-research"
description = "Software utilities for running quantum computing research experiments using Qiskit and the IBM Quantum Services."
licence = "Apache 2.0"
labels = []
created_at = 1662992208.202283
updated_at = 1662992208.20229
group = "Other"
uuid = "8794efa6-808d-45a6-bee1-39f8eeb45fdf"
badge = "https://qisk.it/e-8794efa6"

[github]
url = "https://github.com/qiskit-community/qiskit-research"
owner = "qiskit-community"
repo = "qiskit-research"
stars = 71
homepage = "https://qiskit-community.github.io/qiskit-research/"
license = "Apache License 2.0"
description = "Research using Qiskit."
estimated_contributors = 9
total_dependent_repositories = 0
total_dependent_packages = 0
archived = true
last_commit = 2025-08-25T14:16:21Z
last_activity = 2025-12-08T21:59:10Z

[pypi.qiskit-research]
package_name = "qiskit-research"
version = "0.0.4"
url = "https://pypi.org/project/qiskit-research/"
requires_qiskit = "==1.1.1"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = false
highest_supported_qiskit_release_date = 2024-06-20T16:55:07Z
highest_supported_qiskit_version = "1.1.1"
last_month_downloads = 67
last_180_days_downloads = 317
