name = "qiskit-symb"
url = "https://github.com/SimoneGasperini/qiskit-symb"
description = "Easy-to-use Python package designed to enable symbolic quantum computation in Qiskit. It provides the basic tools for the symbolic evaluation of statevectors, density matrices, and unitary operators directly created from parametric Qiskit quantum circuits. The implementation is based on the Sympy library as backend for symbolic expressions manipulation."
licence = "Apache License 2.0"
contact_info = "simone.gasperini4@unibo.it"
alternatives = "_No response_"
affiliations = "_No response_"
labels = [ "quantum-info", "symbolic-computation",]
created_at = 1680254616.930627
updated_at = 1680254616.930632
tests_results = []
styles_results = []
coverages_results = []
tier = "Community"
skip_tests = false
historical_test_results = []
stars = 10

[configuration]
dependencies_files = [ "requirements.txt",]
extra_dependencies = []
tests_command = [ "pytest -v --cov=qiskit_symb",]
styles_check_command = [ "pylint src/ tests/",]
coverages_check_command = []

[configuration.language]
name = "python"
versions = [ "3.8", "3.9", "3.10",]
