name = "qiskit-ibm-runtime C"
url = "https://github.com/Qiskit/qiskit-ibm-runtime-c/"
contact_info = ""
labels = [ "C", "provider",]
ibm_maintained = true
group = "Compute provider"
uuid = "964baff2-3155-4944-94c4-738961df7d6b"
badge = "https://qisk.it/e-964baff2"

[github]
url = "https://github.com/Qiskit/qiskit-ibm-runtime-c"
owner = "Qiskit"
repo = "qiskit-ibm-runtime-c"
stars = 11
license = "Apache License 2.0"
description = "IBM Quantum Platform API Client for Qiskit's C API"
estimated_contributors = 3
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2026-01-12T21:42:53Z
last_activity = 2026-01-14T21:35:08Z
