name = "Qiskit IonQ Provider"
url = "https://github.com/Qiskit-Partners/qiskit-ionq"
description = "This project contains a provider that allows access to IonQ ion trap quantum systems."
licence = "Apache 2.0"
contact_info = ""
alternatives = ""
labels = [ "Provider", "Partner",]
created_at = 1670427446.011674
updated_at = 1670427446.011675
stars = 38
group = "provider"
