name = "qiskit-classroom-converter"
url = "https://github.com/KMU-quantum-classroom/qiskit-classroom-converter"
description = "Convert quantum circuits, matrices, and bra-ket strings. This converter includes the following conversion functions: quantum circuit to bra-ket notation, quantum circuit to matrix, matrix to quantum circuit, bra-ket notation to matrix"
licence = "Apache License 2.0"
contact_info = "_No response_"
alternatives = "_No response_"
affiliations = "_No response_"
labels = [ "converter",]
tier = "Community"
website = "https://github.com/KMU-quantum-classroom"
tests_results = []
styles_results = []
coverages_results = []
skip_tests = false
historical_test_results = []
stars = 1
