name = "qiskit-metal-docker"
url = "https://github.com/Dpbm/qiskit-metal-docker"
description = "A Docker image to run Qiskit Metal projects."
licence = "MIT license"
contact_info = "dpbm136@gmail.com"
alternatives = "_No response_"
affiliations = "_No response_"
labels = [ "Hardware",]
website = "https://dpbm.github.io/qiskit-metal-docker/"
stars = 0
group = "other"
