name = "Qiskit Finance"
url = "https://github.com/qiskit-community/qiskit-finance"
description = "Includes uncertainty components for stock/securities problems, Ising translators for portfolio optimizations, and data providers."
licence = "Apache 2.0"
labels = [ "Algorithms", "Finance", "Applications",]
ibm_maintained = false
created_at = 1636403009.368607
updated_at = 1636403009.368609
stars = 290
group = "applications"
documentation = "https://qiskit-community.github.io/qiskit-finance/"
uuid = "8ebeec26-5043-4423-9cdc-bfa92bd4ad63"
badge = "[![Qiskit Ecosystem](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fqiskit.github.io%2Fecosystem%2Fb%2F8ebeec26)](https://qisk.it/e)"

[github]
owner = "qiskit-community"
repo = "qiskit-finance"
stars = 290
last_commit = "2025-10-24T19:21:38+00:00"

[pypi.qiskit-finance]
package_name = "qiskit-finance"
version = "0.4.1"
requires_qiskit = ">=0.45"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2025-10-22T14:47:06.921570Z
highest_supported_qiskit_version = "2.2.2"
