name = "Qiskit AQT Provider"
url = "https://github.com/qiskit-community/qiskit-aqt-provider"
description = "Qiskit provider for ion-trap quantum computers from Alpine Quantum Technologies (AQT)."
licence = "Apache License 2.0"
contact_info = "info@aqt.eu"
alternatives = "_No response_"
affiliations = "Alpine Quantum Technologies GmbH"
labels = [ "Provider",]
tier = "Community"
website = "https://www.aqt.eu/qc-systems/"
styles_results = []
coverages_results = []
skip_tests = false
stars = 26
group = "provider"
documentation = "https://qiskit-community.github.io/qiskit-aqt-provider/"
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = ""
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7539254996"
package_commit_hash = "0a860fd968959c80ad8a3a099b5ec15d2f1f6a6e"
qiskit_version = ""
timestamp = 1705396951.715711

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit"
package_version = "0.45.1"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7539254996"
qiskit_version = "0.45.1"
timestamp = 1705396976.391946

[[tests_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.45.1"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7539254996"
qiskit_version = "0.45.1"
timestamp = 1705396854.468236

[[tests_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.45.1"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7539254996"
qiskit_version = "0.45.1"
timestamp = 1705396975.433709

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.43.3"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624757109"
qiskit_version = "0.43.3"
timestamp = 1698139164.804802

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "1.0.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624757109"
package_commit_hash = "fe3bffbc85a4fb57dc62ba04fa7f11bcefb5d75f"
qiskit_version = "1.0.0"
timestamp = 1698139135.510237

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624757109"
qiskit_version = "0.44.2"
timestamp = 1698138760.205501

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.45.1"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7539254996"
qiskit_version = "0.45.1"
timestamp = 1705396854.468236

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = ""
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7539254996"
package_commit_hash = "0a860fd968959c80ad8a3a099b5ec15d2f1f6a6e"
qiskit_version = ""
timestamp = 1705396951.715711

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.45.1"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7539254996"
qiskit_version = "0.45.1"
timestamp = 1705396975.433709

