name = "Qiskit IonQ Provider"
url = "https://github.com/qiskit-community/qiskit-ionq"
description = "This project contains a provider that allows access to IonQ ion trap quantum systems."
licence = "Apache 2.0"
contact_info = ""
alternatives = ""
labels = [ "Compute provider",]
ibm_maintained = false
created_at = 1670427446.011674
updated_at = 1670427446.011675
stars = 43
group = "provider"
uuid = "9dec814e-feb8-49c2-818a-f6a2503d38c5"
