name = "qiskit-quimb"
url = "https://github.com/qiskit-community/qiskit-quimb"
description = "Simulate Qiskit circuits using quimb."
licence = "Apache License 2.0"
labels = [ "Circuit simulator",]
ibm_maintained = false
stars = 15
group = "other"
uuid = "a304538c-feb7-47b2-a41f-f9fbe41de87b"
badge = "[![Qiskit Ecosystem](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fqiskit.github.io%2Fecosystem%2Fb%2Fa304538c)](https://qisk.it/e)"

[github]
owner = "qiskit-community"
repo = "qiskit-quimb"
stars = 15
last_commit = "2025-06-11T03:23:29+00:00"

[pypi.qiskit-quimb]
package_name = "qiskit-quimb"
version = "0.0.9"
requires_qiskit = ">=0"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
