name = "QiskitOpt.jl"
url = "https://github.com/psrenergy/QiskitOpt.jl"
description = "QiskitOpt.jl is a Julia package that exports a JuMP wrapper for qiskit-optimization."
licence = "MIT license"
contact_info = "pedroxavier@psr-inc.com, pedroripper@psr-inc.com, tiago@psr-inc.com, joaquim@psr-inc.com, dbernalneira@usra.edu"
alternatives = "_No response_"
affiliations = "@psrenergy and USRA"
labels = [ "algorithms",]
created_at = 1673642669.650459
updated_at = 1673642669.650464
tier = "Community"
tests_results = []
styles_results = []
coverages_results = []
skip_tests = true
historical_test_results = []
stars = 8
