name = "Qiskit Machine Learning"
url = "https://github.com/qiskit-community/qiskit-machine-learning"
description = "Use flexible building blocks, such as quantum kernels and neural networks, to create quantum machine learning algorithms."
licence = "Apache 2.0"
labels = [ "Algorithms", "Machine learning", "Application package",]
ibm_maintained = false
created_at = 1636403010.012954
updated_at = 1636403010.012956
stars = 628
group = "applications"
documentation = "https://qiskit-community.github.io/qiskit-machine-learning/"
uuid = "18986ebc-e138-4998-8c52-16359961af0a"
