name = "qiskit-addon-pna"
url = "https://github.com/Qiskit/qiskit-addon-pna"
description = "Mitigate gate noise in expectation values by propagating the observable through the inverse noise channel."
licence = "Apache License 2.0"
contact_info = "garrison@ibm.com"
labels = []
ibm_maintained = true
stars = 4
group = "qiskit_addon"
documentation = "https://qiskit.github.io/qiskit-addon-pna/"
uuid = "4cb3b182-7484-445f-897b-ded8e295d755"
badge = "[![Qiskit Ecosystem](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fqiskit.github.io%2Fecosystem%2Fb%2F4cb3b182)](https://qisk.it/e)"

[github]
url = "https://github.com/Qiskit/qiskit-addon-pna"
owner = "Qiskit"
repo = "qiskit-addon-pna"
stars = 4
last_commit = 2025-11-10T17:23:31Z

[pypi.qiskit-addon-pna]
package_name = "qiskit-addon-pna"
version = "0.0.0"
url = "https://pypi.org/project/qiskit-addon-pna/"
requires_qiskit = "<3,>=2.1.2"
compatible_with_qiskit_v1 = false
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2025-10-22T14:47:06Z
highest_supported_qiskit_version = "2.2.2"
