name = "qiskit-finance"
url = "https://github.com/qiskit-community/qiskit-finance"
description = "Qiskit Finance is an open-source framework that contains uncertainty components for stock/securities problems, Ising translators for portfolio optimizations and data providers to source real or random data to finance experiments."
licence = "Apache 2.0"
labels = [ "Algorithms", "Finance",]
created_at = 1636403009.368607
updated_at = 1636403009.368609
tier = "Community"
website = "https://qiskit.org/ecosystem/finance/"
tests_results = []
styles_results = []
coverages_results = []
skip_tests = true
historical_test_results = []
stars = 176
