name = "Alice & Bob Qiskit provider"
url = "https://github.com/Alice-Bob-SW/qiskit-alice-bob-provider"
description = "Access Alice & Bob QPUs and emulators using Qiskit."
licence = "Apache 2.0"
labels = [ "Compute provider",]
ibm_maintained = false
created_at = 1715084994.136498
stars = 29
group = "provider"
uuid = "00f82ee3-ab46-44fc-afbb-32cb34a72339"
