name = "qiskit-aqt-provider"
url = "https://github.com/qiskit-community/qiskit-aqt-provider"
description = "Qiskit provider for ion-trap quantum computers from Alpine Quantum Technologies (AQT). https://www.aqt.eu/qc-systems/"
licence = "Apache License 2.0"
contact_info = "[info@aqt.eu](mailto:info@aqt.eu)"
alternatives = "_No response_"
affiliations = "Alpine Quantum Technologies GmbH"
labels = [ "Provider",]
tier = "Community"
website = "https://qiskit-community.github.io/qiskit-aqt-provider/"
tests_results = []
styles_results = []
coverages_results = []
skip_tests = false
historical_test_results = []
