name = "qiskit-superstaq"
url = "https://github.com/Infleqtion/client-superstaq/tree/main/qiskit-superstaq"
description = "Access the SuperstaQ web API through Qiskit for applications, pulse-level optimizations, and write-once-target-all features."
licence = "Apache 2.0"
contact_info = ""
labels = [ "provider", "cloud service",]
created_at = 1678827878.760089
updated_at = 1678827878.76009
group = "Compute provider"
uuid = "76ae525f-0734-405b-b4b8-421f74125fa2"
badge = "[![Qiskit Ecosystem](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fqiskit.github.io%2Fecosystem%2Fb%2F76ae525f)](https://qisk.it/e)"

[github]
url = "https://github.com/Infleqtion/client-superstaq"
owner = "Infleqtion"
repo = "client-superstaq"
tree = "main/qiskit-superstaq"
stars = 108
license = "Apache License 2.0"
description = "https://superstaq.readthedocs.io"
estimated_contributors = 38
total_dependent_repositories = 53
total_dependent_packages = 8
last_commit = 2025-12-01T15:38:01Z
last_activity = 2025-12-03T19:53:35Z

[pypi.qiskit-superstaq]
package_name = "qiskit-superstaq"
version = "0.5.54"
url = "https://pypi.org/project/qiskit-superstaq/"
requires_qiskit = ">=1.3.0"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2025-10-22T14:47:06Z
highest_supported_qiskit_version = "2.2.2"
last_month_downloads = 4243
last_180_days_downloads = 25113
