name = "Qiskit Quantinuum provider"
url = "https://github.com/qiskit-community/qiskit-quantinuum-provider"
description = "Provider to access Quantinuum quantum devices."
licence = "Apache 2.0"
labels = [ "provider", "cloud service",]
created_at = 1715085347.688097
group = "Compute provider"
uuid = "d5d174ee-cbe5-48a3-82ac-66d4cf2579c1"
badge = "https://qisk.it/e-d5d174ee"

[github]
url = "https://github.com/qiskit-community/qiskit-quantinuum-provider"
owner = "qiskit-community"
repo = "qiskit-quantinuum-provider"
stars = 25
license = "Apache License 2.0"
description = "Qiskit provider for Quantinuum backends."
estimated_contributors = 6
total_dependent_repositories = 0
total_dependent_packages = 0
archived = true
last_commit = 2025-03-13T19:32:07Z
last_activity = 2026-01-10T10:15:51Z

[pypi.qiskit-quantinuum-provider]
package_name = "qiskit-quantinuum-provider"
version = "0.4.1"
url = "https://pypi.org/project/qiskit-quantinuum-provider/"
last_month_downloads = 16
last_180_days_downloads = 114
