name = "qiskit-classroom-converter"
url = "https://github.com/KMU-quantum-classroom/qiskit-classroom-converter"
description = "Convert between circuits, matrices, and bra-ket strings."
licence = "Apache License 2.0"
labels = []
website = "https://github.com/KMU-quantum-classroom"
group = "Converter"
uuid = "bc3b8894-7e2b-4fa3-8cd2-550e58e4133b"
badge = "[![Qiskit Ecosystem](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fqiskit.github.io%2Fecosystem%2Fb%2Fbc3b8894)](https://qisk.it/e)"

[github]
url = "https://github.com/KMU-quantum-classroom/qiskit-classroom-converter"
owner = "KMU-quantum-classroom"
repo = "qiskit-classroom-converter"
stars = 1
homepage = "https://pypi.org/project/qiskit-classroom-converter/"
license = "Apache License 2.0"
description = "qiskit classroom's quantum circuit / bra-ket notation / matrix  converter package"
estimated_contributors = 3
total_dependent_repositories = 3
total_dependent_packages = 1
last_commit = 2025-10-23T06:09:01Z
last_activity = 2025-09-29T07:19:35Z

[pypi.qiskit-classroom-converter]
package_name = "qiskit-classroom-converter"
version = "0.6.0"
url = "https://pypi.org/project/qiskit-classroom-converter/"
requires_qiskit = "==1.3.1"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = false
highest_supported_qiskit_release_date = 2024-12-12T23:38:12Z
highest_supported_qiskit_version = "1.3.1"
last_month_downloads = 78
last_180_days_downloads = 487
