name = "Qiskit Dynamics"
url = "https://github.com/qiskit-community/qiskit-dynamics"
description = "Build, transform, and solve time-dependent quantum systems."
licence = "Apache 2.0"
labels = [ "physics",]
ibm_maintained = true
created_at = 1628883441.121108
updated_at = 1628883441.121111
group = "Application"
documentation = "https://qiskit-community.github.io/qiskit-dynamics/"
uuid = "4bf110b1-5e54-4540-8338-d7d0fb7801d0"
badge = "https://qisk.it/e-4bf110b1"

[github]
url = "https://github.com/qiskit-community/qiskit-dynamics"
owner = "qiskit-community"
repo = "qiskit-dynamics"
stars = 117
homepage = "https://qiskit-community.github.io/qiskit-dynamics/"
license = "Apache License 2.0"
description = "DEPRECATED - Tools for building and solving models of quantum systems in Qiskit"
total_dependent_repositories = 0
total_dependent_packages = 0
archived = true
last_commit = 2025-10-07T18:43:19Z
last_activity = 2026-02-02T11:57:03Z

[pypi.qiskit-dynamics]
package_name = "qiskit-dynamics"
version = "0.6.0"
url = "https://pypi.org/project/qiskit-dynamics/"
requires_qiskit = "<=1.3"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = false
highest_supported_qiskit_release_date = 2024-11-29T08:35:05Z
highest_supported_qiskit_version = "1.3.0"
last_month_downloads = 16753
last_180_days_downloads = 36204
