name = "mthree"
url = "https://github.com/Qiskit/qiskit-addon-mthree"
description = "Matrix-free Measurement Mitigation (M3). Reduce the effects of readout errors from noisy quantum hardware."
licence = "Apache 2.0"
contact_info = ""
labels = [ "Error mitigation",]
ibm_maintained = true
created_at = 1678827878.805163
updated_at = 1678827878.805164
stars = 48
group = "qiskit_addon"
documentation = "https://qiskit.github.io/qiskit-addon-mthree"
uuid = "875968b2-f9e9-44a9-a5dc-4db9c4805021"
badge = "[![Qiskit Ecosystem](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fqiskit.github.io%2Fecosystem%2Fb%2F875968b2)](https://qisk.it/e)"

[github]
owner = "Qiskit"
repo = "qiskit-addon-mthree"
stars = 48
