name = "mthree"
url = "https://github.com/Qiskit/qiskit-addon-mthree"
description = "Matrix-free Measurement Mitigation (M3). Reduce the effects of readout errors from noisy quantum hardware."
licence = "Apache 2.0"
contact_info = ""
alternatives = ""
labels = [ "Error mitigation",]
ibm_maintained = true
created_at = 1678827878.805163
updated_at = 1678827878.805164
stars = 41
group = "other"
documentation = "https://qiskit.github.io/qiskit-addon-mthree"
uuid = "875968b2-f9e9-44a9-a5dc-4db9c4805021"
