name = "qiskit-optimization"
url = "https://github.com/qiskit-community/qiskit-optimization"
description = "Framework that covers the whole range from high-level modeling of optimization problems, with automatic conversion of problems to different required representations, to a suite of easy-to-use quantum optimization algorithms that are ready to run on classical simulators, as well as on real quantum devices via Qiskit."
licence = "Apache 2.0"
labels = [ "algorithms", "optimization",]
created_at = 1636403009.538761
updated_at = 1636403009.538763
tier = "Community"
website = "https://qiskit.org/ecosystem/optimization"
tests_results = []
styles_results = []
coverages_results = []
skip_tests = true
historical_test_results = []
stars = 174
