name = "Qiskit IBM Provider"
url = "https://github.com/Qiskit/qiskit-ibm-provider"
description = "Access IBM Quantum systems."
licence = "Apache 2.0"
contact_info = ""
alternatives = ""
affiliations = "IBM"
labels = [ "IBM maintained", "Provider", "Partner",]
created_at = 1654696732.591266
updated_at = 1654696732.591279
stars = 76
group = "provider"
documentation = "https://docs.quantum.ibm.com/api/qiskit-ibm-provider"
