name = "Qiskit BIP Mapper"
url = "https://github.com/qiskit-community/qiskit-bip-mapper"
description = "This plugin solves the routing and layout problems as a binary integer programming (BIP) problem. This is an implementation of G. Nannicini et al. \"Optimal qubit assignment and routing via integer programming.\"."
licence = "Apache License 2.0"
contact_info = "itoko@jp.ibm.com"
alternatives = "_No response_"
affiliations = "IBM"
labels = [ "Paper implementation",]
created_at = 1681306690.423614
updated_at = 1681306690.423619
tier = "Community"
tests_results = []
styles_results = []
coverages_results = []
skip_tests = true
historical_test_results = []
stars = 4
group = "transpiler_plugin"
reference_paper = "https://arxiv.org/abs/2106.06446"
