name = "qiskit-bip-mapper"
url = "https://github.com/qiskit-community/qiskit-bip-mapper"
description = "The repository contains a standalone routing stage plugin to use the BIPMapping [routing](https://qiskit.org/documentation/apidoc/transpiler.html#routing-stage) pass. The BIP mapping pass solves the routing and [layout](https://qiskit.org/documentation/apidoc/transpiler.html#layout-stage) problems as a binary integer programming (BIP) problem. The algorithm used in this pass is described in: G. Nannicini et al. \"Optimal qubit assignment and routing via integer programming.\" [arXiv:2106.06446](https://arxiv.org/abs/2106.06446)"
licence = "Apache License 2.0"
contact_info = "itoko@jp.ibm.com"
alternatives = "_No response_"
affiliations = "IBM"
labels = [ "plugin", "paper implementation",]
created_at = 1681306690.423614
updated_at = 1681306690.423619
tier = "Community"
tests_results = []
styles_results = []
coverages_results = []
skip_tests = true
historical_test_results = []
stars = 4
