name = "Qiskit Optimization"
url = "https://github.com/qiskit-community/qiskit-optimization"
description = "Model optimization problems, convert them between different representations, and solve them with quantum algorithms."
licence = "Apache 2.0"
labels = [ "Algorithms", "Optimization", "Application package",]
ibm_maintained = false
created_at = 1636403009.538761
updated_at = 1636403009.538763
stars = 215
group = "applications"
documentation = "https://qiskit-community.github.io/qiskit-optimization/"
