name = "qiskit-qubit-reuse"
url = "https://github.com/qiskit-community/qiskit-qubit-reuse"
description = "A Qiskit transpiler stage plugin that reuses qubits through mid-circuit measurement and reset."
licence = "Apache License 2.0"
affiliations = "IBM"
labels = [ "research",]
group = "Transpiler plugin"
uuid = "c9369922-7e0d-4b77-b00a-329472b57a34"
badge = "https://qisk.it/e-c9369922"

[github]
url = "https://github.com/qiskit-community/qiskit-qubit-reuse"
owner = "qiskit-community"
repo = "qiskit-qubit-reuse"
stars = 28
license = "Apache License 2.0"
description = "A Qiskit transpiler stage plugin to enable qubit reuse via mid-circuit measurement and reset."
estimated_contributors = 3
total_dependent_repositories = 2
total_dependent_packages = 0
last_commit = 2025-07-03T17:08:32Z
last_activity = 2025-11-24T19:35:18Z

[pypi.qiskit-qubit-reuse]
package_name = "qiskit-qubit-reuse"
version = "0.0.2"
url = "https://pypi.org/project/qiskit-qubit-reuse/"
requires_qiskit = ">=0.43.0"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2025-10-22T14:47:06Z
highest_supported_qiskit_version = "2.2.2"
last_month_downloads = 18
last_180_days_downloads = 96
