name = "qiskit-ibm-runtime C"
url = "https://github.com/Qiskit/qiskit-ibm-runtime-c/"
contact_info = ""
labels = [ "C", "provider"]
ibm_maintained = true
group = "Compute provider"
uuid = "964baff2-3155-4944-94c4-738961df7d6b"
badge = "[![Qiskit Ecosystem](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fqiskit.github.io%2Fecosystem%2Fb%2F964baff2)](https://qisk.it/e)"

[github]
url = "https://github.com/Qiskit/qiskit-ibm-runtime-c"
owner = "Qiskit"
repo = "qiskit-ibm-runtime-c"
stars = 9
license = "Apache License 2.0"
description = "IBM Quantum Platform API Client for Qiskit's C API"
estimated_contributors = 2
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2025-10-30T18:38:09Z
last_activity = 2025-11-12T13:56:17Z
