name = "qiskit-addon-aqc-tensor"
url = "https://github.com/Qiskit/qiskit-addon-aqc-tensor"
description = "Map to lower depth circuits by compressing initial layers via approximate quantum compilation with tensor networks (AQC-Tensor)."
licence = "Apache License 2.0"
contact_info = "garrison@ibm.com"
labels = [ "circuit manipulation",]
ibm_maintained = true
created_at = 1758737407.8760931
group = "Qiskit addon"
documentation = "https://qiskit.github.io/qiskit-addon-aqc-tensor/"
uuid = "5ad8eedc-2e26-4ca9-92de-f1a5d3f3b097"
badge = "https://qisk.it/e-5ad8eedc"

[github]
url = "https://github.com/Qiskit/qiskit-addon-aqc-tensor"
owner = "Qiskit"
repo = "qiskit-addon-aqc-tensor"
stars = 24
homepage = "https://qiskit.github.io/qiskit-addon-aqc-tensor/"
license = "Apache License 2.0"
description = "Reduce circuit depth by compressing initial layers via approximate quantum compilation with tensor networks (AQC-Tensor)"
estimated_contributors = 9
total_dependent_repositories = 7
total_dependent_packages = 0
last_commit = 2025-12-16T14:23:49Z
last_activity = 2025-12-16T14:23:50Z

[pypi.qiskit-addon-aqc-tensor]
package_name = "qiskit-addon-aqc-tensor"
version = "0.2.0"
url = "https://pypi.org/project/qiskit-addon-aqc-tensor/"
requires_qiskit = "<3,>=1.3.0"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2025-10-22T14:47:06Z
highest_supported_qiskit_version = "2.2.2"
last_month_downloads = 1429
last_180_days_downloads = 11492
