name = "Qiskit AQT Provider"
url = "https://github.com/qiskit-community/qiskit-aqt-provider"
description = "Qiskit provider for ion-trap quantum computers from Alpine Quantum Technologies (AQT)."
licence = "Apache License 2.0"
contact_info = "info@aqt.eu"
affiliations = "Alpine Quantum Technologies GmbH"
labels = [ "Compute provider",]
ibm_maintained = false
website = "https://www.aqt.eu/qc-systems/"
stars = 27
group = "provider"
documentation = "https://qiskit-community.github.io/qiskit-aqt-provider/"
uuid = "04f15cf5-ee50-4c77-b254-8907ed3ba407"
