name = "Qiskit Nature PySCF"
url = "https://github.com/qiskit-community/qiskit-nature-pyscf"
description = "A third-party integration plugin of Qiskit Nature and PySCF."
licence = "Apache License 2.0"
labels = [ "chemistry",]
created_at = 1678827878.723733
updated_at = 1678827878.723734
group = "Application"
documentation = "https://qiskit-community.github.io/qiskit-nature-pyscf/"
uuid = "1bfdd558-ebef-446b-aad5-1be7ecce68cd"
badge = "https://qisk.it/e-1bfdd558"

[github]
url = "https://github.com/qiskit-community/qiskit-nature-pyscf"
owner = "qiskit-community"
repo = "qiskit-nature-pyscf"
stars = 22
license = "Apache License 2.0"
description = "Documentation at https://qiskit-community.github.io/qiskit-nature-pyscf/"
estimated_contributors = 7
total_dependent_repositories = 8
total_dependent_packages = 0
last_commit = 2025-08-12T16:17:34Z
last_activity = 2026-01-13T05:09:52Z

[pypi.qiskit-nature-pyscf]
package_name = "qiskit-nature-pyscf"
version = "0.4.0"
url = "https://pypi.org/project/qiskit-nature-pyscf/"
last_month_downloads = 412
last_180_days_downloads = 2633
