name = "qiskit-nature-pyscf-dft-embedding"
url = "https://github.com/mrossinek/qiskit-nature-pyscf-dft-embedding"
description = "This repository contains the latest prototype implementation of the Qiskit Nature + PySCF DFT Embedding. It is based on the following publication: > Max Rossmannek, Panagiotis Kl. Barkoutsos, Pauline J. Ollitrault, Ivano Tavernelli; > Quantum HF/DFT-embedding algorithms for electronic structure calculations: Scaling up to complex molecular systems. > J. Chem. Phys. 21 March 2021; 154 (11): 114105."
licence = "Apache License 2.0"
contact_info = "oss@zurich.ibm.com"
alternatives = "_No response_"
affiliations = "_No response_"
labels = [ "Algorithms", "Chemistry",]
created_at = 1685540348.208874
updated_at = 1685540348.208879
tier = "Community"
styles_results = []
coverages_results = []
skip_tests = false
stars = 3
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6010261836"
package_commit_hash = "3bd1d46c93a9d6cf2ae9e21093ce8df2b3cf52ad"
qiskit_version = "unknown"
timestamp = 1693300319.785806

[[tests_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6010261836"
qiskit_version = "unknown"
timestamp = 1693300316.340416

[[tests_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6010261836"
qiskit_version = "unknown"
timestamp = 1693300322.929817

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6010261836"
qiskit_version = "unknown"
timestamp = 1693300322.929817

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6010261836"
qiskit_version = "unknown"
timestamp = 1693300316.340416

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6010261836"
package_commit_hash = "3bd1d46c93a9d6cf2ae9e21093ce8df2b3cf52ad"
qiskit_version = "unknown"
timestamp = 1693300319.785806

