name = "Qiskit SAT Synthesis"
url = "https://github.com/qiskit-community/qiskit-sat-synthesis"
description = "Synthesis plugins for Cliffords, linear functions, permutations, and more"
licence = "Apache License 2.0"
contact_info = "alexi@il.ibm.com"
alternatives = "There are other quantum circuit compilation tools that use SAT-solving to search for optimum circuits, for instance: MQT QMAP (https://github.com/cda-tum/mqt-qmap), and tweedledum (https://github.com/boschmitt/tweedledum)."
affiliations = "IBM"
labels = []
stars = 2
group = "transpiler_plugin"
