name = "Qiskit Optimization"
url = "https://github.com/qiskit-community/qiskit-optimization"
description = "Model optimization problems, convert them between different representations, and solve them by using quantum optimization algorithms on simulators or systems."
licence = "Apache 2.0"
labels = [ "Algorithms", "Optimization",]
created_at = 1636403009.538761
updated_at = 1636403009.538763
tier = "Community"
website = "https://qiskit.org/ecosystem/optimization"
tests_results = []
styles_results = []
coverages_results = []
skip_tests = true
historical_test_results = []
stars = 184
group = "applications"
