name = "Qiskit Nature PySCF"
url = "https://github.com/qiskit-community/qiskit-nature-pyscf"
description = "A third-party integration plugin of Qiskit Nature and PySCF."
licence = "Apache License 2.0"
labels = [ "Chemistry", "Application package",]
ibm_maintained = false
created_at = 1678827878.723733
updated_at = 1678827878.723734
stars = 20
group = "applications"
documentation = "https://qiskit-community.github.io/qiskit-nature-pyscf/"
uuid = "1bfdd558-ebef-446b-aad5-1be7ecce68cd"
