name = "qiskit-cold-atom"
url = "https://github.com/qiskit-community/qiskit-cold-atom"
description = "This project builds on this functionality to describe programmable quantum simulators of trapped cold atoms in a gate- and circuit-based framework."
licence = "Apache 2.0"
contact_info = ""
alternatives = ""
labels = [ "Provider", "Physics",]
created_at = 1678827878.507531
updated_at = 1678827878.507532
tier = "Community"
styles_results = []
coverages_results = []
skip_tests = false
stars = 23
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6467186956"
package_commit_hash = "cecb7889372342e3c2ca713d5c767ad793688842"
qiskit_version = "0.45.0"
timestamp = 1696930131.284525

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit"
package_version = "0.44.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6467186956"
qiskit_version = "0.44.2"
timestamp = 1696930196.632498

[[tests_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6467186956"
qiskit_version = "0.44.2"
timestamp = 1696929749.793055

[[tests_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = ""
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6467186956"
qiskit_version = ""
timestamp = 1696930195.541938

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.37.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824121773"
qiskit_version = "0.37.1"
timestamp = 1692695880.437201

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.37.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824121773"
qiskit_version = "0.37.1"
timestamp = 1692695880.437204

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3180920905"
package_commit_hash = "53e215c31cf3aea51a623dc22883ac92fe74d0b9"
qiskit_version = "0.39.0"
timestamp = 1692695880.437208

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.38.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225639328"
qiskit_version = "0.38.0"
timestamp = 1692695880.437211

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.38.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225639358"
qiskit_version = "0.38.0"
timestamp = 1692695880.437214

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368225772"
qiskit_version = "0.39.0"
timestamp = 1692695880.437217

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368225754"
qiskit_version = "0.39.0"
timestamp = 1692695880.437221

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.39.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521953898"
qiskit_version = "0.39.2"
timestamp = 1692695880.437224

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.39.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521953919"
qiskit_version = "0.39.2"
timestamp = 1692695880.437227

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937705694"
qiskit_version = "0.40.0"
timestamp = 1692695880.43723

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.39.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937705604"
qiskit_version = "0.39.4"
timestamp = 1692695880.437234

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.39.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937705583"
qiskit_version = "0.39.4"
timestamp = 1692695880.437237

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.39.5"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994630594"
qiskit_version = "0.39.5"
timestamp = 1692695880.43724

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.39.5"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994630688"
qiskit_version = "0.39.5"
timestamp = 1692695880.437243

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052485912"
qiskit_version = "0.40.0"
timestamp = 1692695880.437246

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052485977"
qiskit_version = "0.40.0"
timestamp = 1692695880.437249

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.41.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231024143"
qiskit_version = "0.41.0"
timestamp = 1692695880.437252

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.41.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231024081"
qiskit_version = "0.41.0"
timestamp = 1692695880.437255

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.41.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414048649"
qiskit_version = "0.41.1"
timestamp = 1692695880.437259

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.41.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414048578"
qiskit_version = "0.41.1"
timestamp = 1692695880.437262

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.43.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414048688"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"
qiskit_version = "0.43.0"
timestamp = 1692695880.437265

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6310545543"
qiskit_version = "0.44.1"
timestamp = 1695719577.688871

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6467186956"
qiskit_version = "0.44.2"
timestamp = 1696929749.793055

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6467186956"
package_commit_hash = "cecb7889372342e3c2ca713d5c767ad793688842"
qiskit_version = "0.45.0"
timestamp = 1696930131.284525

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = ""
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6467186956"
qiskit_version = ""
timestamp = 1696930195.541938

[configuration]
dependencies_files = [ "requirements-dev.txt",]
extra_dependencies = []
debian_dependencies = []
tests_command = [ "stestr run",]
styles_check_command = [ "pylint -rn -j 0 --rcfile=./.pylintrc qiskit_cold_atom/ test/",]
coverages_check_command = []

[configuration.language]
name = "python"
versions = [ "3.7",]
