name = "Qiskit Rigetti Provider"
url = "https://github.com/rigetti/qiskit-rigetti"
description = "Rigetti Provider for Qiskit."
licence = "Apache 2.0"
labels = [ "Provider",]
created_at = 1678827878.136911
updated_at = 1678827878.136912
stars = 8
group = "provider"
