name = "Qiskit Research"
url = "https://github.com/qiskit-community/qiskit-research"
description = "Software utilities for running quantum computing research experiments using Qiskit and the IBM Quantum Services."
licence = "Apache 2.0"
labels = []
ibm_maintained = false
created_at = 1662992208.202283
updated_at = 1662992208.20229
stars = 68
group = "other"
uuid = "8794efa6-808d-45a6-bee1-39f8eeb45fdf"
