created_at = 1636403010.012954
description = "The Machine Learning package contains sample datasets and quantum ML algorithms."
labels = [ "algorithms", "machine learning",]
licence = "Apache 2.0"
name = "qiskit-machine-learning"
tier = "Community"
updated_at = 1636403010.012956
url = "https://github.com/qiskit-community/qiskit-machine-learning"
website = "https://qiskit.org/ecosystem/machine-learning"
tests_results = []
styles_results = []
coverages_results = []
skip_tests = true
stars = 476
