name = "FAdam-VQE"
url = "https://github.com/dolf3131/qiskit_algorithms_V2"
description = "Custom VQE with FAdam optimizer, compatible with Qiskit 1.0+ EstimatorV2 for quantum chemistry & optimization."
licence = "Apache License 2.0"
contact_info = "milk_lime@naver.com"
labels = [ "research",]
website = "https://arxiv.org/abs/2405.12807"
group = "Application"
reference_paper = "https://arxiv.org/abs/2405.12807"
documentation = "https://arxiv.org/abs/2405.12807"
uuid = "e4d840cb-e4f1-4e58-84f6-d5a77a5d2d1e"
badge = "https://qisk.it/e-e4d840cb"

[github]
url = "https://github.com/dolf3131/qiskit_algorithms_V2"
owner = "dolf3131"
repo = "qiskit_algorithms_V2"
stars = 1
license = "Apache License 2.0"
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2025-07-06T05:00:37Z
