name = "Qiskit Algorithms"
url = "https://github.com/qiskit-community/qiskit-algorithms"
description = "A library of quantum algorithms for near-term quantum devices with short-depth circuits."
licence = "Apache License 2.0"
contact_info = "ept@zurich.ibm.com"
affiliations = "IBM Quantum"
labels = [ "Algorithms", "Application package",]
ibm_maintained = false
stars = 98
group = "applications"
documentation = "https://qiskit-community.github.io/qiskit-algorithms/"
uuid = "39fba621-edbb-485b-a723-8a0760ab4b85"
