name = "qiskit-aer"
url = "https://github.com/Qiskit/qiskit-aer"
description = "Aer provides high-performance quantum computing simulators with realistic noise models."
licence = "Apache 2.0"
labels = [ "Circuit simulator",]
created_at = 1636403010.377695
updated_at = 1636403010.377697
tier = "Main"
website = "https://qiskit.org/ecosystem/aer"
tests_results = []
styles_results = []
coverages_results = []
skip_tests = true
historical_test_results = []
stars = 403
