name = "Qiskit on IQM"
url = "https://github.com/iqm-finland/qiskit-on-iqm"
description = "Qiskit adapter for IQM's quantum computers."
licence = "Apache 2.0"
labels = [ "provider", "cloud service",]
created_at = 1715085233.375706
group = "Compute provider"
uuid = "648ef199-ace1-4c6b-ae9c-2c0578cde0d5"
badge = "https://qisk.it/e-648ef199"

[github]
url = "https://github.com/iqm-finland/qiskit-on-iqm"
owner = "iqm-finland"
repo = "qiskit-on-iqm"
stars = 29
homepage = "https://iqm-finland.github.io/qiskit-on-iqm/"
license = "Apache License 2.0"
description = "Qiskit adapter for IQM's quantum computers"
estimated_contributors = 20
total_dependent_repositories = 0
total_dependent_packages = 0
archived = true
last_commit = 2025-09-16T16:24:21Z

[pypi.qiskit-iqm]
package_name = "qiskit-iqm"
version = "18.2"
url = "https://pypi.org/project/qiskit-iqm/"
requires_qiskit = "<1.3,>=1.0"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = false
highest_supported_qiskit_release_date = 2024-10-03T19:47:28Z
highest_supported_qiskit_version = "1.2.4"
last_month_downloads = 4251
last_180_days_downloads = 23957
