name = "Qiskit Aer"
url = "https://github.com/Qiskit/qiskit-aer"
description = "High-performance quantum computing simulators with realistic noise models."
licence = "Apache 2.0"
labels = [ "Circuit simulator",]
ibm_maintained = true
created_at = 1636403010.377695
updated_at = 1636403010.377697
stars = 470
group = "other"
documentation = "https://qiskit.org/ecosystem/aer"
uuid = "474599a7-228b-446f-ae57-636fdbe8c1c6"
