name = "Qiskit Cold Atom"
url = "https://github.com/qiskit-community/qiskit-cold-atom"
description = "Qiskit-cold-atom builds on core Qiskit functionalities to integrate programmable quantum simulators of trapped cold atoms in a gate- and circuit-based framework. The project includes a provider and simulators for fermionic and spin-based systems."
licence = "Apache 2.0"
contact_info = ""
alternatives = ""
labels = [ "Provider", "Physics",]
created_at = 1678827878.507531
updated_at = 1678827878.507532
tier = "Community"
website = "https://qiskit-community.github.io/qiskit-cold-atom/"
styles_results = []
coverages_results = []
skip_tests = false
stars = 25
group = "provider"
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = ""
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7098437184"
package_commit_hash = "b1fc8e9bddacf63e8bf0e535f9e0c18233746ee2"
qiskit_version = ""
timestamp = 1701767660.194693

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit"
package_version = "0.44.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624755140"
qiskit_version = "0.44.2"
timestamp = 1698139310.496177

[[tests_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.45.1"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7098437184"
qiskit_version = "0.45.1"
timestamp = 1701767420.781251

[[tests_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.45.1"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7098437184"
qiskit_version = "0.45.1"
timestamp = 1701767712.349304

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.37.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824121773"
qiskit_version = "0.37.1"
timestamp = 1692695880.437201

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.37.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824121773"
qiskit_version = "0.37.1"
timestamp = 1692695880.437204

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3180920905"
package_commit_hash = "53e215c31cf3aea51a623dc22883ac92fe74d0b9"
qiskit_version = "0.39.0"
timestamp = 1692695880.437208

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.38.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225639328"
qiskit_version = "0.38.0"
timestamp = 1692695880.437211

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.38.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225639358"
qiskit_version = "0.38.0"
timestamp = 1692695880.437214

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368225772"
qiskit_version = "0.39.0"
timestamp = 1692695880.437217

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368225754"
qiskit_version = "0.39.0"
timestamp = 1692695880.437221

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.39.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521953898"
qiskit_version = "0.39.2"
timestamp = 1692695880.437224

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.39.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521953919"
qiskit_version = "0.39.2"
timestamp = 1692695880.437227

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937705694"
qiskit_version = "0.40.0"
timestamp = 1692695880.43723

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.39.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937705604"
qiskit_version = "0.39.4"
timestamp = 1692695880.437234

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.39.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937705583"
qiskit_version = "0.39.4"
timestamp = 1692695880.437237

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.39.5"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994630594"
qiskit_version = "0.39.5"
timestamp = 1692695880.43724

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.39.5"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994630688"
qiskit_version = "0.39.5"
timestamp = 1692695880.437243

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052485912"
qiskit_version = "0.40.0"
timestamp = 1692695880.437246

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052485977"
qiskit_version = "0.40.0"
timestamp = 1692695880.437249

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.41.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231024143"
qiskit_version = "0.41.0"
timestamp = 1692695880.437252

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.41.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231024081"
qiskit_version = "0.41.0"
timestamp = 1692695880.437255

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.41.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414048649"
qiskit_version = "0.41.1"
timestamp = 1692695880.437259

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.41.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414048578"
qiskit_version = "0.41.1"
timestamp = 1692695880.437262

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.43.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414048688"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"
qiskit_version = "0.43.0"
timestamp = 1692695880.437265

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6310545543"
qiskit_version = "0.44.1"
timestamp = 1695719577.688871

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6545041837"
package_commit_hash = "62467839e8d4e263465c42118414e6e5eca3c776"
qiskit_version = "0.45.0"
timestamp = 1697535062.255855

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624755140"
qiskit_version = "0.44.2"
timestamp = 1698138792.66062

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = ""
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624755140"
qiskit_version = ""
timestamp = 1698139309.354068

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "1.0.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624755140"
package_commit_hash = "fe3bffbc85a4fb57dc62ba04fa7f11bcefb5d75f"
qiskit_version = "1.0.0"
timestamp = 1698139244.826846

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.45.1"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7098437184"
qiskit_version = "0.45.1"
timestamp = 1701767712.349304

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = ""
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7098437184"
package_commit_hash = "b1fc8e9bddacf63e8bf0e535f9e0c18233746ee2"
qiskit_version = ""
timestamp = 1701767660.194693

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.45.1"
logs_link = "https://github.com/Qiskit/ecosystem/actions/runs/7098437184"
qiskit_version = "0.45.1"
timestamp = 1701767420.781251

[configuration]
dependencies_files = [ "requirements-dev.txt",]
extra_dependencies = []
debian_dependencies = []
tests_command = [ "stestr run",]
styles_check_command = [ "pylint -rn -j 0 --rcfile=./.pylintrc qiskit_cold_atom/ test/",]
coverages_check_command = []

[configuration.language]
name = "python"
versions = [ "3.7",]
