name = "qiskit-ibm-runtime"
url = "https://github.com/qiskit/qiskit-ibm-runtime"
description = "This module provides the interface to access Qiskit Runtime."
licence = "Apache 2.0"
contact_info = ""
alternatives = ""
affiliations = "IBM"
labels = [ "Provider", "Partner",]
created_at = 1654696489.147673
updated_at = 1654696489.147699
tier = "Main"
tests_results = []
styles_results = []
coverages_results = []
skip_tests = true
historical_test_results = []
stars = 93
