name = "Qiskit Metal"
url = "https://github.com/qiskit-community/qiskit-metal"
description = "Design superconducting qubits through a Python API or a visual interface."
licence = "Apache 2.0"
labels = [ "Hardware",]
created_at = 1628883441.119202
updated_at = 1628883441.119205
tier = "Community"
tests_results = []
styles_results = []
coverages_results = []
skip_tests = true
historical_test_results = []
stars = 251
group = "other"
documentation = "https://qiskit.org/ecosystem/metal/"
