name = "qiskit-toqm"
url = "https://github.com/qiskit-toqm/qiskit-toqm"
description = "Qiskit transpiler routing method using the Time-Optimal Qubit Mapping (TOQM) algorithm, described in https://doi.org/10.1145/3445814.3446706"
licence = "Apache License 2.0"
contact_info = "_No response_"
alternatives = "_No response_"
labels = [ "Transpiler plugin", "Paper implementation", "Circuit",]
created_at = 1678827878.737541
updated_at = 1678827878.737541
tier = "Community"
styles_results = []
coverages_results = []
skip_tests = true
stars = 4
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936779645"
package_commit_hash = "0b51250e219ca303654fc28a318c21366584ccd3"
qiskit_version = "0.45.0"
timestamp = 1692695765.590667

[[tests_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936779645"
qiskit_version = "0.44.1"
timestamp = 1692695765.590677

[[tests_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = ""
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936779645"
qiskit_version = ""
timestamp = 1692695765.461104

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368225279"
qiskit_version = "0.39.0"
timestamp = 1692695765.590688

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368225231"
qiskit_version = "0.39.0"
timestamp = 1692695765.590691

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.39.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521953115"
qiskit_version = "0.39.2"
timestamp = 1692695765.590695

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.39.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521953228"
qiskit_version = "0.39.2"
timestamp = 1692695765.590698

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3881841568"
package_commit_hash = "0344a1c94b8eb8206da18cc74d9bdc70ad203c9a"
qiskit_version = "0.40.0"
timestamp = 1692695765.590701

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.39.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937704714"
qiskit_version = "0.39.4"
timestamp = 1692695765.590705

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.39.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937704666"
qiskit_version = "0.39.4"
timestamp = 1692695765.590708

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.39.5"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994629059"
qiskit_version = "0.39.5"
timestamp = 1692695765.590712

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.39.5"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994628983"
qiskit_version = "0.39.5"
timestamp = 1692695765.590715

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052484838"
qiskit_version = "0.40.0"
timestamp = 1692695765.590718

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052484746"
qiskit_version = "0.40.0"
timestamp = 1692695765.590722

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.41.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231023237"
qiskit_version = "0.41.0"
timestamp = 1692695765.590725

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.41.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231023197"
qiskit_version = "0.41.0"
timestamp = 1692695765.590729

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.41.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414047083"
qiskit_version = "0.41.1"
timestamp = 1692695765.590732

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.41.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414047031"
qiskit_version = "0.41.1"
timestamp = 1692695765.590735

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.43.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414047132"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"
qiskit_version = "0.43.0"
timestamp = 1692695765.590738

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936779645"
qiskit_version = "0.44.1"
timestamp = 1692695765.590745

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936779645"
package_commit_hash = "0b51250e219ca303654fc28a318c21366584ccd3"
qiskit_version = "0.45.0"
timestamp = 1692695765.590748

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = ""
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936779645"
qiskit_version = ""
timestamp = 1692695765.461104

