name = "Qiskit Experiments"
url = "https://github.com/Qiskit-Extensions/qiskit-experiments"
description = "Run characterizing, calibrating, and benchmarking experiments."
licence = "Apache 2.0"
labels = [ "Algorithms", "Hardware",]
created_at = 1661785302.25299
updated_at = 1661785302.25299
tier = "Extensions"
website = "https://qiskit.org/ecosystem/experiments/"
tests_results = []
styles_results = []
coverages_results = []
skip_tests = true
historical_test_results = []
stars = 124
group = "other"
