name = "Qiskit Nature PySCF"
url = "https://github.com/qiskit-community/qiskit-nature-pyscf"
description = "Qiskit Nature PySCF is a third-party integration plugin of Qiskit Nature and PySCF."
licence = "Apache License 2.0"
contact_info = "_No response_"
alternatives = "_No response_"
labels = [ "plugin", "chemistry",]
created_at = 1678827878.723733
updated_at = 1678827878.723734
styles_results = []
coverages_results = []
tier = "Community"
skip_tests = false
stars = 13
[[tests_results]]
test_type = "development"
passed = true
package = "qiskit-terra"
package_version = "0.24.0"
qiskit_version = "0.43.0"
timestamp = 1678827878.721648
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414047970"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"

[[tests_results]]
test_type = "last passing version"
passed = true
package = "qiskit-terra"
package_version = "0.23.2"
qiskit_version = "0.41.1"
timestamp = 1678827878.723691
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414047863"

[[tests_results]]
test_type = "stable"
passed = true
package = "qiskit-terra"
package_version = "0.23.2"
qiskit_version = "0.41.1"
timestamp = 1678827878.723694
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414047863"

[[tests_results]]
test_type = "standard"
passed = true
package = "qiskit-terra"
package_version = "0.23.2"
qiskit_version = "0.41.1"
timestamp = 1678827878.723697
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414047797"

[[historical_test_results]]
test_type = "development"
passed = true
package = "qiskit-terra"
package_version = "0.23.0"
qiskit_version = "0.40.0"
timestamp = 1678827878.723702
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937705234"
package_commit_hash = "af0b2220b75fd5cf3980576b1a31f9c4ceb9f99f"

[[historical_test_results]]
test_type = "standard"
passed = true
package = "qiskit-terra"
package_version = "0.22.3"
qiskit_version = "0.39.4"
timestamp = 1678827878.723705
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937705147"

[[historical_test_results]]
test_type = "stable"
passed = true
package = "qiskit-terra"
package_version = "0.22.3"
qiskit_version = "0.39.4"
timestamp = 1678827878.723707
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937705182"

[[historical_test_results]]
test_type = "stable"
passed = true
package = "qiskit-terra"
package_version = "0.22.4"
qiskit_version = "0.39.5"
timestamp = 1678827878.723709
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994629837"

[[historical_test_results]]
test_type = "standard"
passed = true
package = "qiskit-terra"
package_version = "0.23.0rc1"
qiskit_version = "0.40.0"
timestamp = 1678827878.723711
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994629761"

[[historical_test_results]]
test_type = "stable"
passed = true
package = "qiskit-terra"
package_version = "0.23.0"
qiskit_version = "0.40.0"
timestamp = 1678827878.723714
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052485540"

[[historical_test_results]]
test_type = "standard"
passed = true
package = "qiskit-terra"
package_version = "0.23.0"
qiskit_version = "0.40.0"
timestamp = 1678827878.723716
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052485468"

[[historical_test_results]]
test_type = "stable"
passed = true
package = "qiskit-terra"
package_version = "0.23.1"
qiskit_version = "0.41.0"
timestamp = 1678827878.723718
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231023779"

[[historical_test_results]]
test_type = "standard"
passed = true
package = "qiskit-terra"
package_version = "0.23.1"
qiskit_version = "0.41.0"
timestamp = 1678827878.72372
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231023690"

[[historical_test_results]]
test_type = "standard"
passed = true
package = "qiskit-terra"
package_version = "0.23.2"
qiskit_version = "0.41.1"
timestamp = 1678827878.723725
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414047797"

[[historical_test_results]]
test_type = "stable"
passed = true
package = "qiskit-terra"
package_version = "0.23.2"
qiskit_version = "0.41.1"
timestamp = 1678827878.723727
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414047863"

[[historical_test_results]]
test_type = "development"
passed = true
package = "qiskit-terra"
package_version = "0.24.0"
qiskit_version = "0.43.0"
timestamp = 1678827878.721648
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414047970"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"

