name = "qiskit-rigetti"
url = "https://github.com/rigetti/qiskit-rigetti"
description = "Rigetti Provider for Qiskit"
licence = "Apache 2.0"
labels = [ "provider",]
created_at = 1678827878.136911
updated_at = 1678827878.136912
tier = "Community"
skip_tests = false
stars = 8
[[tests_results]]
test_type = "development"
passed = false
package = "qiskit-terra"
package_version = "0.24.0"
terra_version = "0.24.0"
timestamp = 1678827878.128199
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414046008"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"

[[tests_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.23.2"
terra_version = "0.23.2"
timestamp = 1678827878.126264
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414045904"

[[tests_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.23.2"
terra_version = "0.23.2"
timestamp = 1678827878.128207
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414045863"

[[styles_results]]
style_type = "pylint"
passed = false

[[coverages_results]]
coverage_type = ""
passed = false

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.20.2"
terra_version = "0.20.2"
timestamp = 1678827878.136846

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.20.2"
terra_version = "0.20.2"
timestamp = 1678827878.136852

[[historical_test_results]]
test_type = "development"
passed = false
package = "qiskit-terra"
package_version = "0.21.0"
terra_version = "0.21.0"
timestamp = 1678827878.136854

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.21.0"
terra_version = "0.21.0"
timestamp = 1678827878.136857
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2617548565"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.21.0"
terra_version = "0.21.0"
timestamp = 1678827878.136859
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2617548565"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.21.1"
terra_version = "0.21.1"
timestamp = 1678827878.136861
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824121452"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.21.1"
terra_version = "0.21.1"
timestamp = 1678827878.136863
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824121452"

[[historical_test_results]]
test_type = "development"
passed = false
package = "qiskit-terra"
package_version = "0.22.0"
terra_version = "0.22.0"
timestamp = 1678827878.136866
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3180920336"
package_commit_hash = "53e215c31cf3aea51a623dc22883ac92fe74d0b9"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.21.2"
terra_version = "0.21.2"
timestamp = 1678827878.136868
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225638837"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.21.2"
terra_version = "0.21.2"
timestamp = 1678827878.13687
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225638860"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.22.0"
terra_version = "0.22.0"
timestamp = 1678827878.136872
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368224732"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.22.0"
terra_version = "0.22.0"
timestamp = 1678827878.136874
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368224678"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.22.2"
terra_version = "0.22.2"
timestamp = 1678827878.136877
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521952331"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.22.2"
terra_version = "0.22.2"
timestamp = 1678827878.136879
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521952362"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.22.3"
terra_version = "0.22.3"
timestamp = 1678827878.136881
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937703796"

[[historical_test_results]]
test_type = "development"
passed = false
package = "qiskit-terra"
package_version = "0.23.0"
terra_version = "0.23.0"
timestamp = 1678827878.136883
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937703897"
package_commit_hash = "af0b2220b75fd5cf3980576b1a31f9c4ceb9f99f"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.22.3"
terra_version = "0.22.3"
timestamp = 1678827878.136886
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937703767"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.22.4"
terra_version = "0.22.4"
timestamp = 1678827878.136888
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994628005"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.22.4"
terra_version = "0.22.4"
timestamp = 1678827878.13689
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994627910"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.23.0"
terra_version = "0.23.0"
timestamp = 1678827878.136893
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052483522"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.23.0"
terra_version = "0.23.0"
timestamp = 1678827878.136895
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052483440"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.23.1"
terra_version = "0.23.1"
timestamp = 1678827878.136897
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231022161"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.23.1"
terra_version = "0.23.1"
timestamp = 1678827878.136899
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231022210"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.23.2"
terra_version = "0.23.2"
timestamp = 1678827878.136902
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414045863"

[[historical_test_results]]
test_type = "development"
passed = false
package = "qiskit-terra"
package_version = "0.24.0"
terra_version = "0.24.0"
timestamp = 1678827878.136904
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414046008"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.23.2"
terra_version = "0.23.2"
timestamp = 1678827878.126264
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414045904"

[configuration]
dependencies_files = []
extra_dependencies = [ "qiskit", "coverage", "pylint", "numpy==1.*,>=1.20.1", "pyquil==3.*,>=3.0.0", "black==20.*,>=20.8.0.b1", "flake8==3.*,>=3.8.1", "mypy==0.*,>=0.800.0", "pip-licenses==3.*,>=3.5.1", "pytest==6.*,>=6.2.2", "pytest-cov==2.*,>=2.11.1", "pytest-httpx==0.*,>=0.9.0", "pytest-mock==3.*,>=3.6.1",]
tests_command = [ "pytest",]
styles_check_command = [ "pylint -rn qiskit_rigetti tests",]
coverages_check_command = [ "coverage3 -m pytest", "coverage3 report --fail-under=80",]

[configuration.language]
name = "python"
versions = [ "3.6",]
