name = "qiskit-experiments"
url = "https://github.com/Qiskit-Extensions/qiskit-experiments"
description = "Qiskit Experiments is an open-source project for running characterizing, calibrating, and benchmarking experiments in Qiskit."
licence = "Apache 2.0"
labels = [ "algorithms",]
created_at = 1661785302.25299
updated_at = 1661785302.25299
tier = "Extensions"
website = "https://qiskit.org/ecosystem/experiments/"
tests_results = []
styles_results = []
coverages_results = []
skip_tests = true
historical_test_results = []
stars = 116
