name = "Qiskit IBM Runtime"
url = "https://github.com/qiskit/qiskit-ibm-runtime"
description = "Run Qiskit primitives on IBM Quantum hardware with built-in error suppression and mitigation."
licence = "Apache 2.0"
contact_info = ""
alternatives = ""
affiliations = "IBM"
labels = [ "IBM maintained", "Provider", "Partner",]
created_at = 1654696489.147673
updated_at = 1654696489.147699
stars = 118
group = "provider"
documentation = "https://docs.quantum.ibm.com/api/qiskit-ibm-runtime"
