name = "qiskit-qubit-reuse"
url = "https://github.com/qiskit-community/qiskit-qubit-reuse"
description = "A Qiskit transpiler stage plugin to enable qubit reuse via mid-circuit measurement and reset."
licence = "Apache License 2.0"
contact_info = "_No response_"
alternatives = "_No response_"
affiliations = "IBM"
labels = [ "Paper implementation", "Transpiler plugin",]
tier = "Community"
styles_results = []
coverages_results = []
skip_tests = false
stars = 7
group = "other"
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "1.0.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6782294567"
package_commit_hash = "af643eb09b22fc3833084b3112890b1aebdcbf92"
qiskit_version = "1.0.0"
timestamp = 1699348761.79962

[[tests_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6782294567"
qiskit_version = "0.45.0"
timestamp = 1699348334.090996

[[tests_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6782294567"
qiskit_version = "0.45.0"
timestamp = 1699348791.107908

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6545037619"
package_commit_hash = "62467839e8d4e263465c42118414e6e5eca3c776"
qiskit_version = "0.45.0"
timestamp = 1697534299.210143

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.44.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624756682"
qiskit_version = "0.44.2"
timestamp = 1698138743.534176

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = ""
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624756682"
qiskit_version = ""
timestamp = 1698139143.811313

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6782294567"
qiskit_version = "0.45.0"
timestamp = 1699348334.090996

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6782294567"
qiskit_version = "0.45.0"
timestamp = 1699348791.107908

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "1.0.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6782294567"
package_commit_hash = "af643eb09b22fc3833084b3112890b1aebdcbf92"
qiskit_version = "1.0.0"
timestamp = 1699348761.79962

