name = "qiskit-addon-aqc-tensor"
url = "https://github.com/Qiskit/qiskit-addon-opt-mapper"
description = "Mapping combinatorial optimization problems to quantum computers"
licence = "Apache License 2.0"
contact_info = "garrison@ibm.com"
labels = []
ibm_maintained = true
group = "Qiskit addon"
documentation = "https://qiskit.github.io/qiskit-addon-opt-mapper/"
uuid = "ef4e120a-f308-4462-86b6-10e7c7ba17c7"
badge = "https://qisk.it/e-ef4e120a"

[github]
url = "https://github.com/Qiskit/qiskit-addon-opt-mapper"
owner = "Qiskit"
repo = "qiskit-addon-opt-mapper"
stars = 13
homepage = "https://qiskit.github.io/qiskit-addon-opt-mapper/"
license = "Apache License 2.0"
description = "Mapping combinatorial optimization problems to quantum computers"
estimated_contributors = 23
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2026-01-07T11:38:44Z
last_activity = 2026-01-13T13:53:21Z

[pypi.qiskit-addon-opt-mapper]
package_name = "qiskit-addon-opt-mapper"
version = "0.1.0"
url = "https://pypi.org/project/qiskit-addon-opt-mapper/"
requires_qiskit = "<3"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2025-10-22T14:47:06Z
highest_supported_qiskit_version = "2.2.2"
last_month_downloads = 560
last_180_days_downloads = 560
