name = "qiskit-quimb"
url = "https://github.com/qiskit-community/qiskit-quimb"
description = "Simulate Qiskit circuits using quimb."
licence = "Apache License 2.0"
labels = [ "Circuit simulator",]
ibm_maintained = false
stars = 12
group = "other"
uuid = "a304538c-feb7-47b2-a41f-f9fbe41de87b"
