name = "Qiskit Rigetti Provider"
url = "https://github.com/rigetti/qiskit-rigetti"
description = "Rigetti Provider for Qiskit."
licence = "Apache 2.0"
labels = [ "Compute provider",]
ibm_maintained = false
created_at = 1678827878.136911
updated_at = 1678827878.136912
stars = 9
group = "provider"
uuid = "88a73f80-a247-4bb4-a6aa-f5da3ebd50c4"
