name = "Qiskit Inspect"
url = "https://github.com/neuralsorcerer/qiskit-inspect"
description = "Debugger, backend prefix tracing, and assertions for Qiskit."
licence = "Apache License 2.0"
contact_info = "soumyadip@soumyadipsarkar.com"
labels = []
group = "Other"
uuid = "1513e7fe-9390-4014-9c2a-f6c600ddf6ca"
badge = "https://qisk.it/e-1513e7fe"

[github]
url = "https://github.com/neuralsorcerer/qiskit-inspect"
owner = "neuralsorcerer"
repo = "qiskit-inspect"
stars = 1
homepage = "http://pypi.org/project/qiskit-inspect/"
license = "Apache License 2.0"
description = "Debugger, backend prefix tracing, and assertions for Qiskit"
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2025-11-11T09:28:39Z
last_activity = 2025-11-11T09:28:40Z
