name = "qiskit-ionq"
url = "https://github.com/Qiskit-Partners/qiskit-ionq"
description = "Project contains a provider that allows access to IonQ ion trap quantum systems."
licence = "Apache 2.0"
contact_info = ""
alternatives = ""
labels = [ "provider", "partner",]
created_at = 1670427446.011674
updated_at = 1670427446.011675
styles_results = []
coverages_results = []
tier = "Community"
skip_tests = false
stars = 30
[[tests_results]]
test_type = "development"
passed = true
package = "qiskit"
package_version = "0.23.0"
timestamp = 1670427446.003062
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3628097776"
package_commit_hash = "0df0d29fc44fb571e38530d20743a6e70e230865"

[[tests_results]]
test_type = "last passing version"
passed = true
package = "qiskit"
package_version = "0.22.3"
timestamp = 1670427446.011682
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3628097716"

[[tests_results]]
test_type = "stable"
passed = true
package = "qiskit"
package_version = "0.22.3"
timestamp = 1670427446.001605
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3628097716"

[[tests_results]]
test_type = "standard"
passed = true
package = "qiskit"
package_version = "0.22.3"
timestamp = 1670427446.003071
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3628097663"

[[historical_test_results]]
test_type = "standard"
passed = true
package = "qiskit"
package_version = "0.21.1"
timestamp = 1670427446.01164
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824121621"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit"
package_version = "0.21.1"
timestamp = 1670427446.011645
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824121621"

[[historical_test_results]]
test_type = "development"
passed = true
package = "qiskit"
package_version = "0.22.0"
timestamp = 1670427446.011647
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3180921277"
package_commit_hash = "53e215c31cf3aea51a623dc22883ac92fe74d0b9"

[[historical_test_results]]
test_type = "standard"
passed = true
package = "qiskit"
package_version = "0.21.2"
timestamp = 1670427446.011649
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225639640"

[[historical_test_results]]
test_type = "stable"
passed = true
package = "qiskit"
package_version = "0.21.2"
timestamp = 1670427446.011652
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225639611"

[[historical_test_results]]
test_type = "standard"
passed = true
package = "qiskit"
package_version = "0.22.0"
timestamp = 1670427446.011654
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368226131"

[[historical_test_results]]
test_type = "stable"
passed = true
package = "qiskit"
package_version = "0.22.0"
timestamp = 1670427446.011656
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368226160"

[[historical_test_results]]
test_type = "stable"
passed = true
package = "qiskit"
package_version = "0.22.2"
timestamp = 1670427446.011659
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521954337"

[[historical_test_results]]
test_type = "standard"
passed = true
package = "qiskit"
package_version = "0.22.2"
timestamp = 1670427446.011661
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521954292"

[[historical_test_results]]
test_type = "standard"
passed = true
package = "qiskit"
package_version = "0.22.3"
timestamp = 1670427446.011665
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3628097663"

[[historical_test_results]]
test_type = "development"
passed = true
package = "qiskit"
package_version = "0.23.0"
timestamp = 1670427446.011667
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3628097776"
package_commit_hash = "0df0d29fc44fb571e38530d20743a6e70e230865"

[[historical_test_results]]
test_type = "stable"
passed = true
package = "qiskit"
package_version = "0.22.3"
timestamp = 1670427446.001605
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3628097716"

[configuration]
dependencies_files = [ "requirements.txt", "requirements-test.txt",]
extra_dependencies = []
tests_command = [ "python setup.py test",]
styles_check_command = [ "pylint -rn --rcfile=./.pylintrc qiskit_ionq test",]
coverages_check_command = []

[configuration.language]
name = "python"
versions = [ "3.7",]
