name = "Qiskit SAT Synthesis"
url = "https://github.com/qiskit-community/qiskit-sat-synthesis"
description = "Synthesis plugins for Cliffords, linear functions, permutations, and more."
licence = "Apache License 2.0"
contact_info = "alexi@il.ibm.com"
affiliations = "IBM"
labels = []
group = "High-level synthesis plugin"
uuid = "2e6b95b1-5046-4a83-8842-c0b6ea36ec12"
badge = "https://qisk.it/e-2e6b95b1"

[github]
url = "https://github.com/qiskit-community/qiskit-sat-synthesis"
owner = "qiskit-community"
repo = "qiskit-sat-synthesis"
stars = 9
license = "Apache License 2.0"
estimated_contributors = 2
total_dependent_repositories = 2
total_dependent_packages = 0
last_commit = 2024-12-24T07:07:21Z

[pypi.qiskit-sat-synthesis]
package_name = "qiskit-sat-synthesis"
version = "0.0.2"
url = "https://pypi.org/project/qiskit-sat-synthesis/"
requires_qiskit = ">=1.2.0"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2025-10-22T14:47:06Z
highest_supported_qiskit_version = "2.2.2"
last_month_downloads = 17
last_180_days_downloads = 142
