name = "Qiskit QEC"
url = "https://github.com/qiskit-community/qiskit-qec"
description = "For quantum error correction developers, experimentalists, and theorists."
licence = "Apache 2.0"
labels = [ "Algorithms", "Circuit building tool", "Error correction",]
ibm_maintained = false
created_at = 1662992390.122591
updated_at = 1662992390.122597
stars = 89
group = "other"
uuid = "f00eb2fa-f4f1-4e97-8e59-3013e424e0f5"
