name = "qlasskit"
url = "https://github.com/dakk/qlasskit"
description = "Write classical algorithms in pure Python and translate them into quantum circuits."
licence = "Apache License 2.0"
contact_info = "gessadavide@gmail.com"
affiliations = "The project is partially funded by the UnitaryFund microgrant."
labels = [ "Converter",]
ibm_maintained = false
website = "https://dakk.github.io/qlasskit/"
stars = 62
group = "other"
uuid = "42b0f0f5-bdbd-4008-8749-955b496dab08"
