name = "qlasskit"
url = "https://github.com/dakk/qlasskit"
description = "Qlasskit is a Python library that allows quantum developers to write classical algorithms in pure Python and translate them into quantum circuits."
licence = "Apache License 2.0"
contact_info = "gessadavide@gmail.com"
alternatives = "_No response_"
affiliations = "The project is partially funded by the UnitaryFund microgrant."
labels = [ "Converter",]
tier = "Community"
website = "https://dakk.github.com/qlasskit"
tests_results = []
styles_results = []
coverages_results = []
skip_tests = false
historical_test_results = []
group = "other"
