name = "qlasskit"
url = "https://github.com/dakk/qlasskit"
description = "Write classical algorithms in pure Python and translate them into quantum circuits."
licence = "Apache License 2.0"
contact_info = "gessadavide@gmail.com"
labels = []
website = "https://dakk.github.io/qlasskit/"
group = "Converter"
uuid = "42b0f0f5-bdbd-4008-8749-955b496dab08"
badge = "https://qisk.it/e-42b0f0f5"

[github]
url = "https://github.com/dakk/qlasskit"
owner = "dakk"
repo = "qlasskit"
stars = 71
homepage = "https://dakk.github.io/qlasskit/"
license = "Apache License 2.0"
description = "A python-to-quantum compiler"
estimated_contributors = 6
total_dependent_repositories = 3
total_dependent_packages = 0
last_commit = 2025-12-12T10:24:44Z
last_activity = 2025-12-23T06:59:42Z

[pypi.qlasskit]
package_name = "qlasskit"
version = "0.1.36"
url = "https://pypi.org/project/qlasskit/"
last_month_downloads = 151
last_180_days_downloads = 776
