name = "qlasskit"
url = "https://github.com/dakk/qlasskit"
description = "Write classical algorithms in pure Python and translate them into quantum circuits."
licence = "Apache License 2.0"
contact_info = "gessadavide@gmail.com"
affiliations = "The project is partially funded by the UnitaryFund microgrant."
labels = [ "Converter",]
website = "https://dakk.github.io/qlasskit/"
group = "other"
uuid = "42b0f0f5-bdbd-4008-8749-955b496dab08"
badge = "[![Qiskit Ecosystem](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fqiskit.github.io%2Fecosystem%2Fb%2F42b0f0f5)](https://qisk.it/e)"

[github]
url = "https://github.com/dakk/qlasskit"
owner = "dakk"
repo = "qlasskit"
stars = 69
homepage = "https://dakk.github.io/qlasskit/"
license = "Apache License 2.0"
description = "A python-to-quantum compiler"
estimated_contributors = 5
total_dependent_repositories = 3
total_dependent_packages = 0
last_commit = 2025-11-02T10:58:28Z

[pypi.qlasskit]
package_name = "qlasskit"
version = "0.1.36"
url = "https://pypi.org/project/qlasskit/"
