name = "qMuVi"
url = "https://github.com/garymooney/qmuvi"
description = "Convert circuits into audiovisual experiences, bridging the gap between complex quantum computations and human perception."
licence = "GNU Library or \"Lesser\" General Public License (LGPL)"
contact_info = "gary.mooney4444@gmail.com"
affiliations = "The University of Melbourne"
labels = [ "Converter",]
group = "other"
documentation = "https://garymooney.github.io/qmuvi/"
uuid = "9d4da903-9823-4ae3-a80c-22821b62931e"
badge = "[![Qiskit Ecosystem](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fqiskit.github.io%2Fecosystem%2Fb%2F9d4da903)](https://qisk.it/e)"

[github]
url = "https://github.com/garymooney/qmuvi"
owner = "garymooney"
repo = "qmuvi"
stars = 16
homepage = "https://garymooney.github.io/qmuvi/"
license = "GNU Lesser General Public License v2.1"
description = "qMuVi - A python package that converts quantum circuits into audiovisual experiences, bridging the gap between complex quantum computations and human perception. Render music videos that reveal the evolution of quantum states during algorithm processing, making quantum computing more intuitive and accessible."
estimated_contributors = 4
total_dependent_repositories = 4
total_dependent_packages = 0
last_commit = 2025-09-04T08:49:29Z

[pypi.qmuvi]
package_name = "qmuvi"
version = "0.3.0"
url = "https://pypi.org/project/qmuvi/"
requires_qiskit = "<3.0.0,>=2.1.2"
compatible_with_qiskit_v1 = false
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2025-10-22T14:47:06Z
highest_supported_qiskit_version = "2.2.2"
