name = "qMuVi"
url = "https://github.com/garymooney/qmuvi"
description = "Convert circuits into audiovisual experiences, bridging the gap between complex quantum computations and human perception."
licence = "GNU Library or \"Lesser\" General Public License (LGPL)"
contact_info = "gary.mooney4444@gmail.com"
affiliations = "The University of Melbourne"
labels = [ "Converter",]
ibm_maintained = false
stars = 16
group = "other"
documentation = "https://garymooney.github.io/qmuvi/"
uuid = "9d4da903-9823-4ae3-a80c-22821b62931e"
