name = "qMuVi"
url = "https://github.com/garymooney/qmuvi"
description = "Convert circuits into audiovisual experiences, bridging the gap between complex quantum computations and human perception. Render music videos that reveal the evolution of quantum states, making quantum computing more intuitive and accessible."
licence = "GNU Library or \"Lesser\" General Public License (LGPL)"
contact_info = "gary.mooney4444@gmail.com"
alternatives = "_No response_"
affiliations = "The University of Melbourne"
labels = [ "Converter", "Visualization", "Education",]
tier = "Community"
documentation = "https://garymooney.github.io/qmuvi/"
tests_results = []
styles_results = []
coverages_results = []
skip_tests = false
historical_test_results = []
group = "other"
