name = "QoptKIT"
url = "https://github.com/SOQCSAdmin/QoptKIT"
description = "Optical circuits in Qiskit. Translate Qiskit circuits to quantum-optical circuits made of phase shifters and beamsplitters, simulate the circuit, then translate the outcome back to a qubit encoding."
licence = "Apache License 2.0"
contact_info = "soqcslib@gmail.com"
alternatives = "_No response_"
affiliations = "National University of Ireland Maynooth"
labels = [ "Circuit simulator",]
stars = 1
group = "other"
documentation = "https://soqcsadmin.github.io/QoptKIT/"
