name = "QoptKIT"
url = "https://github.com/SOQCSAdmin/QoptKIT"
description = "Translate Qiskit circuits to quantum-optical circuits, simulate them, then translate results back to qubit encodings."
licence = "Apache License 2.0"
contact_info = "soqcslib@gmail.com"
affiliations = "National University of Ireland Maynooth"
labels = [ "Circuit simulator", "Converter",]
ibm_maintained = false
stars = 1
group = "other"
documentation = "https://soqcsadmin.github.io/QoptKIT/"
