name = "QoptKIT"
url = "https://github.com/SOQCSAdmin/QoptKIT"
description = "Translate Qiskit circuits to quantum-optical circuits, simulate them, then translate the results back to qubit encodings."
licence = "Apache License 2.0"
contact_info = "soqcslib@gmail.com"
affiliations = "National University of Ireland Maynooth"
labels = []
group = "Converter"
documentation = "https://soqcsadmin.github.io/QoptKIT/"
uuid = "d94095eb-85cf-42ea-a70e-fa1735225b68"
badge = "https://qisk.it/e-d94095eb"

[github]
url = "https://github.com/SOQCSAdmin/QoptKIT"
owner = "SOQCSAdmin"
repo = "QoptKIT"
stars = 1
homepage = "https://soqcsadmin.github.io/QoptKIT/"
license = "Apache License 2.0"
description = "Optical circuits in Qiskit. Translate Qiskit circuits to quantum-optical circuits made of phase shifters and beamsplitters, simulat..."
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2024-03-10T17:29:40Z
