name = "QPong"
url = "https://github.com/HuangJunye/QPong"
description = "A quantum version of the classic game Pong built with Qiskit and PyGame"
licence = "Apache 2.0"
contact_info = "ukskosana@gmail.com"
alternatives = "_No response_"
labels = [ "Game",]
created_at = 1678827877.979398
updated_at = 1678827877.979398
stars = 116
group = "other"
