name = "QPong"
url = "https://github.com/HuangJunye/QPong"
description = "A quantum version of the classic game Pong built with Qiskit and PyGame"
licence = "Apache 2.0"
contact_info = "ukskosana@gmail.com"
labels = [ "Game",]
ibm_maintained = false
created_at = 1678827877.979398
updated_at = 1678827877.979398
stars = 120
group = "other"
uuid = "56eb0ca6-4dd5-4954-a059-96256fd0ab26"
