name = "QPong"
url = "https://github.com/HuangJunye/QPong"
description = "A quantum version of the classic game Pong built with Qiskit and PyGame"
licence = "Apache 2.0"
contact_info = "ukskosana@gmail.com"
alternatives = "_No response_"
labels = [ "Game",]
created_at = 1678827877.979398
updated_at = 1678827877.979398
styles_results = []
coverages_results = []
tier = "Community"
skip_tests = false
stars = 110
[[tests_results]]
test_type = "development"
passed = false
package = "qiskit-terra"
package_version = "0.24.0"
terra_version = "0.24.0"
timestamp = 1678827877.970614
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414046211"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"

[[tests_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.23.2"
terra_version = "0.23.2"
timestamp = 1678827877.968673
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414046214"

[[tests_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.20.1"
terra_version = "0.20.1"
timestamp = 1678827877.970622
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414046210"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.20.1"
terra_version = "0.20.1"
timestamp = 1678827877.979363
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2998938879"

[[historical_test_results]]
test_type = "development"
passed = false
package = "qiskit-terra"
package_version = "0.22.0"
terra_version = "0.22.0"
timestamp = 1678827877.979368
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3180920605"
package_commit_hash = "53e215c31cf3aea51a623dc22883ac92fe74d0b9"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.21.2"
terra_version = "0.21.2"
timestamp = 1678827877.97937
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225639040"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.22.0"
terra_version = "0.22.0"
timestamp = 1678827877.979373
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368224830"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.22.2"
terra_version = "0.22.2"
timestamp = 1678827877.979375
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521952730"

[[historical_test_results]]
test_type = "development"
passed = false
package = "qiskit-terra"
package_version = "0.23.0"
terra_version = "0.23.0"
timestamp = 1678827877.979377
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937704251"
package_commit_hash = "af0b2220b75fd5cf3980576b1a31f9c4ceb9f99f"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.22.3"
terra_version = "0.22.3"
timestamp = 1678827877.97938
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937704190"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.22.4"
terra_version = "0.22.4"
timestamp = 1678827877.979382
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994628345"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.23.0"
terra_version = "0.23.0"
timestamp = 1678827877.979384
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052484060"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.23.1"
terra_version = "0.23.1"
timestamp = 1678827877.979387
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231022588"

[[historical_test_results]]
test_type = "development"
passed = false
package = "qiskit-terra"
package_version = "0.24.0"
terra_version = "0.24.0"
timestamp = 1678827877.979389
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414046211"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.20.1"
terra_version = "0.20.1"
timestamp = 1678827877.979391
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414046210"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.23.2"
terra_version = "0.23.2"
timestamp = 1678827877.968673
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414046214"

[configuration]
dependencies_files = [ "requirements.txt", "requirements-dev.txt",]
extra_dependencies = [ "pytest",]
tests_command = [ "pytest",]
styles_check_command = [ "pylint -rn qpong tests",]
coverages_check_command = [ "coverage3 run -m pytest", "coverage3 report --fail-under=80",]

[configuration.language]
name = "python"
versions = [ "3.9",]
