name = "QPong"
url = "https://github.com/HuangJunye/QPong"
description = "A quantum version of the classic game Pong built with Qiskit and PyGame"
licence = "Apache 2.0"
contact_info = "ukskosana@gmail.com"
alternatives = "_No response_"
labels = [ "Game",]
created_at = 1678827877.979398
updated_at = 1678827877.979398
tier = "Community"
styles_results = []
coverages_results = []
skip_tests = false
stars = 112
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6310547040"
package_commit_hash = "6e80e89e18da2691a86d4e2050db2e5479043b16"
qiskit_version = "0.45.0"
timestamp = 1695720590.203191

[[tests_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6310547040"
qiskit_version = "0.44.1"
timestamp = 1695720134.51514

[[tests_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.36.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6310547040"
qiskit_version = "0.36.1"
timestamp = 1695720653.037476

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.36.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2998938879"
qiskit_version = "0.36.1"
timestamp = 1692696186.206015

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3180920605"
package_commit_hash = "53e215c31cf3aea51a623dc22883ac92fe74d0b9"
qiskit_version = "0.39.0"
timestamp = 1692696186.206018

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.38.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225639040"
qiskit_version = "0.38.0"
timestamp = 1692696186.206021

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368224830"
qiskit_version = "0.39.0"
timestamp = 1692696186.206024

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.39.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521952730"
qiskit_version = "0.39.2"
timestamp = 1692696186.206027

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937704251"
package_commit_hash = "af0b2220b75fd5cf3980576b1a31f9c4ceb9f99f"
qiskit_version = "0.40.0"
timestamp = 1692696186.206031

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.39.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937704190"
qiskit_version = "0.39.4"
timestamp = 1692696186.206034

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.39.5"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994628345"
qiskit_version = "0.39.5"
timestamp = 1692696186.206037

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052484060"
qiskit_version = "0.40.0"
timestamp = 1692696186.20604

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.41.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231022588"
qiskit_version = "0.41.0"
timestamp = 1692696186.206043

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.43.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414046211"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"
qiskit_version = "0.43.0"
timestamp = 1692696186.206046

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.41.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414046214"
qiskit_version = "0.41.1"
timestamp = 1692696186.206049

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6310547040"
qiskit_version = "0.44.1"
timestamp = 1695720134.51514

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.36.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6310547040"
qiskit_version = "0.36.1"
timestamp = 1695720653.037476

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6310547040"
package_commit_hash = "6e80e89e18da2691a86d4e2050db2e5479043b16"
qiskit_version = "0.45.0"
timestamp = 1695720590.203191

[configuration]
dependencies_files = [ "requirements.txt", "requirements-dev.txt",]
extra_dependencies = [ "pytest",]
debian_dependencies = []
tests_command = [ "pytest",]
styles_check_command = [ "pylint -rn qpong tests",]
coverages_check_command = [ "coverage3 run -m pytest", "coverage3 report --fail-under=80",]

[configuration.language]
name = "python"
versions = [ "3.9",]
