name = "qtcodes"
url = "https://github.com/yaleqc/qtcodes"
description = "Qiskit Topological Codes"
licence = "Apache 2.0"
contact_info = ""
alternatives = ""
labels = [ "Error correction",]
created_at = 1678827878.827901
updated_at = 1678827878.827902
tier = "Community"
skip_tests = false
stars = 82
[[tests_results]]
test_type = "development"
passed = true
package = "qiskit-terra"
package_version = "0.24.0"
terra_version = "0.24.0"
timestamp = 1678827878.819181
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414044195"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"

[[tests_results]]
test_type = "last passing version"
passed = true
package = "qiskit-terra"
package_version = "0.23.2"
terra_version = "0.23.2"
timestamp = 1678827878.819186
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414044129"

[[tests_results]]
test_type = "stable"
passed = true
package = "qiskit-terra"
package_version = "0.23.2"
terra_version = "0.23.2"
timestamp = 1678827878.819189
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414044129"

[[tests_results]]
test_type = "standard"
passed = true
package = "qiskit-terra"
package_version = "0.23.2"
terra_version = "0.23.2"
timestamp = 1678827878.817194
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414044094"

[[styles_results]]
style_type = "pylint"
passed = false

[[coverages_results]]
coverage_type = ""
passed = false

[[historical_test_results]]
test_type = "standard"
passed = true
package = "qiskit-terra"
package_version = "0.20.2"
terra_version = "0.20.2"
timestamp = 1678827878.827841

[[historical_test_results]]
test_type = "development"
passed = true
package = "qiskit-terra"
package_version = "0.21.0"
terra_version = "0.21.0"
timestamp = 1678827878.827846

[[historical_test_results]]
test_type = "stable"
passed = true
package = "qiskit-terra"
package_version = "0.20.2"
terra_version = "0.20.2"
timestamp = 1678827878.827849

[[historical_test_results]]
test_type = "standard"
passed = true
package = "qiskit-terra"
package_version = "0.21.0"
terra_version = "0.21.0"
timestamp = 1678827878.827851
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2617548269"

[[historical_test_results]]
test_type = "stable"
passed = true
package = "qiskit-terra"
package_version = "0.21.0"
terra_version = "0.21.0"
timestamp = 1678827878.827854
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2617548269"

[[historical_test_results]]
test_type = "standard"
passed = true
package = "qiskit-terra"
package_version = "0.21.1"
terra_version = "0.21.1"
timestamp = 1678827878.827856
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824121068"

[[historical_test_results]]
test_type = "stable"
passed = true
package = "qiskit-terra"
package_version = "0.21.1"
terra_version = "0.21.1"
timestamp = 1678827878.827858
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824121068"

[[historical_test_results]]
test_type = "development"
passed = true
package = "qiskit-terra"
package_version = "0.22.0"
terra_version = "0.22.0"
timestamp = 1678827878.827861
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3180919232"
package_commit_hash = "53e215c31cf3aea51a623dc22883ac92fe74d0b9"

[[historical_test_results]]
test_type = "standard"
passed = true
package = "qiskit-terra"
package_version = "0.21.2"
terra_version = "0.21.2"
timestamp = 1678827878.827863
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3180919153"

[[historical_test_results]]
test_type = "stable"
passed = true
package = "qiskit-terra"
package_version = "0.21.2"
terra_version = "0.21.2"
timestamp = 1678827878.827865
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225637904"

[[historical_test_results]]
test_type = "stable"
passed = true
package = "qiskit-terra"
package_version = "0.22.0"
terra_version = "0.22.0"
timestamp = 1678827878.827867
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368223904"

[[historical_test_results]]
test_type = "standard"
passed = true
package = "qiskit-terra"
package_version = "0.22.0"
terra_version = "0.22.0"
timestamp = 1678827878.827869
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368223902"

[[historical_test_results]]
test_type = "standard"
passed = true
package = "qiskit-terra"
package_version = "0.22.2"
terra_version = "0.22.2"
timestamp = 1678827878.827871
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521950844"

[[historical_test_results]]
test_type = "stable"
passed = true
package = "qiskit-terra"
package_version = "0.22.2"
terra_version = "0.22.2"
timestamp = 1678827878.827874
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521950941"

[[historical_test_results]]
test_type = "development"
passed = true
package = "qiskit-terra"
package_version = "0.23.0"
terra_version = "0.23.0"
timestamp = 1678827878.827876
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937701356"
package_commit_hash = "af0b2220b75fd5cf3980576b1a31f9c4ceb9f99f"

[[historical_test_results]]
test_type = "stable"
passed = true
package = "qiskit-terra"
package_version = "0.22.3"
terra_version = "0.22.3"
timestamp = 1678827878.827878
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937701333"

[[historical_test_results]]
test_type = "standard"
passed = true
package = "qiskit-terra"
package_version = "0.22.3"
terra_version = "0.22.3"
timestamp = 1678827878.82788
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937701250"

[[historical_test_results]]
test_type = "standard"
passed = true
package = "qiskit-terra"
package_version = "0.22.4"
terra_version = "0.22.4"
timestamp = 1678827878.827882
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994625932"

[[historical_test_results]]
test_type = "stable"
passed = true
package = "qiskit-terra"
package_version = "0.23.0"
terra_version = "0.23.0"
timestamp = 1678827878.827885
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052481542"

[[historical_test_results]]
test_type = "standard"
passed = true
package = "qiskit-terra"
package_version = "0.23.0"
terra_version = "0.23.0"
timestamp = 1678827878.827887
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052481466"

[[historical_test_results]]
test_type = "stable"
passed = true
package = "qiskit-terra"
package_version = "0.23.1"
terra_version = "0.23.1"
timestamp = 1678827878.827889
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231020538"

[[historical_test_results]]
test_type = "standard"
passed = true
package = "qiskit-terra"
package_version = "0.23.1"
terra_version = "0.23.1"
timestamp = 1678827878.827891
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231020492"

[[historical_test_results]]
test_type = "stable"
passed = true
package = "qiskit-terra"
package_version = "0.23.2"
terra_version = "0.23.2"
timestamp = 1678827878.827893
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414044129"

[[historical_test_results]]
test_type = "development"
passed = true
package = "qiskit-terra"
package_version = "0.24.0"
terra_version = "0.24.0"
timestamp = 1678827878.827895
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414044195"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"

[[historical_test_results]]
test_type = "standard"
passed = true
package = "qiskit-terra"
package_version = "0.23.2"
terra_version = "0.23.2"
timestamp = 1678827878.817194
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414044094"

[configuration]
dependencies_files = []
extra_dependencies = [ "qiskit", "coverage", "pylint", "numpy", "matplotlib>=3.3.0", "retworkx>=0.10.0", "tqdm", "pylatexenc", "IPython", "mypy", "black", "pytest",]
tests_command = [ "python -m unittest",]
styles_check_command = [ "pylint -rn qtcodes",]
coverages_check_command = [ "coverage3 -m pytest", "coverage3 report --fail-under=80",]

[configuration.language]
name = "python"
versions = [ "3.6",]
