name = "qtcodes"
url = "https://github.com/yaleqc/qtcodes"
description = "Qiskit Topological Codes"
licence = "Apache 2.0"
contact_info = ""
alternatives = ""
labels = [ "Error correction",]
created_at = 1678827878.827901
updated_at = 1678827878.827902
tier = "Community"
skip_tests = true
stars = 83
[[tests_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936781765"
package_commit_hash = "0b51250e219ca303654fc28a318c21366584ccd3"
qiskit_version = "0.45.0"
timestamp = 1692696030.514374

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936781765"
qiskit_version = "0.44.1"
timestamp = 1692696030.686452

[[tests_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936781765"
qiskit_version = "0.44.1"
timestamp = 1692696030.686456

[[tests_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936781765"
qiskit_version = "0.44.1"
timestamp = 1692696030.68646

[[styles_results]]
passed = false
style_type = "pylint"

[[coverages_results]]
passed = false
coverage_type = ""

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.36.2"
qiskit_version = "0.36.2"
timestamp = 1692696030.686474

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.37.0"
qiskit_version = "0.37.0"
timestamp = 1692696030.686478

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.36.2"
qiskit_version = "0.36.2"
timestamp = 1692696030.686481

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.37.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2617548269"
qiskit_version = "0.37.0"
timestamp = 1692696030.686485

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.37.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2617548269"
qiskit_version = "0.37.0"
timestamp = 1692696030.686489

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.37.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824121068"
qiskit_version = "0.37.1"
timestamp = 1692696030.686493

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.37.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824121068"
qiskit_version = "0.37.1"
timestamp = 1692696030.686497

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3180919232"
package_commit_hash = "53e215c31cf3aea51a623dc22883ac92fe74d0b9"
qiskit_version = "0.39.0"
timestamp = 1692696030.686501

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.38.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3180919153"
qiskit_version = "0.38.0"
timestamp = 1692696030.686505

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.38.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225637904"
qiskit_version = "0.38.0"
timestamp = 1692696030.686508

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368223904"
qiskit_version = "0.39.0"
timestamp = 1692696030.686512

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368223902"
qiskit_version = "0.39.0"
timestamp = 1692696030.686516

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.39.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521950844"
qiskit_version = "0.39.2"
timestamp = 1692696030.68652

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.39.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521950941"
qiskit_version = "0.39.2"
timestamp = 1692696030.686523

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937701356"
package_commit_hash = "af0b2220b75fd5cf3980576b1a31f9c4ceb9f99f"
qiskit_version = "0.40.0"
timestamp = 1692696030.686527

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.39.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937701333"
qiskit_version = "0.39.4"
timestamp = 1692696030.68653

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.39.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937701250"
qiskit_version = "0.39.4"
timestamp = 1692696030.686534

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.39.5"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994625932"
qiskit_version = "0.39.5"
timestamp = 1692696030.686538

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052481542"
qiskit_version = "0.40.0"
timestamp = 1692696030.686541

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052481466"
qiskit_version = "0.40.0"
timestamp = 1692696030.686544

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.41.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231020538"
qiskit_version = "0.41.0"
timestamp = 1692696030.686548

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.41.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231020492"
qiskit_version = "0.41.0"
timestamp = 1692696030.686552

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.41.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414044129"
qiskit_version = "0.41.1"
timestamp = 1692696030.686556

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.43.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414044195"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"
qiskit_version = "0.43.0"
timestamp = 1692696030.68656

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.41.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414044094"
qiskit_version = "0.41.1"
timestamp = 1692696030.686563

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936781765"
qiskit_version = "0.44.1"
timestamp = 1692696030.686571

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936781765"
qiskit_version = "0.44.1"
timestamp = 1692696030.686574

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936781765"
package_commit_hash = "0b51250e219ca303654fc28a318c21366584ccd3"
qiskit_version = "0.45.0"
timestamp = 1692696030.514374

[configuration]
dependencies_files = []
extra_dependencies = [ "qiskit", "coverage", "pylint", "numpy", "matplotlib>=3.3.0", "retworkx>=0.10.0", "tqdm", "pylatexenc", "IPython", "mypy", "black", "pytest",]
tests_command = [ "python -m unittest",]
styles_check_command = [ "pylint -rn qtcodes",]
coverages_check_command = [ "coverage3 -m pytest", "coverage3 report --fail-under=80",]

[configuration.language]
name = "python"
versions = [ "3.6",]
