name = "Quantum Inspire SDK"
url = "https://github.com/QuTech-Delft/quantuminspire"
description = "This platform allows you to execute quantum algorithms using the cQASM language."
licence = "Apache 2.0"
labels = [ "Algorithms",]
created_at = 1678827878.401835
updated_at = 1678827878.401836
stars = 62
group = "other"
