name = "quantumcat"
url = "https://github.com/artificial-brain/quantumcat"
description = "quantumcat is a platform-independent, open-source, high-level quantum computing library, which allows the quantum community to focus on developing platform-independent quantum applications without much effort"
licence = "Apache 2.0"
labels = [ "Algorithms", "Converter",]
created_at = 1678827878.289276
updated_at = 1678827878.289277
tier = "Community"
skip_tests = true
stars = 21
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936780773"
package_commit_hash = "0b51250e219ca303654fc28a318c21366584ccd3"
qiskit_version = "0.45.0"
timestamp = 1692695925.156435

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936780773"
qiskit_version = "0.44.1"
timestamp = 1692695925.165703

[[tests_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936780773"
qiskit_version = "0.44.1"
timestamp = 1692695925.027478

[[tests_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.26.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936780773"
qiskit_version = "0.26.2"
timestamp = 1692695925.156452

[[styles_results]]
passed = false
style_type = "pylint"

[[coverages_results]]
passed = false
coverage_type = ""

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.37.0"
qiskit_version = "0.37.0"
timestamp = 1692695925.156465

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.27.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2998938614"
qiskit_version = "0.27.0"
timestamp = 1692695925.156469

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3180920000"
package_commit_hash = "53e215c31cf3aea51a623dc22883ac92fe74d0b9"
qiskit_version = "0.39.0"
timestamp = 1692695925.156472

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.38.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225638565"
qiskit_version = "0.38.0"
timestamp = 1692695925.156475

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368224447"
qiskit_version = "0.39.0"
timestamp = 1692695925.156478

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.39.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521951857"
qiskit_version = "0.39.2"
timestamp = 1692695925.156481

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937703088"
package_commit_hash = "af0b2220b75fd5cf3980576b1a31f9c4ceb9f99f"
qiskit_version = "0.40.0"
timestamp = 1692695925.156484

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.39.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937703035"
qiskit_version = "0.39.4"
timestamp = 1692695925.156487

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.39.5"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994627419"
qiskit_version = "0.39.5"
timestamp = 1692695925.15649

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052482715"
qiskit_version = "0.40.0"
timestamp = 1692695925.156493

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.41.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231021726"
qiskit_version = "0.41.0"
timestamp = 1692695925.156495

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.27.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414045179"
qiskit_version = "0.27.0"
timestamp = 1692695925.156498

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.43.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414045280"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"
qiskit_version = "0.43.0"
timestamp = 1692695925.156501

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.41.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414045216"
qiskit_version = "0.41.1"
timestamp = 1692695925.156504

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936780773"
package_commit_hash = "0b51250e219ca303654fc28a318c21366584ccd3"
qiskit_version = "0.45.0"
timestamp = 1692695925.15651

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.26.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936780773"
qiskit_version = "0.26.2"
timestamp = 1692695925.156513

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936780773"
qiskit_version = "0.44.1"
timestamp = 1692695925.027478

[configuration]
dependencies_files = [ "requirements.txt",]
extra_dependencies = [ "coverage", "pylint",]
tests_command = [ "pytest",]
styles_check_command = [ "pylint -rn quantumcat tests",]
coverages_check_command = [ "coverage3 -m pytest", "coverage3 report --fail-under=80",]

[configuration.language]
name = "python"
versions = [ "3.6",]
