name = "Quantum-MasterChef"
url = "https://github.com/shravanpatel30/Quantum-MasterChef.git"
description = "A unique and immersive quantum computing game that combines the excitement of culinary arts with the challenges of quantum mechanics to teach about qiskit and quantum computing."
licence = "Apache License 2.0"
contact_info = "shravanpatel4@gmail.com"
labels = [ "Circuit", "Education", "Game",]
group = "other"
