name = "Quantum Inspire SDK"
url = "https://github.com/QuTech-Delft/quantuminspire"
description = "This platform allows you to execute quantum algorithms using the cQASM language."
licence = "Apache 2.0"
labels = [ "Algorithms", "Software development kit",]
ibm_maintained = false
created_at = 1678827878.401835
updated_at = 1678827878.401836
stars = 67
group = "other"
uuid = "fb1cd889-961a-4029-bb8f-229e4c4e12a4"
