name = "Quantum MasterChef"
url = "https://github.com/shravanpatel30/Quantum-MasterChef"
description = "Combine the excitement of culinary arts with the challenges of quantum mechanics to learn about Qiskit and quantum computing."
licence = "Apache License 2.0"
contact_info = "shravanpatel4@gmail.com"
labels = []
group = "Game"
uuid = "e6e7a086-9b91-47b9-be78-f9c7bc680863"
badge = "https://qisk.it/e-e6e7a086"

[github]
url = "https://github.com/shravanpatel30/Quantum-MasterChef"
owner = "shravanpatel30"
repo = "Quantum-MasterChef"
stars = 2
license = "Apache License 2.0"
description = "Welcome to Quantum MasterChef, a unique and immersive quantum computing game that combines the excitement of culinary arts with the..."
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2024-05-10T00:23:52Z
