name = "quantum-tetris"
url = "https://github.com/olivierbrcknr/quantum-tetris"
description = "What would happen if you combine Tetris with a Quantum computer? The winning entry of the Quantum Design Jam from IBM and Parsons in October 2021 explores just that!"
licence = "Apache License 2.0"
contact_info = "_No response_"
alternatives = "_No response_"
affiliations = "_No response_"
labels = [ "Game",]
created_at = 1679712086.990215
updated_at = 1679712086.99022
tier = "Community"
tests_results = []
styles_results = []
coverages_results = []
skip_tests = true
historical_test_results = []
stars = 9
