name = "quantumcat"
url = "https://github.com/artificial-brain/quantumcat"
description = "quantumcat is a platform-independent, open-source, high-level quantum computing library, which allows the quantum community to focus on developing platform-independent quantum applications without much effort."
licence = "Apache 2.0"
labels = [ "Algorithms", "Converter",]
created_at = 1678827878.289276
updated_at = 1678827878.289277
stars = 22
group = "other"
