name = "Quantum Prototype Template"
url = "https://github.com/qiskit-community/quantum-prototype-template"
description = "A template repository for generating new quantum prototypes based on Qiskit."
licence = "Apache License 2.0"
contact_info = "_No response_"
alternatives = "_No response_"
affiliations = "Qiskit Community"
labels = [ "Productivity",]
stars = 37
group = "other"
