name = "quantuminspire"
url = "https://github.com/QuTech-Delft/quantuminspire"
description = "platform allows to execute quantum algorithms using the cQASM language."
licence = "Apache 2.0"
labels = [ "algorithms",]
created_at = 1678827878.401835
updated_at = 1678827878.401836
tier = "Community"
skip_tests = false
stars = 57
[[tests_results]]
test_type = "development"
passed = false
package = "qiskit-terra"
package_version = "0.24.0"
qiskit_version = "0.43.0"
timestamp = 1678827878.393127
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414044684"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"

[[tests_results]]
test_type = "last passing version"
passed = true
package = "qiskit-terra"
package_version = "0.22.4"
qiskit_version = "0.39.5"
timestamp = 1678827878.393133
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994626752"

[[tests_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.23.2"
qiskit_version = "0.41.1"
timestamp = 1678827878.393136
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414044614"

[[tests_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.23.2"
qiskit_version = "0.41.1"
timestamp = 1678827878.391164
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414044617"

[[styles_results]]
style_type = "pylint"
passed = false

[[coverages_results]]
coverage_type = ""
passed = true

[[historical_test_results]]
test_type = "standard"
passed = true
package = "qiskit-terra"
package_version = "0.20.2"
qiskit_version = "0.36.2"
timestamp = 1678827878.401772

[[historical_test_results]]
test_type = "development"
passed = false
package = "qiskit-terra"
package_version = "0.21.0"
qiskit_version = "0.37.0"
timestamp = 1678827878.401778

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.20.2"
qiskit_version = "0.36.2"
timestamp = 1678827878.40178

[[historical_test_results]]
test_type = "standard"
passed = true
package = "qiskit-terra"
package_version = "0.21.0"
qiskit_version = "0.37.0"
timestamp = 1678827878.401782
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2617548414"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.21.0"
qiskit_version = "0.37.0"
timestamp = 1678827878.401785
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2617548414"

[[historical_test_results]]
test_type = "standard"
passed = true
package = "qiskit-terra"
package_version = "0.21.1"
qiskit_version = "0.37.1"
timestamp = 1678827878.401787
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824121223"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.21.1"
qiskit_version = "0.37.1"
timestamp = 1678827878.401789
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824121223"

[[historical_test_results]]
test_type = "development"
passed = true
package = "qiskit-terra"
package_version = "0.22.0"
qiskit_version = "0.39.0"
timestamp = 1678827878.401792
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3180919652"
package_commit_hash = "53e215c31cf3aea51a623dc22883ac92fe74d0b9"

[[historical_test_results]]
test_type = "stable"
passed = true
package = "qiskit-terra"
package_version = "0.21.2"
qiskit_version = "0.38.0"
timestamp = 1678827878.401794
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225638229"

[[historical_test_results]]
test_type = "standard"
passed = true
package = "qiskit-terra"
package_version = "0.21.2"
qiskit_version = "0.38.0"
timestamp = 1678827878.401796
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225638217"

[[historical_test_results]]
test_type = "stable"
passed = true
package = "qiskit-terra"
package_version = "0.22.0"
qiskit_version = "0.39.0"
timestamp = 1678827878.401798
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368224170"

[[historical_test_results]]
test_type = "standard"
passed = true
package = "qiskit-terra"
package_version = "0.22.0"
qiskit_version = "0.39.0"
timestamp = 1678827878.4018
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368224153"

[[historical_test_results]]
test_type = "stable"
passed = true
package = "qiskit-terra"
package_version = "0.22.2"
qiskit_version = "0.39.2"
timestamp = 1678827878.401803
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521951415"

[[historical_test_results]]
test_type = "standard"
passed = true
package = "qiskit-terra"
package_version = "0.22.2"
qiskit_version = "0.39.2"
timestamp = 1678827878.401805
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521951365"

[[historical_test_results]]
test_type = "development"
passed = false
package = "qiskit-terra"
package_version = "0.23.0"
qiskit_version = "0.40.0"
timestamp = 1678827878.401807
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937702185"
package_commit_hash = "af0b2220b75fd5cf3980576b1a31f9c4ceb9f99f"

[[historical_test_results]]
test_type = "stable"
passed = true
package = "qiskit-terra"
package_version = "0.22.3"
qiskit_version = "0.39.4"
timestamp = 1678827878.401809
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937702004"

[[historical_test_results]]
test_type = "standard"
passed = true
package = "qiskit-terra"
package_version = "0.22.3"
qiskit_version = "0.39.4"
timestamp = 1678827878.401812
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937701988"

[[historical_test_results]]
test_type = "standard"
passed = true
package = "qiskit-terra"
package_version = "0.22.4"
qiskit_version = "0.39.5"
timestamp = 1678827878.401814
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994626686"

[[historical_test_results]]
test_type = "stable"
passed = true
package = "qiskit-terra"
package_version = "0.22.4"
qiskit_version = "0.39.5"
timestamp = 1678827878.401816
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994626752"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.23.0"
qiskit_version = "0.40.0"
timestamp = 1678827878.401818
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052482051"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.23.0"
qiskit_version = "0.40.0"
timestamp = 1678827878.40182
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052481946"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.23.1"
qiskit_version = "0.41.0"
timestamp = 1678827878.401823
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231021022"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.23.1"
qiskit_version = "0.41.0"
timestamp = 1678827878.401825
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231021114"

[[historical_test_results]]
test_type = "stable"
passed = false
package = "qiskit-terra"
package_version = "0.23.2"
qiskit_version = "0.41.1"
timestamp = 1678827878.401827
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414044614"

[[historical_test_results]]
test_type = "development"
passed = false
package = "qiskit-terra"
package_version = "0.24.0"
qiskit_version = "0.43.0"
timestamp = 1678827878.401829
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414044684"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"

[[historical_test_results]]
test_type = "standard"
passed = false
package = "qiskit-terra"
package_version = "0.23.2"
qiskit_version = "0.41.1"
timestamp = 1678827878.391164
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414044617"

[configuration]
dependencies_files = [ "requirements.txt",]
extra_dependencies = [ "coverage", "pylint", "qiskit",]
tests_command = [ "pytest src/tests",]
styles_check_command = [ "pylint -rn src",]
coverages_check_command = [ "coverage run --source=\"./src/quantuminspire\" -m unittest discover -s src/tests -t src -v",]

[configuration.language]
name = "python"
versions = [ "3.6",]
