name = "quantuminspire"
url = "https://github.com/QuTech-Delft/quantuminspire"
description = "platform allows to execute quantum algorithms using the cQASM language."
licence = "Apache 2.0"
labels = [ "Algorithms",]
created_at = 1678827878.401835
updated_at = 1678827878.401836
tier = "Community"
skip_tests = true
stars = 57
[[tests_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936781238"
package_commit_hash = "0b51250e219ca303654fc28a318c21366584ccd3"
qiskit_version = "0.45.0"
timestamp = 1692696301.518172

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936781238"
qiskit_version = "0.44.1"
timestamp = 1692696301.698695

[[tests_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936781238"
qiskit_version = "0.44.1"
timestamp = 1692696301.698699

[[tests_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936781238"
qiskit_version = "0.44.1"
timestamp = 1692696301.698703

[[styles_results]]
passed = false
style_type = "pylint"

[[coverages_results]]
passed = true
coverage_type = ""

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.36.2"
qiskit_version = "0.36.2"
timestamp = 1692696301.698718

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.37.0"
qiskit_version = "0.37.0"
timestamp = 1692696301.698721

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.36.2"
qiskit_version = "0.36.2"
timestamp = 1692696301.698725

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.37.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2617548414"
qiskit_version = "0.37.0"
timestamp = 1692696301.698729

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.37.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2617548414"
qiskit_version = "0.37.0"
timestamp = 1692696301.698732

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.37.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824121223"
qiskit_version = "0.37.1"
timestamp = 1692696301.698736

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.37.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824121223"
qiskit_version = "0.37.1"
timestamp = 1692696301.69874

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3180919652"
package_commit_hash = "53e215c31cf3aea51a623dc22883ac92fe74d0b9"
qiskit_version = "0.39.0"
timestamp = 1692696301.698743

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.38.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225638229"
qiskit_version = "0.38.0"
timestamp = 1692696301.698747

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.38.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225638217"
qiskit_version = "0.38.0"
timestamp = 1692696301.69875

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368224170"
qiskit_version = "0.39.0"
timestamp = 1692696301.698754

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368224153"
qiskit_version = "0.39.0"
timestamp = 1692696301.698757

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.39.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521951415"
qiskit_version = "0.39.2"
timestamp = 1692696301.698761

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.39.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521951365"
qiskit_version = "0.39.2"
timestamp = 1692696301.698764

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937702185"
package_commit_hash = "af0b2220b75fd5cf3980576b1a31f9c4ceb9f99f"
qiskit_version = "0.40.0"
timestamp = 1692696301.698768

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.39.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937702004"
qiskit_version = "0.39.4"
timestamp = 1692696301.698771

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.39.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937701988"
qiskit_version = "0.39.4"
timestamp = 1692696301.698775

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.39.5"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994626686"
qiskit_version = "0.39.5"
timestamp = 1692696301.698778

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.39.5"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994626752"
qiskit_version = "0.39.5"
timestamp = 1692696301.698781

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052482051"
qiskit_version = "0.40.0"
timestamp = 1692696301.698785

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052481946"
qiskit_version = "0.40.0"
timestamp = 1692696301.698788

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.41.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231021022"
qiskit_version = "0.41.0"
timestamp = 1692696301.698792

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.41.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231021114"
qiskit_version = "0.41.0"
timestamp = 1692696301.698795

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.41.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414044614"
qiskit_version = "0.41.1"
timestamp = 1692696301.698798

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.43.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414044684"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"
qiskit_version = "0.43.0"
timestamp = 1692696301.698802

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.41.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414044617"
qiskit_version = "0.41.1"
timestamp = 1692696301.698805

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936781238"
qiskit_version = "0.44.1"
timestamp = 1692696301.698812

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936781238"
qiskit_version = "0.44.1"
timestamp = 1692696301.698815

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936781238"
package_commit_hash = "0b51250e219ca303654fc28a318c21366584ccd3"
qiskit_version = "0.45.0"
timestamp = 1692696301.518172

[configuration]
dependencies_files = [ "requirements.txt",]
extra_dependencies = [ "coverage", "pylint", "qiskit",]
tests_command = [ "pytest src/tests",]
styles_check_command = [ "pylint -rn src",]
coverages_check_command = [ "coverage run --source=\"./src/quantuminspire\" -m unittest discover -s src/tests -t src -v",]

[configuration.language]
name = "python"
versions = [ "3.6",]
