name = "Quantum Debugger"
url = "https://github.com/quantag/qdb-qscore"
description = "Debug and visualize OpenQASM and Qiskit circuits directly from VSCode or any IDE that supports Microsoft's Debugger Adapter Protocol."
licence = "MIT license"
contact_info = "sergii.salata@quantag-it.com"
affiliations = "Quantag IT Solutions GmbH"
labels = [ "openqasm",]
website = "https://quantag-it.com/quantum/#/debugger"
group = "Tooling"
uuid = "3728ab3d-5b7b-416d-ad73-8e55a41091ca"
badge = "https://qisk.it/e-3728ab3d"

[github]
url = "https://github.com/quantag/qdb-qscore"
owner = "quantag"
repo = "qdb-qscore"
stars = 1
homepage = "https://quantum.quantag-it.com/"
license = "MIT License"
description = "Quantum circuit debugger backend"
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2025-12-02T11:57:10Z
last_activity = 2025-12-02T11:57:11Z
