name = "QuantumCircuits.jl"
url = "https://github.com/Adgnitio/QuantumCircuits.jl"
description = "QuantumCircuits is an open-source library written in Julia for working with quantum computers at the application level, especially for Quantum Finance and Quantum Machine Learning. It allows to creation and manipulation of the quantum circuits and executes them in Julia or convert them to Qiskit Python object. The library also contains the Quantum Binomial Tree implementation for derivative pricing."
licence = "GNU General Public License (GPL)"
contact_info = "rafal.pracht@adgnitio.com"
alternatives = "qiskit-finance, qiskit-machine-learning, Yao"
labels = [ "Paper implementation", "Machine learning", "Finance", "Julia", "Circuit",]
created_at = 1678827878.254124
updated_at = 1678827878.254125
tier = "Community"
styles_results = []
coverages_results = []
skip_tests = false
stars = 0
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936778549"
package_commit_hash = "0b51250e219ca303654fc28a318c21366584ccd3"
qiskit_version = "unknown"
timestamp = 1692695452.695431

[[tests_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936778549"
qiskit_version = "unknown"
timestamp = 1692695452.841178

[[tests_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936778549"
qiskit_version = "unknown"
timestamp = 1692695452.841182

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936778549"
qiskit_version = "unknown"
timestamp = 1692695452.841192

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936778549"
qiskit_version = "unknown"
timestamp = 1692695452.841195

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936778549"
package_commit_hash = "0b51250e219ca303654fc28a318c21366584ccd3"
qiskit_version = "unknown"
timestamp = 1692695452.695431

