name = "Quantum Prototype Template"
url = "https://github.com/qiskit-community/quantum-prototype-template"
description = "A template repository for generating new quantum prototypes based on Qiskit."
licence = "Apache License 2.0"
affiliations = "Qiskit Community"
labels = []
group = "Other"
uuid = "bb5d0da9-1523-4756-bda2-43d970b1fc51"
badge = "[![Qiskit Ecosystem](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fqiskit.github.io%2Fecosystem%2Fb%2Fbb5d0da9)](https://qisk.it/e)"

[github]
url = "https://github.com/qiskit-community/quantum-prototype-template"
owner = "qiskit-community"
repo = "quantum-prototype-template"
stars = 45
license = "Apache License 2.0"
description = "A template repository for generating new quantum prototypes based on Qiskit"
estimated_contributors = 7
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2024-09-11T15:59:49Z
last_activity = 2025-11-16T02:32:43Z

[pypi.vqls-prototype]
package_name = "vqls-prototype"
version = "0.2.0"
url = "https://pypi.org/project/vqls-prototype/"
requires_qiskit = ">=0.14.1"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2025-10-22T14:47:06Z
highest_supported_qiskit_version = "2.2.2"
last_month_downloads = 241
last_180_days_downloads = 472
