name = "Quantum Inspire SDK"
url = "https://github.com/QuTech-Delft/quantuminspire"
description = "This platform allows you to execute quantum algorithms using the cQASM language."
licence = "Apache 2.0"
labels = []
created_at = 1678827878.401835
updated_at = 1678827878.401836
group = "SDK"
uuid = "fb1cd889-961a-4029-bb8f-229e4c4e12a4"
badge = "https://qisk.it/e-fb1cd889"

[github]
url = "https://github.com/QuTech-Delft/quantuminspire"
owner = "QuTech-Delft"
repo = "quantuminspire"
stars = 76
license = "Apache License 2.0"
description = "Quantum Inspire SDK"
estimated_contributors = 9
total_dependent_repositories = 26
total_dependent_packages = 3
last_commit = 2026-01-29T09:17:12Z
last_activity = 2026-01-29T09:17:13Z

[pypi.quantuminspire]
package_name = "quantuminspire"
version = "3.3.1"
url = "https://pypi.org/project/quantuminspire/"
requires_qiskit = "==1.0.2"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = false
highest_supported_qiskit_release_date = 2024-03-07T23:51:19Z
highest_supported_qiskit_version = "1.0.2"
last_month_downloads = 3022
last_180_days_downloads = 13096
