name = "Quantum Network Coding"
url = "https://github.com/NagyTamas0122/QuantumNetworkCoding"
description = "Simulate Quantum Network Coding in Quantum Repeater Network environment."
licence = "Apache License 2.0"
contact_info = "mikrobi.0122@gmail.com"
affiliations = "Budapest University of Technology and Economics, Faculty of Electrical Engineering and Informatics"
labels = [ "Quantum information",]
group = "applications"
reference_paper = "https://journals.aps.org/pra/abstract/10.1103/PhysRevA.86.032331"
uuid = "0533cf1a-7462-484b-9c47-241cc6b3dcb5"
badge = "[![Qiskit Ecosystem](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fqiskit.github.io%2Fecosystem%2Fb%2F0533cf1a)](https://qisk.it/e)"

[github]
url = "https://github.com/NagyTamas0122/QuantumNetworkCoding"
owner = "NagyTamas0122"
repo = "QuantumNetworkCoding"
stars = 0
license = "Apache License 2.0"
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2025-11-03T11:37:50Z
