name = "Quantum Serverless"
url = "https://github.com/Qiskit-Extensions/quantum-serverless"
description = "Execute Qiskit programs as long-running jobs and distribute them across many CPUs, GPUs, and QPUs."
licence = "Apache License 2.0"
contact_info = "blake.johnson@ibm.com"
alternatives = "_No response_"
labels = [ "Software development kit",]
created_at = 1670427445.627174
updated_at = 1670427445.627175
stars = 47
group = "other"
