name = "Qubit"
url = "https://github.com/R-D-BioTech-Alaska/Qubit"
description = "Implements real-world n-level Cubit (physics) and Qubit (Qiskit) abstractions with subspace, noise, and device realism."
licence = "MIT license"
contact_info = "contact@qelm.org"
affiliations = "R&D BioTech Alaska"
labels = []
group = "Circuit simulator"
uuid = "5870b3e3-0c86-4506-aa73-1d6b1f172b7c"
badge = "https://qisk.it/e-5870b3e3"

[github]
url = "https://github.com/R-D-BioTech-Alaska/Qubit"
owner = "R-D-BioTech-Alaska"
repo = "Qubit"
stars = 4
license = "MIT License"
description = "Hybrid Qubit for real world applications"
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2025-12-10T02:02:16Z
last_activity = 2025-12-10T02:02:17Z
