name = "Qubit"
url = "https://github.com/R-D-BioTech-Alaska/Qubit"
description = "Implements real-world n-level Cubit (physics) and Qubit (Qiskit) abstractions with subspace, noise, and device realism."
licence = "MIT license"
contact_info = "contact@qelm.org"
affiliations = "R&D BioTech Alaska"
labels = []
group = "Circuit simulator"
uuid = "5870b3e3-0c86-4506-aa73-1d6b1f172b7c"
badge = "[![Qiskit Ecosystem](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fqiskit.github.io%2Fecosystem%2Fb%2F5870b3e3)](https://qisk.it/e)"

[github]
url = "https://github.com/R-D-BioTech-Alaska/Qubit"
owner = "R-D-BioTech-Alaska"
repo = "Qubit"
stars = 4
license = "MIT License"
description = "Hybrid Qubit for real world applications"
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2025-12-01T05:18:45Z
last_activity = 2025-12-01T05:18:46Z
