name = "quPython"
url = "https://github.com/frankharkins/quPython"
description = "Write quantum programs as Python functions instead of circuit objects. Create higher-level quantum data types and return measurement results as bool-like objects."
licence = "MIT license"
contact_info = "frankharkins@hotmail.co.uk"
alternatives = "_No response_"
affiliations = "_No response_"
labels = [ "Circuit", "Converter", "Productivity",]
tier = "Community"
tests_results = []
styles_results = []
coverages_results = []
skip_tests = false
historical_test_results = []
group = "other"
