name = "quPython"
url = "https://github.com/frankharkins/quPython"
description = "Write Pythonic quantum programs. Replace circuits and registers with functions and classes for better abstractions and readability."
licence = "MIT license"
contact_info = "frankharkins@hotmail.co.uk"
labels = [ "Circuit building tool", "Converter", "Software development kit",]
ibm_maintained = false
stars = 9
group = "other"
uuid = "bad95659-420a-4529-97d0-80e52532fc90"
