name = "quPython"
url = "https://github.com/frankharkins/quPython"
description = "Write Pythonic quantum programs. Replace circuits and registers with functions and classes for better abstractions and readability."
licence = "MIT license"
contact_info = "frankharkins@hotmail.co.uk"
labels = [ "circuit building",]
group = "SDK"
uuid = "bad95659-420a-4529-97d0-80e52532fc90"
badge = "https://qisk.it/e-bad95659"

[github]
url = "https://github.com/frankharkins/quPython"
owner = "frankharkins"
repo = "quPython"
stars = 10
homepage = "https://frankharkins.github.io/quPython/"
license = "MIT License"
description = "Quantum programs in Python"
estimated_contributors = 2
total_dependent_repositories = 5
total_dependent_packages = 0
last_commit = 2024-10-09T21:34:04Z

[pypi.qupython]
package_name = "qupython"
version = "0.2.0"
url = "https://pypi.org/project/qupython/"
requires_qiskit = ">=0"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2025-10-22T14:47:06Z
highest_supported_qiskit_version = "2.2.2"
last_month_downloads = 20
last_180_days_downloads = 109
