name = "Qutes Programming Language"
url = "https://github.com/GabrieleMessina/qutes_lang"
description = "A high-level quantum language that doesn't require deep theoretical expertise. For diverse domains of research and application."
licence = "MIT license"
contact_info = "gabryelemessina99@gmail.com"
labels = [ "Circuit building tool", "Software development kit", "Algorithms",]
website = "https://gabrielemessina.github.io/qutes_lang/"
group = "Other"
documentation = "https://github.com/GabrieleMessina/qutes_lang/wiki"
uuid = "79b52453-af83-4d4e-8d9b-e54a5ec7e326"
badge = "[![Qiskit Ecosystem](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fqiskit.github.io%2Fecosystem%2Fb%2F79b52453)](https://qisk.it/e)"

[github]
url = "https://github.com/GabrieleMessina/qutes_lang"
owner = "GabrieleMessina"
repo = "qutes_lang"
stars = 10
homepage = "https://gabrielemessina.github.io/qutes_lang/"
license = "MIT License"
description = "Qutes - A high level programming language for quantum computing."
estimated_contributors = 2
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2025-10-28T12:10:36Z
last_activity = 2025-11-12T20:36:53Z
