name = "Qutes Programming Language"
url = "https://github.com/GabrieleMessina/qutes_lang"
description = "A high-level quantum language that doesn't require deep theoretical expertise. For diverse domains of research and application."
licence = "MIT license"
contact_info = "gabryelemessina99@gmail.com"
labels = [ "circuit manipulation",]
website = "https://gabrielemessina.github.io/qutes_lang/"
group = "SDK"
documentation = "https://github.com/GabrieleMessina/qutes_lang/wiki"
uuid = "79b52453-af83-4d4e-8d9b-e54a5ec7e326"
badge = "https://qisk.it/e-79b52453"

[github]
url = "https://github.com/GabrieleMessina/qutes_lang"
owner = "GabrieleMessina"
repo = "qutes_lang"
stars = 14
homepage = "https://gabrielemessina.github.io/qutes_lang/"
license = "MIT License"
description = "Qutes - A high level programming language for quantum computing."
estimated_contributors = 2
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2025-11-30T17:44:51Z
last_activity = 2026-01-13T15:53:36Z
