name = "Qx86"
url = "https://github.com/mistasparkaru/Qx86"
description = "Qx86 is an Intel 8080/Z80 emulator which executes all salient points of Intel 8080/Z80 execution on IBM's quantum computers."
licence = "GNU General Public License (GPL)"
contact_info = "mistasparkaru@hotmail.co.uk"
affiliations = "None"
labels = [ "Software development kit",]
website = "https://github.com/mistasparkaru/Qx86"
group = "Applications"
reference_paper = "https://ieeexplore.ieee.org/document/9878250"
documentation = "https://github.com/mistasparkaru/Qx86"
uuid = "a68e9142-dc31-4b9f-a851-413dd91222d7"
badge = "[![Qiskit Ecosystem](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fqiskit.github.io%2Fecosystem%2Fb%2Fa68e9142)](https://qisk.it/e)"

[github]
url = "https://github.com/mistasparkaru/Qx86"
owner = "mistasparkaru"
repo = "Qx86"
stars = 1
license = "GNU General Public License v3.0"
description = "Qx86 is an intel 8080/Z80 emulator written for IBMs Quantum Computers"
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2024-08-20T17:31:09Z
