name = "Qx86"
url = "https://github.com/mistasparkaru/Qx86"
description = "Qx86 is an Intel 8080/Z80 emulator which executes all salient points of Intel 8080/Z80 execution on IBM's quantum computers."
licence = "GNU General Public License (GPL)"
contact_info = "mistasparkaru@hotmail.co.uk"
affiliations = "None"
labels = [ "cloud service",]
website = "https://github.com/mistasparkaru/Qx86"
group = "Application"
reference_paper = "https://ieeexplore.ieee.org/document/9878250"
documentation = "https://github.com/mistasparkaru/Qx86"
uuid = "a68e9142-dc31-4b9f-a851-413dd91222d7"
badge = "https://qisk.it/e-a68e9142"

[github]
url = "https://github.com/mistasparkaru/Qx86"
owner = "mistasparkaru"
repo = "Qx86"
stars = 2
license = "GNU General Public License v3.0"
description = "Qx86 is an intel 8080/Z80 emulator written for IBMs Quantum Computers"
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2024-08-20T17:31:09Z
last_activity = 2026-02-03T00:00:08Z
