name = "RasQberry"
url = "https://github.com/JanLahmann/RasQberry"
description = "RasQberry is a functional model of IBM Quantum System One, and can run Qiskit on the integrated Raspberry Pi"
licence = "Apache License 2.0"
contact_info = "Jan.lahmann@de.ibm.com"
labels = [ "demo",]
created_at = 1674598082.072493
updated_at = 1674598082.072494
group = "Game"
uuid = "dfa4cfd2-0ef5-4536-b7ec-47cc982ed0d9"
badge = "https://qisk.it/e-dfa4cfd2"

[github]
url = "https://github.com/JanLahmann/RasQberry"
owner = "JanLahmann"
repo = "RasQberry"
stars = 155
license = "Apache License 2.0"
description = "The RasQberry project: Exploring Quantum Computing and Qiskit with a Raspberry Pi and a 3D Printer"
estimated_contributors = 10
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2025-10-28T10:02:29Z
last_activity = 2026-01-17T16:28:39Z
