name = "RasQberry"
url = "https://github.com/JanLahmann/RasQberry"
description = "RasQberry is a functional model of IBM Quantum System One, and can run Qiskit on the integrated Raspberry Pi"
licence = "Apache License 2.0"
contact_info = "Jan.lahmann@de.ibm.com"
alternatives = "_No response_"
labels = [ "Game",]
created_at = 1674598082.072493
updated_at = 1674598082.072494
stars = 128
group = "other"
