name = "spinoza"
url = "https://github.com/smu160/spinoza"
description = "One of the fastest open-source quantum state simulators. Spinoza has a Qiskit-like quantum circuit interface, runs on various computing environments, and supports multi-threading and distributed computing."
licence = "Apache License 2.0"
contact_info = "sy2685@columbia.edu"
alternatives = "_No response_"
affiliations = "_No response_"
labels = [ "Circuit simulator", "Rust",]
created_at = 1683727562.604629
updated_at = 1683727562.604634
tier = "Community"
tests_results = []
styles_results = []
coverages_results = []
skip_tests = true
historical_test_results = []
stars = 17
group = "other"
