name = "Implicit Solvent Model template"
url = "https://github.com/qiskit-community/qiskit-function-templates/tree/main/chemistry/sqd_pcm"
description = "A Qiskit Function template for the Implicit Solvent Model with SQD Qiskit addon, from IBM Quantum partnership with Cleveland Clinic"
licence = "Apache License 2.0"
affiliations = "Cleveland Clinic"
labels = [ "Applications", "Chemistry",]
ibm_maintained = true
group = "applications"
reference_paper = "https://pubs.acs.org/doi/10.1021/acs.jpcb.5c01030"
uuid = "fac11d8c-c0f4-426e-8c20-ac009726d417"
