name = "SSVQE"
url = "https://github.com/JoelHBierman/SSVQE"
description = "The SSVQE algorithm (https://arxiv.org/abs/1810.09434) is a generalization of VQE to find low-lying eigenstates of a Hermitian operator. This specific implementation of SSVQE carries out one optimization procedure using weights."
licence = "Apache License 2.0"
contact_info = "joel.bierman@duke.edu"
alternatives = "_No response_"
affiliations = "Duke University"
labels = [ "Algorithms", "Chemistry",]
tier = "Community"
styles_results = []
coverages_results = []
skip_tests = false
stars = 0
group = "applications"
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "1.0.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6782294308"
package_commit_hash = "af643eb09b22fc3833084b3112890b1aebdcbf92"
qiskit_version = "1.0.0"
timestamp = 1699348696.587452

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit"
package_version = "0.44.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624759281"
qiskit_version = "0.44.2"
timestamp = 1698140140.619623

[[tests_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6782294308"
qiskit_version = "0.45.0"
timestamp = 1699348351.418835

[[tests_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6782294308"
qiskit_version = "0.45.0"
timestamp = 1699348761.387919

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6310546097"
qiskit_version = "0.44.1"
timestamp = 1695720580.615558

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6310546097"
qiskit_version = "0.44.1"
timestamp = 1695720033.374617

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6545042350"
package_commit_hash = "62467839e8d4e263465c42118414e6e5eca3c776"
qiskit_version = "0.45.0"
timestamp = 1697535130.366886

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.44.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624759281"
qiskit_version = "0.44.2"
timestamp = 1698140137.914579

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6624759281"
qiskit_version = "0.44.2"
timestamp = 1698139509.437624

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6782294308"
qiskit_version = "0.45.0"
timestamp = 1699348761.387919

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "1.0.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6782294308"
package_commit_hash = "af643eb09b22fc3833084b3112890b1aebdcbf92"
qiskit_version = "1.0.0"
timestamp = 1699348696.587452

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6782294308"
qiskit_version = "0.45.0"
timestamp = 1699348351.418835

