name = "SSVQE"
url = "https://github.com/JoelHBierman/SSVQE"
description = "The SSVQE algorithm (https://arxiv.org/abs/1810.09434) is a generalization of VQE to find low-lying eigenstates of a Hermitian operator. This specific implementation of SSVQE carries out one optimization procedure using weights."
licence = "Apache License 2.0"
contact_info = "joel.bierman@duke.edu"
alternatives = "_No response_"
affiliations = "Duke University"
labels = [ "Algorithms", "Chemistry",]
tier = "Community"
styles_results = []
coverages_results = []
skip_tests = false
stars = 0
[[tests_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6157348078"
package_commit_hash = "cd507adc68a96a333bc62de7ce9799a245506f25"
qiskit_version = "0.45.0"
timestamp = 1694510879.815417

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6157348078"
qiskit_version = "0.44.1"
timestamp = 1694510982.250791

[[tests_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6157348078"
qiskit_version = "0.44.1"
timestamp = 1694510472.317145

[[tests_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6157348078"
qiskit_version = "0.44.1"
timestamp = 1694510978.156974

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6157348078"
qiskit_version = "0.44.1"
timestamp = 1694510978.156974

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6157348078"
package_commit_hash = "cd507adc68a96a333bc62de7ce9799a245506f25"
qiskit_version = "0.45.0"
timestamp = 1694510879.815417

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6157348078"
qiskit_version = "0.44.1"
<<<<<<< Updated upstream
timestamp = 1694510472.317145
=======
timestamp = 1693906223.950387
<<<<<<< Updated upstream
<<<<<<< Updated upstream
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes

