name = "symbolic-qiskit"
url = "https://github.com/ianchung621/symbolic-qiskit"
description = "Symbolic simulator for Qiskit circuits using sympy backend, supporting mid-circuit measurement and state inspection."
licence = "Apache License 2.0"
contact_info = "ianchung621@gmail.com"
affiliations = "National Taiwan University, Physics"
labels = [ "quantum information",]
group = "Circuit simulator"
uuid = "e10b8307-99fd-4d10-a046-3934bf9396a1"
badge = "https://qisk.it/e-e10b8307"

[github]
url = "https://github.com/ianchung621/symbolic-qiskit"
owner = "ianchung621"
repo = "symbolic-qiskit"
stars = 2
license = "Apache License 2.0"
description = "Symbolic simulator for Qiskit circuits using sympy backend, supporting mid-circuit measurement and state inspection."
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2025-06-27T15:45:56Z

[pypi.symbolic-qiskit]
package_name = "symbolic-qiskit"
version = "0.1.0a1"
url = "https://pypi.org/project/symbolic-qiskit/"
requires_qiskit = ">=0"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2025-10-22T14:47:06Z
highest_supported_qiskit_version = "2.2.2"
last_month_downloads = 5
last_180_days_downloads = 130
