name = "TorchQuantum"
url = "https://github.com/mit-han-lab/torchquantum"
description = "A PyTorch-centric hybrid classical-quantum dynamic neural networks framework."
licence = "Apache 2.0"
labels = [ "QML",]
created_at = 1678827878.611621
updated_at = 1678827878.611622
group = "Application"
uuid = "6fefeede-f98e-44df-aea0-149827358701"
badge = "https://qisk.it/e-6fefeede"

[github]
url = "https://github.com/mit-han-lab/torchquantum"
owner = "mit-han-lab"
repo = "torchquantum"
stars = 1587
homepage = "https://torchquantum.org"
license = "MIT License"
description = "A PyTorch-based framework for Quantum Classical Simulation, Quantum Machine Learning, Quantum Neural Networks, Parameterized Quantu..."
estimated_contributors = 30
total_dependent_repositories = 59
total_dependent_packages = 1
last_commit = 2025-10-28T01:51:40Z
last_activity = 2025-12-21T02:12:05Z

[pypi.torchquantum]
package_name = "torchquantum"
version = "0.1.8"
url = "https://pypi.org/project/torchquantum/"
requires_qiskit = "<1.0.0,>=0.39.0"
compatible_with_qiskit_v1 = false
compatible_with_qiskit_v2 = false
highest_supported_qiskit_release_date = 2024-09-27T11:19:37Z
highest_supported_qiskit_version = "0.46.3"
last_month_downloads = 1323
last_180_days_downloads = 8799
