name = "TorchQuantum"
url = "https://github.com/mit-han-lab/torchquantum"
description = "A PyTorch-centric hybrid classical-quantum dynamic neural networks framework."
licence = "Apache 2.0"
labels = [ "Machine learning", "Application package",]
ibm_maintained = false
created_at = 1678827878.611621
updated_at = 1678827878.611622
stars = 1342
group = "applications"
uuid = "6fefeede-f98e-44df-aea0-149827358701"
