name = "truncated Variational Hamiltonian Ansatz tVHA"
url = "https://github.com/cpossel/tvha"
description = "truncated Variational Hamiltonian Ansatz (tVHA) for calculation of ground state energies of molecular systems/fermionic Hamiltonians"
licence = "MIT license"
contact_info = "clemens.possel@ict.fraunhofer.de"
affiliations = "Fraunhofer Institute for Chemical Technology ICT"
labels = [ "chemistry", "research", "physics",]
group = "Application"
reference_paper = "https://arxiv.org/abs/2505.19772"
uuid = "6e4000a2-3a09-43ff-b738-d4b17a0df011"
badge = "https://qisk.it/e-6e4000a2"

[github]
url = "https://github.com/cpossel/tvha"
owner = "cpossel"
repo = "tvha"
stars = 1
license = "MIT License"
description = "Implementation of the (truncated) Variational Hamiltonian Ansatz (VHA/tVHA) for calculation of ground state energies of molecular s..."
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2025-07-22T09:46:14Z
