name = "vqls-prototype"
url = "https://github.com/QuantumApplicationLab/vqls-prototype"
description = "The Variational Quantum Linear Solver (VQLS) uses an optimization approach to solve linear systems of equations. The vqls-prototype allows to easily setup and deploy a VQLS instance on different backends through the use of qiskit primitives and the runtime library"
licence = "Apache License 2.0"
contact_info = "nicolas.gm.renaud@gmail.com"
alternatives = "The prototype builds on the qiskit-textbook chapter and tutorial. The prototype allows to use the primitives and use different cost function and test circuits to optimize the parameters."
affiliations = "Netherlands eScience Center @ Quantum Application Lab, Amsterdam NL"
labels = [ "Algorithms", "Optimization",]
created_at = 1683906067.55753
updated_at = 1683906067.557535
tier = "Community"
styles_results = []
coverages_results = []
skip_tests = false
stars = 2
[[tests_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6233534870"
package_commit_hash = "2d3632fee633413bb1883e411d1a26f76fc54e92"
qiskit_version = "0.45.0"
timestamp = 1695115743.603468

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6233534870"
qiskit_version = "0.44.1"
timestamp = 1695115848.977965

[[tests_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6233534870"
qiskit_version = "0.44.1"
timestamp = 1695115319.985544

[[tests_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6233534870"
qiskit_version = "0.44.1"
timestamp = 1695115844.838502

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = ""
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936779850"
qiskit_version = ""
timestamp = 1692695887.580608

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6233534870"
qiskit_version = "0.44.1"
timestamp = 1695115844.838502

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6233534870"
package_commit_hash = "2d3632fee633413bb1883e411d1a26f76fc54e92"
qiskit_version = "0.45.0"
timestamp = 1695115743.603468

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/6233534870"
qiskit_version = "0.44.1"
timestamp = 1695115319.985544

