name = "vqls-prototype"
url = "https://github.com/QuantumApplicationLab/vqls-prototype"
description = "The Variational Quantum Linear Solver (VQLS) uses an optimization approach to solve linear systems of equations. The vqls-prototype allows to easily setup and deploy a VQLS instance on different backends through the use of qiskit primitives and the runtime library"
licence = "Apache License 2.0"
contact_info = "nicolas.gm.renaud@gmail.com"
alternatives = "The prototype builds on the qiskit-textbook chapter and tutorial. The prototype allows to use the primitives and use different cost function and test circuits to optimize the parameters."
affiliations = "Netherlands eScience Center @ Quantum Application Lab, Amsterdam NL"
labels = [ "Algorithms", "Optimization",]
created_at = 1683906067.55753
updated_at = 1683906067.557535
styles_results = []
coverages_results = []
tier = "Community"
skip_tests = false
stars = 2
[[tests_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5924782315"
package_commit_hash = "7bc2bfd4f8dcc436aec5f85641e3ec07be15eb01"
qiskit_version = "0.45.0"
timestamp = 1692612528.13598

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5924782315"
qiskit_version = "0.44.1"
timestamp = 1692612528.135989

[[tests_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5924782315"
qiskit_version = "0.44.1"
timestamp = 1692612528.135992

[[tests_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = ""
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5924782315"
qiskit_version = ""
timestamp = 1692612528.009074

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5924782315"
package_commit_hash = "7bc2bfd4f8dcc436aec5f85641e3ec07be15eb01"
qiskit_version = "0.45.0"
timestamp = 1692612528.135999

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5924782315"
qiskit_version = "0.44.1"
timestamp = 1692612528.136002

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = ""
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5924782315"
qiskit_version = ""
timestamp = 1692612528.009074

