name = "Variational Quantum Linear Solver Prototype"
url = "https://github.com/QuantumApplicationLab/vqls-prototype"
description = "VQLS uses an optimization approach to solve systems of linear equations. Set up and deploy VQLS instances on different backends."
licence = "Apache License 2.0"
contact_info = "nicolas.gm.renaud@gmail.com"
alternatives = "The prototype builds on the qiskit-textbook chapter and tutorial. The prototype allows to use the primitives and use different cost function and test circuits to optimize the parameters."
affiliations = "Netherlands eScience Center @ Quantum Application Lab, Amsterdam NL"
labels = [ "Algorithms", "Optimization", "Application package",]
ibm_maintained = false
created_at = 1683906067.55753
updated_at = 1683906067.557535
stars = 14
group = "applications"
uuid = "05140a48-184b-491e-ac3c-d613ca05b3c8"
