name = "zoose-codespace"
url = "https://github.com/ianhellstrom/zoose-codespace"
description = "Run any major quantum library in your browser with only two clicks! No installation required. Ideal for beginners or coders on the go."
licence = "MIT license"
contact_info = "ian \\[..at..\\] databaseline \\[..dot..\\] tech"
labels = [ "Cloud service",]
ibm_maintained = false
created_at = 1670402642.907656
updated_at = 1670402642.907662
stars = 0
group = "other"
uuid = "255ca532-6ea0-404d-a7dc-7181cca2e5bd"
