name = "zoose-codespace"
url = "https://github.com/ianhellstrom/zoose-codespace"
description = "Run any major quantum library in your browser with only two clicks! No installation required. Ideal for beginners or coders on the go."
licence = "MIT license"
contact_info = "ian \\[..at..\\] databaseline \\[..dot..\\] tech"
labels = [ "cloud service",]
created_at = 1670402642.907656
updated_at = 1670402642.907662
website = "https://ianreppel.org/zoose-codespace/"
group = "Other"
uuid = "255ca532-6ea0-404d-a7dc-7181cca2e5bd"
badge = "https://qisk.it/e-255ca532"

[github]
url = "https://github.com/ianreppel/zoose-codespace"
owner = "ianreppel"
repo = "zoose-codespace"
stars = 0
homepage = "https://ianreppel.org/zoose-codespace/"
license = "MIT License"
description = "Zoose Quantum Codespace"
estimated_contributors = 2
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2025-02-21T13:55:43Z
