name: Test main tier of ecosystem

on:
  schedule:
    - cron:  '5 8 * * 2' # each Tuesday at 8 05
  workflow_dispatch:

jobs:
  compatibility_tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: [3.9]
    steps:
    - name: Get current datetime
      id: date
      run: echo "::set-output name=date::$(date +'%Y_%m_%d_%H_%M')"
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up tox env
      run: |
        pver=${{ matrix.python-version }}
        tox_env="-epy${pver/./}"
        echo tox_env
        echo TOX_ENV=$tox_env >> $GITHUB_ENV
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    # test runs with stable version of Qiskit
    - name: Stable version of Qiskit test for Qiskit-nature
      run: python manager.py python_stable_tests https://github.com/Qiskit/qiskit-nature --tox_python=py39
    - name: Stable version of Qiskit test for Qiskit-finance
      run: python manager.py python_stable_tests https://github.com/Qiskit/qiskit-finance --tox_python=py39

    # test runs with dev version of Qiskit
    - name: Dev version of Qiskit test for Qiskit-nature
      run: python manager.py python_dev_tests https://github.com/Qiskit/qiskit-nature --tox_python=py39
    - name: Dev version of Qiskit test for Qiskit-finance
      run: python manager.py python_dev_tests https://github.com/Qiskit/qiskit-finance --tox_python=py39

    - name: State of members.json file
      run: cat ecosystem/resources/members.json

    - name: Commit changes and create Pull Request
      if: ${{ success() }}
      id: cpr
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: Default tests run for ${{ steps.date.outputs.date }}.
        title: Default tests run for ${{ steps.date.outputs.date }}.
        body: Default tests run for ${{ steps.date.outputs.date }}.
        branch: default-tests-${{ steps.date.outputs.date }}
        base: main
