name: 'Close stale submissions'
on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * mon'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v10
        with:
          stale-issue-message: 'This submission is stale because it has been open 20 days with no activity. Comment or this will be closed in 10 days.'
          stale-pr-message: 'This submission is stale because it has been open for 20 days with no activity. Please address any comments from the review; otherwise, it will be closed in 10 days.'
          close-issue-message: 'This submission was closed because it has been stalled. Feel free to submit a new request if you still want this project to be part of the Qiskit Ecosystem.'
          days-before-stale: 20
          days-before-close: 10
          stale-issue-label: 'stale?'
          any-of-labels: submission
          delete-branch: true
