name: Ecosystem | Project tests workflow

on:
  #  Payload:
  #  "client_payload": {
  #    "tier": "COMMUNITY", # 'Tier of project'
  #    "branch_name": "weekly-checks-1", # 'Branch name to push changes'
  #    "issue_id": 49, # 'Id of issue to put comments in'
  #    "repo_name": "demo-implementation", # 'Repository name'
  #    "repo_url": "https://github.com/IceKhan13/demo-implementation" # 'Repository URL'
  #  }
  repository_dispatch:
    types: [ check_project ]

jobs:
  project_check_job:
    runs-on: ubuntu-latest
    steps:
    - name: Setup variables
      id: vars
      run: |
        echo "Running check for ${{ github.event.client_payload.repo_url }}..."
        echo "Will be commenting in ${{ github.event.client_payload.issue_id }}..."
        echo "Will push changes to ${{ github.event.client_payload.branch_name }}..."
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.client_payload.branch_name }}
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
          python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Standard tests
      id: standard
      uses: ./.github/actions/run-tests
      with:
        repo_url: ${{ github.event.client_payload.repo_url }}
        check_type: "test_standard"
        tox_env: "py39"
        tier: ${{ github.event.client_payload.tier }}
        run_name: ${{ github.event.client_payload.branch_name }}

    - name: Stable tests
      id: stable
      uses: ./.github/actions/run-tests
      with:
        repo_url: ${{ github.event.client_payload.repo_url }}
        check_type: "test_stable"
        tox_env: "py39"
        tier: ${{ github.event.client_payload.tier }}
        run_name: ${{ github.event.client_payload.branch_name }}

    - name: Dev tests
      id: dev
      uses: ./.github/actions/run-tests
      with:
        repo_url: ${{ github.event.client_payload.repo_url }}
        check_type: "test_dev"
        tox_env: "py39"
        tier: ${{ github.event.client_payload.tier }}
        run_name: ${{ github.event.client_payload.branch_name }}

    - name: Styles check
      id: linter
      uses: ./.github/actions/run-tests
      with:
        repo_url: ${{ github.event.client_payload.repo_url }}
        check_type: "lint"
        tox_env: "py39"
        tier: ${{ github.event.client_payload.tier }}
        run_name: ${{ github.event.client_payload.branch_name }}

    - name: Coverage check
      id: coverage
      uses: ./.github/actions/run-tests
      with:
        repo_url: ${{ github.event.client_payload.repo_url }}
        check_type: "coverage"
        tox_env: "py39"
        tier: ${{ github.event.client_payload.tier }}
        run_name: ${{ github.event.client_payload.branch_name }}

    # check if any of the tests failed
    - name: Check return
      run: |
        echo "PASS_LOG=True" >> $GITHUB_ENV

        declare -a return_list=( \
          "${{ steps.standard.outputs.result }}" \
          "${{ steps.linter.outputs.result }}" \
          "${{ steps.coverage.outputs.result }}" \
          "${{ steps.stable.outputs.result }}" \
          "${{ steps.dev.outputs.result }}" \
        )
        for i in "${return_list[@]}"; do
          if [[ "${i}" != *"True"* ]]; then
            echo "PASS_LOG=False" >> $GITHUB_ENV
          fi
        done

    - name: Check the check
      id: check_result
      run: |
        echo "Pass log is ${{ env.PASS_LOG }}"
        
    - name: Commit changes
      run: |
        git pull --rebase --autostash
        git add ecosystem/resources/
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "Tests for ${{ github.event.client_payload.repo_url }}" --allow-empty
        git pull --rebase --autostash
        git push
        
    - name: Create comment on failure
      if: ${{ env.PASS_LOG == 'False' }}
      uses: peter-evans/create-or-update-comment@v1
      with:
        repository: "qiskit-community/ecosystem"
        issue-number: ${{ github.event.client_payload.issue_id }}
        body: |
          Failed project check ${{ github.event.client_payload.repo_url }} :warning:
          Error see: https://github.com/qiskit-community/ecosystem/actions/runs/${{ github.run_id }}
          If you don't fix this issue, your badge will change to grey automatically.

          ### Checks Status ###
          Linter : ${{ steps.linter.outputs.result }}
          Coverage : ${{ steps.coverage.outputs.result }}
          Qiskit Stable : ${{ steps.stable.outputs.result }}
          Qiskit Dev : ${{ steps.dev.outputs.result }}
          Standard: ${{ steps.standard.outputs.result }}

          ### Logs ###
          <details>
          <summary>Linter</summary>

          #### Error logs
          ${{ steps.linter.outputs.error }}

          #### Failed logs
          ${{ steps.linter.outputs.fail }}
          </details>
          <details>
          <summary>Coverage</summary>

          #### Error logs
          ${{ steps.coverage.outputs.error }}

          #### Failed logs
          ${{ steps.coverage.outputs.fail }}
          </details>
          <details>
          <summary>Qiskit Stable</summary>

          #### Error logs
          ${{ steps.stable.outputs.error }}

          #### Failed logs
          ${{ steps.stable.outputs.fail }}
          </details>
          <details>
          <summary>Qiskit Dev</summary>
          
          #### Qiskit depreciation logs
          ${{ steps.dev.outputs.depreciation }}

          #### Error logs
          ${{ steps.dev.outputs.error }}

          #### Failed logs
          ${{ steps.dev.outputs.fail }}
          </details>
          <details>
          <summary>Standard</summary>

          #### Error logs
          ${{ steps.standard.outputs.error }}

          #### Failed logs
          ${{ steps.standard.outputs.fail }}
          </details>
