name: Ecosystem | Batch | generate badges

on:
  workflow_dispatch:
    inputs:
      tier:
        description: 'Ecosystem tier'
        required: false
        default: "COMMUNITY"

jobs:
  batch_update_badges:
    runs-on: ubuntu-latest
    env:
      ISSUE_ID: 49
    steps:
    - name: Setup variables
      id: vars
      run: |
        echo "::set-output name=datetime::$(date +'%Y_%m_%d_%H_%M')"
        echo "::set-output name=pr_branch_name::batch_badges_$(date +'%Y_%m_%d_%H_%M')"
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
          python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Update badges
      run: python manager.py update_badges

    - name: Create PR for batch badge
      id: cpr
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: Batch badges for ${{ steps.vars.outputs.datetime }}
        title: Batch badges for ${{ steps.vars.outputs.datetime }}
        body: |
          Batch badges
          Time: ${{ steps.vars.outputs.datetime }}
          Tier: ${{ github.event.inputs.tier }}
        branch: ${{ steps.vars.outputs.pr_branch_name }}
        base: main

