name: Ecosystem | Fetch tests results from GitHub action runs of main repositories
# Fetch tests results from GitHub action runs for Main tier projects

on:
  workflow_dispatch:

jobs:
  fetch_results_for_main_repos:
    runs-on: ubuntu-latest
    env:
      tox_env: "py39"
      python-version: "3.9"
      repository: "qiskit-community/ecosystem"
    steps:
    - name: Setup variables
      id: vars
      run: |
        echo "datetime=$(date +'%Y_%m_%d_%H_%M')" >> "$GITHUB_OUTPUT"
        echo "pr_branch_name=fetch_tests_for_main_$(date +'%Y_%m_%d_%H_%M')" >> "$GITHUB_OUTPUT"
    - uses: actions/checkout@v3
    - name: Set up Python ${{ env.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Fetch test results
      run: python manager.py fetch_and_update_main_tests_results

    - name: Create PR for batch checks
      id: cpr
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: Fetch tests results for main projects.
        title: AUTO ${{ steps.vars.outputs.datetime }} | Fetch tests results for main projects
        body: |
          ${{ steps.vars.outputs.datetime }} | Fetch tests results for main projects
        branch: ${{ steps.vars.outputs.pr_branch_name }}
        base: main
