name: Ecosystem | Batch | check projects

on:
  workflow_dispatch:
  schedule:
  - cron:  '0 9 * * 2'

jobs:
  batch_repo_check:
    runs-on: ubuntu-latest
    steps:
    - name: Setup variables
      id: vars
      run: |
        echo "datetime=$(date +'%Y_%m_%d_%H_%M')" >> "$GITHUB_OUTPUT"
        echo "pr_branch_name=batch_checks_$(date +'%Y_%m_%d_%H_%M')" >> "$GITHUB_OUTPUT"
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
          python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Add check time
      run:  echo ${{ steps.vars.outputs.datetime }} >> check_time.txt
    - name: Create PR for batch checks
      id: cpr
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: Batch checks for ${{ steps.vars.outputs.datetime }}
        title: Batch checks | ${{ steps.vars.outputs.datetime }}
        body: |
          Batch checks
          Time: ${{ steps.vars.outputs.datetime }}
        branch: ${{ steps.vars.outputs.pr_branch_name }}
        base: main
    - name: Get project for check
      id: repos
      run: python manager.py expose_all_project_to_actions
    - name: Launch separate workflows for each project check
      run: |
        IFS=',' read -r -a repositories <<< ${{ steps.repos.outputs.repositories }}
        IFS=',' read -r -a tiers <<< ${{ steps.repos.outputs.tiers }}

        for (( i=0; i<${#repositories[*]}; ++i)); do
          echo "Launching separate workflow for ${repositories[$i]} in ${tiers[$i]} tier"
          python manager.py dispatch_check_workflow \
                            --repo_url=${repositories[$i]} \
                            --branch_name=${{ steps.vars.outputs.pr_branch_name }} \
                            --tier=${tiers[$i]} \
                            --token=${{ secrets.WORKFLOW_DISPATCH_PAT }} \
                            --owner=${{ github.repository_owner }}
        done
