name: Create stats and badge

on:
  pull_request_review:
    types: [submitted]

jobs:
  create_stats:
    if: >
      github.event.review.state == 'approved'
      && startsWith(github.event.pull_request.title, 'Add ')
      && contains(github.event.pull_request.labels.*.name, 'submission')
    runs-on: ubuntu-latest
    steps:
      - name: Setup variables
        id: get-id
        run: |
          id=$(echo ${{ github.event.pull_request.head.ref }} | cut -d- -f2 )
          echo "::set-output name=id::$id"
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - uses: actions/checkout@v5
      - name: Checkout PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr checkout ${{ github.event.pull_request.number }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Update stats
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name 'GitHub'
          git config user.email 'noreply@github.com'
          python manager.py members update_github ${{ steps.get-id.outputs.id }}
          git commit -am "Modify tracked file during workflow"
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push --verbose